import type { ObjectShape } from './shapeCatalog';

export type { ObjectShape };

export interface ObjectItem {
  id: string;
  label: string;
  shape: ObjectShape;
  minLevel: 1 | 2 | 3;
}

import { OBJECT_SUPPLEMENT } from './objectSupplement';
import { OBJECT_SUPPLEMENT_EXTRA } from './objectSupplementExtra';
import { OBJECT_SUPPLEMENT_WAVE3 } from './objectSupplementWave3';

/** Đồ vật nhận dạng hình học (tên không gợi ý dạng hình). */
export const OBJECT_BANK: ObjectItem[] = [
  { id: 'o001', label: 'Cửa sổ nhà', shape: 'square', minLevel: 1 },
  { id: 'o002', label: 'Gạch lát sân', shape: 'square', minLevel: 1 },
  { id: 'o003', label: 'Ô bàn cờ', shape: 'square', minLevel: 1 },
  { id: 'o004', label: 'Khung tranh treo', shape: 'square', minLevel: 1 },
  { id: 'o005', label: 'Bánh chưng', shape: 'square', minLevel: 1 },
  { id: 'o006', label: 'Thảm trải sàn', shape: 'square', minLevel: 1 },
  { id: 'o007', label: 'Quà sinh nhật', shape: 'square', minLevel: 1 },
  { id: 'o008', label: 'Mặt đồng hồ treo tường', shape: 'circle', minLevel: 1 },
  { id: 'o009', label: 'Gương treo', shape: 'square', minLevel: 1 },
  { id: 'o010', label: 'Khay đựng đồ', shape: 'rect', minLevel: 1 },
  { id: 'o011', label: 'Nắp hộp sữa', shape: 'square', minLevel: 1 },
  { id: 'o012', label: 'Bánh quy', shape: 'circle', minLevel: 1 },
  { id: 'o013', label: 'Rubik', shape: 'square', minLevel: 2 },
  { id: 'o014', label: 'Bìa cứng', shape: 'rect', minLevel: 2 },
  { id: 'o015', label: 'Chocolate', shape: 'rect', minLevel: 2 },
  { id: 'o016', label: 'Pin mặt trời', shape: 'square', minLevel: 2 },
  { id: 'o017', label: 'Khung cửa sổ', shape: 'square', minLevel: 2 },
  { id: 'o018', label: 'Gạch men', shape: 'rhombus', minLevel: 2 },
  { id: 'o019', label: 'Lót ly', shape: 'circle', minLevel: 2 },
  { id: 'o020', label: 'Sandwich kẹp', shape: 'rect', minLevel: 2 },
  { id: 'o021', label: 'Mặt sàn gạch hoa', shape: 'square', minLevel: 2 },
  { id: 'o022', label: 'Decal dán tường', shape: 'square', minLevel: 3 },
  { id: 'o023', label: 'Xúc xắc', shape: 'square', minLevel: 3 },
  { id: 'o024', label: 'Miếng đậu phụ', shape: 'square', minLevel: 3 },
  { id: 'o025', label: 'Kính an toàn', shape: 'square', minLevel: 3 },
  { id: 'o026', label: 'Khăn quàng cổ', shape: 'rect', minLevel: 3 },
  { id: 'o027', label: 'Phô mai', shape: 'square', minLevel: 3 },
  { id: 'o028', label: 'Ván sàn', shape: 'rect', minLevel: 3 },
  { id: 'o029', label: 'Bánh flan', shape: 'square', minLevel: 3 },
  { id: 'o030', label: 'Lego đỏ', shape: 'square', minLevel: 3 },
  { id: 'o031', label: 'Mặt bàn ăn', shape: 'rect', minLevel: 3 },
  { id: 'o032', label: 'Mica trong', shape: 'rect', minLevel: 3 },
  { id: 'o033', label: 'Bánh kẹp', shape: 'rect', minLevel: 3 },
  { id: 'o034', label: 'Đế bàn cờ', shape: 'square', minLevel: 3 },

  { id: 'o035', label: 'Cổng nhà gạch', shape: 'rect', minLevel: 1 },
  { id: 'o036', label: 'Dầm gỗ', shape: 'rect', minLevel: 1 },
  { id: 'o037', label: 'Biển báo', shape: 'rect', minLevel: 1 },
  { id: 'o038', label: 'Gạch ống', shape: 'rect', minLevel: 1 },
  { id: 'o039', label: 'Mặt bàn học', shape: 'rect', minLevel: 1 },
  { id: 'o040', label: 'Thước kẻ 30cm', shape: 'rect', minLevel: 1 },
  { id: 'o041', label: 'Cửa phòng', shape: 'rect', minLevel: 1 },
  { id: 'o042', label: 'Bút chì', shape: 'rect', minLevel: 1 },
  { id: 'o043', label: 'Bánh mì', shape: 'triangle', minLevel: 1 },
  { id: 'o044', label: 'Thẻ học từ', shape: 'rect', minLevel: 1 },
  { id: 'o045', label: 'Sữa tươi', shape: 'rect', minLevel: 1 },
  { id: 'o046', label: 'Thớt gỗ', shape: 'rect', minLevel: 2 },
  { id: 'o047', label: 'Khay sách nhiều ngăn', shape: 'rect', minLevel: 2 },
  { id: 'o048', label: 'Ván gỗ', shape: 'rect', minLevel: 2 },
  { id: 'o049', label: 'Pin tiểu', shape: 'rect', minLevel: 2 },
  { id: 'o050', label: 'Mặt quyển vở', shape: 'rect', minLevel: 2 },
  { id: 'o051', label: 'Cây tre', shape: 'rect', minLevel: 2 },
  { id: 'o052', label: 'Bánh đa nem', shape: 'rect', minLevel: 2 },
  { id: 'o053', label: 'Thân diều', shape: 'rect', minLevel: 2 },
  { id: 'o054', label: 'Vải cuộn', shape: 'rect', minLevel: 2 },
  { id: 'o055', label: 'Viên nem rán', shape: 'rect', minLevel: 2 },
  { id: 'o056', label: 'Mặt bảng đen', shape: 'rect', minLevel: 2 },
  { id: 'o057', label: 'Khay đựng chén', shape: 'rect', minLevel: 2 },
  { id: 'o058', label: 'Bài úp', shape: 'rect', minLevel: 3 },
  { id: 'o059', label: 'Tấm kim loại', shape: 'rect', minLevel: 3 },
  { id: 'o060', label: 'Hộp đồ dùng học', shape: 'rect', minLevel: 3 },
  { id: 'o061', label: 'Quạt trần', shape: 'rect', minLevel: 3 },
  { id: 'o062', label: 'Bánh phở', shape: 'rect', minLevel: 3 },
  { id: 'o063', label: 'Remote tv', shape: 'rect', minLevel: 3 },
  { id: 'o064', label: 'Xà beng nhỏ', shape: 'parallelogram', minLevel: 3 },
  { id: 'o065', label: 'Thẻ từ vựng', shape: 'rect', minLevel: 3 },
  { id: 'o066', label: 'Chuồn chuồn giấy', shape: 'rect', minLevel: 3 },
  { id: 'o067', label: 'Gỗ pallet', shape: 'rect', minLevel: 3 },

  { id: 'o068', label: 'Mái nhà ngói', shape: 'trapezoid', minLevel: 1 },
  { id: 'o069', label: 'Lá cờ đuôi nõn', shape: 'rect', minLevel: 1 },
  { id: 'o070', label: 'Nêm cao su tường', shape: 'triangle', minLevel: 1 },
  { id: 'o071', label: 'Buồm thuyền', shape: 'triangle', minLevel: 1 },
  { id: 'o072', label: 'Miếng pizza', shape: 'triangle', minLevel: 1 },
  { id: 'o073', label: 'Eke nhạc gỗ', shape: 'triangle', minLevel: 1 },
  { id: 'o074', label: 'Mái chùa con', shape: 'trapezoid', minLevel: 1 },
  { id: 'o075', label: 'Én', shape: 'triangle', minLevel: 1 },
  { id: 'o076', label: 'Nón lá', shape: 'triangle', minLevel: 1 },
  { id: 'o077', label: 'Mái hiên che', shape: 'trapezoid', minLevel: 1 },
  { id: 'o078', label: 'Bánh sandwich cắt', shape: 'triangle', minLevel: 2 },
  { id: 'o079', label: 'Kim tự tháp nhỏ', shape: 'triangle', minLevel: 2 },
  { id: 'o080', label: 'Diều đuôi', shape: 'triangle', minLevel: 2 },
  { id: 'o081', label: 'Phô mai múi', shape: 'triangle', minLevel: 2 },
  { id: 'o082', label: 'Biển báo giao thông', shape: 'triangle', minLevel: 2 },
  { id: 'o083', label: 'Lều cắm trại', shape: 'trapezoid', minLevel: 2 },
  { id: 'o084', label: 'Máy bay nhỏ', shape: 'triangle', minLevel: 2 },
  { id: 'o085', label: 'Bánh kem', shape: 'triangle', minLevel: 2 },
  { id: 'o086', label: 'Nêm cá hồng', shape: 'triangle', minLevel: 2 },
  { id: 'o087', label: 'Mái lều cắm trại', shape: 'trapezoid', minLevel: 2 },
  { id: 'o088', label: 'Thuyền buồm', shape: 'triangle', minLevel: 3 },
  { id: 'o089', label: 'Đá mài', shape: 'triangle', minLevel: 3 },
  { id: 'o090', label: 'Snack giòn', shape: 'triangle', minLevel: 3 },
  { id: 'o091', label: 'Nêm xà phòng', shape: 'rect', minLevel: 3 },
  { id: 'o092', label: 'Mái chắn nắng', shape: 'trapezoid', minLevel: 3 },
  { id: 'o093', label: 'Cọc tiêu', shape: 'rect', minLevel: 3 },
  { id: 'o094', label: 'Tàu lượn', shape: 'triangle', minLevel: 3 },
  { id: 'o095', label: 'Cơm nắm onigiri', shape: 'triangle', minLevel: 3 },
  { id: 'o096', label: 'Mái nhà sóng ngói', shape: 'trapezoid', minLevel: 3 },
  { id: 'o097', label: 'Gỗ chặt', shape: 'triangle', minLevel: 3 },
  { id: 'o098', label: 'Diều rồng', shape: 'triangle', minLevel: 3 },
  { id: 'o099', label: 'Miếng bánh dorito', shape: 'triangle', minLevel: 3 },
  { id: 'o100', label: 'Mica tím', shape: 'square', minLevel: 3 },
  ...OBJECT_SUPPLEMENT,
  ...OBJECT_SUPPLEMENT_EXTRA,
  ...OBJECT_SUPPLEMENT_WAVE3,
];

export const OBJECT_BANK_SIZE = OBJECT_BANK.length;
