export type ObjectShape = 'square' | 'rect' | 'triangle';

export interface ObjectItem {
  id: string;
  label: string;
  shape: ObjectShape;
  minLevel: 1 | 2 | 3;
}

import { OBJECT_SUPPLEMENT } from './objectSupplement';

/** Đồ vật nhận dạng hình học (tên không gợi ý dạng hình). */
export const OBJECT_BANK: ObjectItem[] = [
  { id: 'o001', label: 'Cửa sổ nhà', shape: 'square', minLevel: 1 },
  { id: 'o002', label: 'Viên gạch lát sân', shape: 'square', minLevel: 1 },
  { id: 'o003', label: 'Ô bàn cờ', shape: 'square', minLevel: 1 },
  { id: 'o004', label: 'Khung tranh treo', shape: 'square', minLevel: 1 },
  { id: 'o005', label: 'Miếng bánh chưng', shape: 'square', minLevel: 1 },
  { id: 'o006', label: 'Tấm thảm trải sàn', shape: 'square', minLevel: 1 },
  { id: 'o007', label: 'Hộp quà sinh nhật', shape: 'square', minLevel: 1 },
  { id: 'o008', label: 'Mặt đồng hồ treo tường', shape: 'square', minLevel: 1 },
  { id: 'o009', label: 'Tấm gương treo', shape: 'square', minLevel: 1 },
  { id: 'o010', label: 'Khay đựng đồ', shape: 'square', minLevel: 1 },
  { id: 'o011', label: 'Nắp hộp sữa', shape: 'square', minLevel: 1 },
  { id: 'o012', label: 'Miếng bánh quy', shape: 'square', minLevel: 1 },
  { id: 'o013', label: 'Khối rubik', shape: 'square', minLevel: 2 },
  { id: 'o014', label: 'Tấm bìa cứng', shape: 'square', minLevel: 2 },
  { id: 'o015', label: 'Miếng chocolate', shape: 'square', minLevel: 2 },
  { id: 'o016', label: 'Tấm pin mặt trời', shape: 'square', minLevel: 2 },
  { id: 'o017', label: 'Khung cửa sổ', shape: 'square', minLevel: 2 },
  { id: 'o018', label: 'Viên gạch men', shape: 'square', minLevel: 2 },
  { id: 'o019', label: 'Tấm lót ly', shape: 'square', minLevel: 2 },
  { id: 'o020', label: 'Miếng sandwich kẹp', shape: 'square', minLevel: 2 },
  { id: 'o021', label: 'Mặt sàn gạch hoa', shape: 'square', minLevel: 2 },
  { id: 'o022', label: 'Tấm decal dán tường', shape: 'square', minLevel: 3 },
  { id: 'o023', label: 'Khối xúc xắc', shape: 'square', minLevel: 3 },
  { id: 'o024', label: 'Miếng tofu', shape: 'square', minLevel: 3 },
  { id: 'o025', label: 'Tấm kính an toàn', shape: 'square', minLevel: 3 },
  { id: 'o026', label: 'Khăn quàng cổ', shape: 'square', minLevel: 3 },
  { id: 'o027', label: 'Viên phô mai', shape: 'square', minLevel: 3 },
  { id: 'o028', label: 'Tấm ván sàn', shape: 'square', minLevel: 3 },
  { id: 'o029', label: 'Miếng bánh flan', shape: 'square', minLevel: 3 },
  { id: 'o030', label: 'Khối LEGO đỏ', shape: 'square', minLevel: 3 },
  { id: 'o031', label: 'Mặt bàn ăn', shape: 'square', minLevel: 3 },
  { id: 'o032', label: 'Tấm mica trong', shape: 'square', minLevel: 3 },
  { id: 'o033', label: 'Miếng bánh kẹp', shape: 'square', minLevel: 3 },
  { id: 'o034', label: 'Khối đế bàn cờ', shape: 'square', minLevel: 3 },

  { id: 'o035', label: 'Cổng nhà gạch', shape: 'rect', minLevel: 1 },
  { id: 'o036', label: 'Thanh dầm gỗ', shape: 'rect', minLevel: 1 },
  { id: 'o037', label: 'Tấm biển báo', shape: 'rect', minLevel: 1 },
  { id: 'o038', label: 'Viên gạch ống', shape: 'rect', minLevel: 1 },
  { id: 'o039', label: 'Mặt bàn học', shape: 'rect', minLevel: 1 },
  { id: 'o040', label: 'Thước kẻ 30cm', shape: 'rect', minLevel: 1 },
  { id: 'o041', label: 'Cánh cửa phòng', shape: 'rect', minLevel: 1 },
  { id: 'o042', label: 'Hộp bút chì', shape: 'rect', minLevel: 1 },
  { id: 'o043', label: 'Miếng bánh mì', shape: 'rect', minLevel: 1 },
  { id: 'o044', label: 'Tấm thẻ học từ', shape: 'rect', minLevel: 1 },
  { id: 'o045', label: 'Hộp sữa tươi', shape: 'rect', minLevel: 1 },
  { id: 'o046', label: 'Tấm thớt gỗ', shape: 'rect', minLevel: 2 },
  { id: 'o047', label: 'Khay sách nhiều ngăn', shape: 'rect', minLevel: 2 },
  { id: 'o048', label: 'Tấm ván gỗ', shape: 'rect', minLevel: 2 },
  { id: 'o049', label: 'Viên pin tiểu', shape: 'rect', minLevel: 2 },
  { id: 'o050', label: 'Mặt quyển vở', shape: 'rect', minLevel: 2 },
  { id: 'o051', label: 'Thanh tre', shape: 'rect', minLevel: 2 },
  { id: 'o052', label: 'Tấm bánh đa nem', shape: 'rect', minLevel: 2 },
  { id: 'o053', label: 'Cánh diều thân', shape: 'rect', minLevel: 2 },
  { id: 'o054', label: 'Tấm vải cuộn', shape: 'rect', minLevel: 2 },
  { id: 'o055', label: 'Viên nem rán', shape: 'rect', minLevel: 2 },
  { id: 'o056', label: 'Mặt bảng đen', shape: 'rect', minLevel: 2 },
  { id: 'o057', label: 'Khay đựng chén', shape: 'rect', minLevel: 2 },
  { id: 'o058', label: 'Thẻ bài úp', shape: 'rect', minLevel: 3 },
  { id: 'o059', label: 'Tấm kim loại mỏng', shape: 'rect', minLevel: 3 },
  { id: 'o060', label: 'Hộp đồ dùng học', shape: 'rect', minLevel: 3 },
  { id: 'o061', label: 'Cánh quạt trần', shape: 'rect', minLevel: 3 },
  { id: 'o062', label: 'Tấm bánh phở', shape: 'rect', minLevel: 3 },
  { id: 'o063', label: 'Viên remote TV', shape: 'rect', minLevel: 3 },
  { id: 'o064', label: 'Thanh xà beng nhỏ', shape: 'rect', minLevel: 3 },
  { id: 'o065', label: 'Tấm thẻ từ vựng', shape: 'rect', minLevel: 3 },
  { id: 'o066', label: 'Cánh chuồn chuồn giấy', shape: 'rect', minLevel: 3 },
  { id: 'o067', label: 'Tấm gỗ pallet', shape: 'rect', minLevel: 3 },

  { id: 'o068', label: 'Mái nhà ngói', shape: 'triangle', minLevel: 1 },
  { id: 'o069', label: 'Lá cờ đuôi nõn', shape: 'triangle', minLevel: 1 },
  { id: 'o070', label: 'Nêm cao su tường', shape: 'triangle', minLevel: 1 },
  { id: 'o071', label: 'Cánh buồm thuyền', shape: 'triangle', minLevel: 1 },
  { id: 'o072', label: 'Miếng pizza', shape: 'triangle', minLevel: 1 },
  { id: 'o073', label: 'Eke nhạc gỗ', shape: 'triangle', minLevel: 1 },
  { id: 'o074', label: 'Mái chùa con', shape: 'triangle', minLevel: 1 },
  { id: 'o075', label: 'Cánh én', shape: 'triangle', minLevel: 1 },
  { id: 'o076', label: 'Nón lá', shape: 'triangle', minLevel: 1 },
  { id: 'o077', label: 'Mái hiên che', shape: 'triangle', minLevel: 1 },
  { id: 'o078', label: 'Miếng bánh sandwich cắt', shape: 'triangle', minLevel: 2 },
  { id: 'o079', label: 'Kim tự tháp nhỏ', shape: 'triangle', minLevel: 2 },
  { id: 'o080', label: 'Cánh diều đuôi', shape: 'triangle', minLevel: 2 },
  { id: 'o081', label: 'Miếng phô mai múi', shape: 'triangle', minLevel: 2 },
  { id: 'o082', label: 'Biển báo giao thông', shape: 'triangle', minLevel: 2 },
  { id: 'o083', label: 'Lều cắm trại', shape: 'triangle', minLevel: 2 },
  { id: 'o084', label: 'Cánh máy bay nhỏ', shape: 'triangle', minLevel: 2 },
  { id: 'o085', label: 'Miếng bánh kem', shape: 'triangle', minLevel: 2 },
  { id: 'o086', label: 'Nêm cá hồng', shape: 'triangle', minLevel: 2 },
  { id: 'o087', label: 'Mái lều cắm trại', shape: 'triangle', minLevel: 2 },
  { id: 'o088', label: 'Cánh thuyền buồm', shape: 'triangle', minLevel: 3 },
  { id: 'o089', label: 'Khối đá mài', shape: 'triangle', minLevel: 3 },
  { id: 'o090', label: 'Miếng snack giòn', shape: 'triangle', minLevel: 3 },
  { id: 'o091', label: 'Nêm xà phòng', shape: 'triangle', minLevel: 3 },
  { id: 'o092', label: 'Mái chắn nắng', shape: 'triangle', minLevel: 3 },
  { id: 'o093', label: 'Khối cọc tiêu', shape: 'triangle', minLevel: 3 },
  { id: 'o094', label: 'Cánh tàu lượn', shape: 'triangle', minLevel: 3 },
  { id: 'o095', label: 'Miếng onigiri', shape: 'triangle', minLevel: 3 },
  { id: 'o096', label: 'Mái nhà sóng ngói', shape: 'triangle', minLevel: 3 },
  { id: 'o097', label: 'Khối gỗ chặt', shape: 'triangle', minLevel: 3 },
  { id: 'o098', label: 'Cánh diều rồng', shape: 'triangle', minLevel: 3 },
  { id: 'o099', label: 'Miếng dorito', shape: 'triangle', minLevel: 3 },
  { id: 'o100', label: 'Khối mica tím', shape: 'triangle', minLevel: 3 },
  ...OBJECT_SUPPLEMENT,
];

export const OBJECT_BANK_SIZE = OBJECT_BANK.length;
