import type { ObjectItem } from './objectBank';
/** Đồ vật hình học bổ sung — 150 mục */
export const OBJECT_SUPPLEMENT: ObjectItem[] = [
  { id: 'o101', label: 'Viên xúc xắc', shape: 'square', minLevel: 1 },
  { id: 'o102', label: 'Tấm viên xúc xắc trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o103', label: 'Miếng viên xúc xắc ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o104', label: 'Miếng phô mai vuông', shape: 'square', minLevel: 2 },
  { id: 'o105', label: 'Tấm miếng phô mai vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o106', label: 'Miếng miếng phô mai vuông ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o107', label: 'Tấm gương vuông', shape: 'square', minLevel: 1 },
  { id: 'o108', label: 'Tấm tấm gương vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o109', label: 'Miếng tấm gương vuông ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o110', label: 'Khay sushi', shape: 'square', minLevel: 2 },
  { id: 'o111', label: 'Tấm khay sushi trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o112', label: 'Miếng khay sushi ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o113', label: 'Miếng brownie', shape: 'square', minLevel: 1 },
  { id: 'o114', label: 'Tấm miếng brownie trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o115', label: 'Miếng miếng brownie ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o116', label: 'Tấm kính vuông', shape: 'square', minLevel: 2 },
  { id: 'o117', label: 'Tấm tấm kính vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o118', label: 'Miếng tấm kính vuông ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o119', label: 'Khối đá lát', shape: 'square', minLevel: 1 },
  { id: 'o120', label: 'Tấm khối đá lát trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o121', label: 'Miếng khối đá lát ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o122', label: 'Miếng bánh quy vuông', shape: 'square', minLevel: 2 },
  { id: 'o123', label: 'Tấm miếng bánh quy vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o124', label: 'Miếng miếng bánh quy vuông ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o125', label: 'Tấm thảm họa tiết', shape: 'square', minLevel: 1 },
  { id: 'o126', label: 'Tấm tấm thảm họa tiết trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o127', label: 'Miếng tấm thảm họa tiết ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o128', label: 'Hộp sữa vuông', shape: 'square', minLevel: 2 },
  { id: 'o129', label: 'Tấm hộp sữa vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o130', label: 'Miếng hộp sữa vuông ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o131', label: 'Miếng tofu vuông', shape: 'square', minLevel: 1 },
  { id: 'o132', label: 'Tấm miếng tofu vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o133', label: 'Miếng miếng tofu vuông ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o134', label: 'Tấm decal vuông', shape: 'square', minLevel: 2 },
  { id: 'o135', label: 'Tấm tấm decal vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o136', label: 'Miếng tấm decal vuông ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o137', label: 'Khối xếp hình', shape: 'square', minLevel: 1 },
  { id: 'o138', label: 'Tấm khối xếp hình trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o139', label: 'Miếng khối xếp hình ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o140', label: 'Miếng kẹo dẻo', shape: 'square', minLevel: 2 },
  { id: 'o141', label: 'Tấm miếng kẹo dẻo trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o142', label: 'Miếng miếng kẹo dẻo ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o143', label: 'Tấm bìa màu', shape: 'square', minLevel: 1 },
  { id: 'o144', label: 'Tấm tấm bìa màu trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o145', label: 'Miếng tấm bìa màu ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o146', label: 'Viên gạch mosaic', shape: 'square', minLevel: 2 },
  { id: 'o147', label: 'Tấm viên gạch mosaic trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o148', label: 'Miếng viên gạch mosaic ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o149', label: 'Miếng sandwich vuông', shape: 'square', minLevel: 1 },
  { id: 'o150', label: 'Tấm miếng sandwich vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o151', label: 'Miếng miếng sandwich vuông ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o152', label: 'Tấm lót bàn', shape: 'square', minLevel: 2 },
  { id: 'o153', label: 'Tấm tấm lót bàn trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o154', label: 'Miếng tấm lót bàn ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o155', label: 'Khung ảnh vuông', shape: 'square', minLevel: 1 },
  { id: 'o156', label: 'Tấm khung ảnh vuông trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o157', label: 'Miếng khung ảnh vuông ngoài sân', shape: 'square', minLevel: 1 },
  { id: 'o158', label: 'Miếng bánh flan', shape: 'square', minLevel: 2 },
  { id: 'o159', label: 'Tấm miếng bánh flan trên bàn', shape: 'square', minLevel: 3 },
  { id: 'o160', label: 'Miếng miếng bánh flan ngoài sân', shape: 'square', minLevel: 2 },
  { id: 'o161', label: 'Thẻ tên', shape: 'rect', minLevel: 1 },
  { id: 'o162', label: 'Tấm thẻ tên trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o163', label: 'Miếng thẻ tên ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o164', label: 'Cuốn sách mỏng', shape: 'rect', minLevel: 2 },
  { id: 'o165', label: 'Tấm cuốn sách mỏng trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o166', label: 'Miếng cuốn sách mỏng ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o167', label: 'Thước kẻ dài', shape: 'rect', minLevel: 1 },
  { id: 'o168', label: 'Tấm thước kẻ dài trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o169', label: 'Miếng thước kẻ dài ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o170', label: 'Hộp bút', shape: 'rect', minLevel: 2 },
  { id: 'o171', label: 'Tấm hộp bút trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o172', label: 'Miếng hộp bút ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o173', label: 'Tấm ván gỗ', shape: 'rect', minLevel: 1 },
  { id: 'o174', label: 'Tấm tấm ván gỗ trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o175', label: 'Miếng tấm ván gỗ ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o176', label: 'Viên gạch ống', shape: 'rect', minLevel: 2 },
  { id: 'o177', label: 'Tấm viên gạch ống trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o178', label: 'Miếng viên gạch ống ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o179', label: 'Cánh cửa phòng', shape: 'rect', minLevel: 1 },
  { id: 'o180', label: 'Tấm cánh cửa phòng trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o181', label: 'Miếng cánh cửa phòng ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o182', label: 'Tấm biển báo', shape: 'rect', minLevel: 2 },
  { id: 'o183', label: 'Tấm tấm biển báo trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o184', label: 'Miếng tấm biển báo ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o185', label: 'Khay đựng bút', shape: 'rect', minLevel: 1 },
  { id: 'o186', label: 'Tấm khay đựng bút trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o187', label: 'Miếng khay đựng bút ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o188', label: 'Hộp socola', shape: 'rect', minLevel: 2 },
  { id: 'o189', label: 'Tấm hộp socola trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o190', label: 'Miếng hộp socola ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o191', label: 'Tờ giấy A4', shape: 'rect', minLevel: 1 },
  { id: 'o192', label: 'Tấm tờ giấy a4 trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o193', label: 'Miếng tờ giấy a4 ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o194', label: 'Miếng bánh mì', shape: 'rect', minLevel: 2 },
  { id: 'o195', label: 'Tấm miếng bánh mì trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o196', label: 'Miếng miếng bánh mì ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o197', label: 'Thẻ nhớ', shape: 'rect', minLevel: 1 },
  { id: 'o198', label: 'Tấm thẻ nhớ trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o199', label: 'Miếng thẻ nhớ ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o200', label: 'Hộp diêm', shape: 'rect', minLevel: 2 },
  { id: 'o201', label: 'Tấm hộp diêm trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o202', label: 'Miếng hộp diêm ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o203', label: 'Tấm thẻ học', shape: 'rect', minLevel: 1 },
  { id: 'o204', label: 'Tấm tấm thẻ học trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o205', label: 'Miếng tấm thẻ học ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o206', label: 'Băng dính cuộn', shape: 'rect', minLevel: 2 },
  { id: 'o207', label: 'Tấm băng dính cuộn trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o208', label: 'Miếng băng dính cuộn ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o209', label: 'Hộp sữa hộp', shape: 'rect', minLevel: 1 },
  { id: 'o210', label: 'Tấm hộp sữa hộp trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o211', label: 'Miếng hộp sữa hộp ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o212', label: 'Tấm menu', shape: 'rect', minLevel: 2 },
  { id: 'o213', label: 'Tấm tấm menu trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o214', label: 'Miếng tấm menu ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o215', label: 'Cánh tay ghế', shape: 'rect', minLevel: 1 },
  { id: 'o216', label: 'Tấm cánh tay ghế trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o217', label: 'Miếng cánh tay ghế ngoài sân', shape: 'rect', minLevel: 1 },
  { id: 'o218', label: 'Thân bút chì', shape: 'rect', minLevel: 2 },
  { id: 'o219', label: 'Tấm thân bút chì trên bàn', shape: 'rect', minLevel: 3 },
  { id: 'o220', label: 'Miếng thân bút chì ngoài sân', shape: 'rect', minLevel: 2 },
  { id: 'o221', label: 'Miếng pizza', shape: 'triangle', minLevel: 1 },
  { id: 'o222', label: 'Tấm miếng pizza trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o223', label: 'Miếng miếng pizza ngoài sân', shape: 'triangle', minLevel: 1 },
  { id: 'o224', label: 'Nón lá', shape: 'triangle', minLevel: 2 },
  { id: 'o225', label: 'Tấm nón lá trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o226', label: 'Miếng nón lá ngoài sân', shape: 'triangle', minLevel: 2 },
  { id: 'o227', label: 'Cái ê-tô', shape: 'triangle', minLevel: 1 },
  { id: 'o228', label: 'Tấm cái ê-tô trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o229', label: 'Miếng cái ê-tô ngoài sân', shape: 'triangle', minLevel: 1 },
  { id: 'o230', label: 'Kim tự tháp mini', shape: 'triangle', minLevel: 2 },
  { id: 'o231', label: 'Tấm kim tự tháp mini trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o232', label: 'Miếng kim tự tháp mini ngoài sân', shape: 'triangle', minLevel: 2 },
  { id: 'o233', label: 'Dấu hiệu cảnh báo', shape: 'triangle', minLevel: 1 },
  { id: 'o234', label: 'Tấm dấu hiệu cảnh báo trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o235', label: 'Miếng dấu hiệu cảnh báo ngoài sân', shape: 'triangle', minLevel: 1 },
  { id: 'o236', label: 'Miếng sandwich tam giác', shape: 'triangle', minLevel: 2 },
  { id: 'o237', label: 'Tấm miếng sandwich tam giác trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o238', label: 'Miếng miếng sandwich tam giác ngoài sân', shape: 'triangle', minLevel: 2 },
  { id: 'o239', label: 'Cánh diều', shape: 'triangle', minLevel: 1 },
  { id: 'o240', label: 'Tấm cánh diều trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o241', label: 'Miếng cánh diều ngoài sân', shape: 'triangle', minLevel: 1 },
  { id: 'o242', label: 'Đinh ba trang trí', shape: 'triangle', minLevel: 2 },
  { id: 'o243', label: 'Tấm đinh ba trang trí trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o244', label: 'Miếng đinh ba trang trí ngoài sân', shape: 'triangle', minLevel: 2 },
  { id: 'o245', label: 'Miếng bánh sandwich', shape: 'triangle', minLevel: 1 },
  { id: 'o246', label: 'Tấm miếng bánh sandwich trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o247', label: 'Miếng miếng bánh sandwich ngoài sân', shape: 'triangle', minLevel: 1 },
  { id: 'o248', label: 'Núi nhọn', shape: 'triangle', minLevel: 2 },
  { id: 'o249', label: 'Tấm núi nhọn trên bàn', shape: 'triangle', minLevel: 3 },
  { id: 'o250', label: 'Miếng núi nhọn ngoài sân', shape: 'triangle', minLevel: 2 },
];
