import type { ObjectItem } from './objectBank';
/** Đồ vật bổ sung — nhãn tự nhiên, shape theo tên đồ vật. */
export const OBJECT_SUPPLEMENT: ObjectItem[] = [
  { id: 'o101', label: 'Xúc xắc', shape: 'square', minLevel: 1 },
  { id: 'o102', label: 'Xúc xắc', shape: 'square', minLevel: 3 },
  { id: 'o103', label: 'Xúc xắc', shape: 'square', minLevel: 1 },
  { id: 'o104', label: 'Phô mai', shape: 'square', minLevel: 2 },
  { id: 'o105', label: 'Phô mai', shape: 'square', minLevel: 3 },
  { id: 'o106', label: 'Phô mai', shape: 'square', minLevel: 2 },
  { id: 'o107', label: 'Gương', shape: 'rect', minLevel: 1 },
  { id: 'o108', label: 'Gương', shape: 'rect', minLevel: 3 },
  { id: 'o109', label: 'Gương', shape: 'rect', minLevel: 1 },
  { id: 'o110', label: 'Khay sushi', shape: 'rect', minLevel: 2 },
  { id: 'o111', label: 'Khay sushi', shape: 'rect', minLevel: 3 },
  { id: 'o112', label: 'Khay sushi', shape: 'rect', minLevel: 2 },
  { id: 'o113', label: 'Bánh brownie', shape: 'rect', minLevel: 1 },
  { id: 'o114', label: 'Bánh brownie', shape: 'rect', minLevel: 3 },
  { id: 'o115', label: 'Bánh brownie', shape: 'rect', minLevel: 1 },
  { id: 'o116', label: 'Kính', shape: 'rect', minLevel: 2 },
  { id: 'o117', label: 'Kính', shape: 'rect', minLevel: 3 },
  { id: 'o118', label: 'Kính', shape: 'rect', minLevel: 2 },
  { id: 'o119', label: 'Đá lát', shape: 'rect', minLevel: 1 },
  { id: 'o120', label: 'Đá lát', shape: 'rect', minLevel: 3 },
  { id: 'o121', label: 'Đá lát', shape: 'rect', minLevel: 1 },
  { id: 'o122', label: 'Bánh quy', shape: 'circle', minLevel: 2 },
  { id: 'o123', label: 'Bánh quy', shape: 'circle', minLevel: 3 },
  { id: 'o124', label: 'Bánh quy', shape: 'circle', minLevel: 2 },
  { id: 'o125', label: 'Thảm họa tiết', shape: 'rect', minLevel: 1 },
  { id: 'o126', label: 'Thảm họa tiết', shape: 'rect', minLevel: 3 },
  { id: 'o127', label: 'Thảm họa tiết', shape: 'rect', minLevel: 1 },
  { id: 'o128', label: 'Sữa', shape: 'rect', minLevel: 2 },
  { id: 'o129', label: 'Sữa', shape: 'rect', minLevel: 3 },
  { id: 'o130', label: 'Sữa', shape: 'rect', minLevel: 2 },
  { id: 'o131', label: 'Đậu phụ', shape: 'square', minLevel: 1 },
  { id: 'o132', label: 'Đậu phụ', shape: 'square', minLevel: 3 },
  { id: 'o133', label: 'Đậu phụ', shape: 'square', minLevel: 1 },
  { id: 'o134', label: 'Miếng decal', shape: 'parallelogram', minLevel: 2 },
  { id: 'o135', label: 'Miếng decal', shape: 'parallelogram', minLevel: 3 },
  { id: 'o136', label: 'Miếng decal', shape: 'parallelogram', minLevel: 2 },
  { id: 'o137', label: 'Xếp hình', shape: 'rect', minLevel: 1 },
  { id: 'o138', label: 'Xếp hình', shape: 'rect', minLevel: 3 },
  { id: 'o139', label: 'Xếp hình', shape: 'rect', minLevel: 1 },
  { id: 'o140', label: 'Kẹo dẻo', shape: 'rect', minLevel: 2 },
  { id: 'o141', label: 'Kẹo dẻo', shape: 'rect', minLevel: 3 },
  { id: 'o142', label: 'Kẹo dẻo', shape: 'rect', minLevel: 2 },
  { id: 'o143', label: 'Bìa màu', shape: 'rect', minLevel: 1 },
  { id: 'o144', label: 'Bìa màu', shape: 'rect', minLevel: 3 },
  { id: 'o145', label: 'Bìa màu', shape: 'rect', minLevel: 1 },
  { id: 'o146', label: 'Gạch mosaic', shape: 'square', minLevel: 2 },
  { id: 'o147', label: 'Gạch mosaic', shape: 'square', minLevel: 3 },
  { id: 'o148', label: 'Gạch mosaic', shape: 'square', minLevel: 2 },
  { id: 'o149', label: 'Bánh sandwich', shape: 'rect', minLevel: 1 },
  { id: 'o150', label: 'Bánh sandwich', shape: 'rect', minLevel: 3 },
  { id: 'o151', label: 'Bánh sandwich', shape: 'rect', minLevel: 1 },
  { id: 'o152', label: 'Lót bàn', shape: 'rect', minLevel: 2 },
  { id: 'o153', label: 'Lót bàn', shape: 'rect', minLevel: 3 },
  { id: 'o154', label: 'Lót bàn', shape: 'rect', minLevel: 2 },
  { id: 'o155', label: 'Khung ảnh', shape: 'square', minLevel: 1 },
  { id: 'o156', label: 'Khung ảnh', shape: 'square', minLevel: 3 },
  { id: 'o157', label: 'Khung ảnh', shape: 'square', minLevel: 1 },
  { id: 'o158', label: 'Bánh flan', shape: 'square', minLevel: 2 },
  { id: 'o159', label: 'Bánh flan', shape: 'square', minLevel: 3 },
  { id: 'o160', label: 'Bánh flan', shape: 'square', minLevel: 2 },
  { id: 'o161', label: 'Thẻ tên', shape: 'rect', minLevel: 1 },
  { id: 'o162', label: 'Thẻ tên', shape: 'rect', minLevel: 3 },
  { id: 'o163', label: 'Thẻ tên', shape: 'rect', minLevel: 1 },
  { id: 'o164', label: 'Sách', shape: 'rect', minLevel: 2 },
  { id: 'o165', label: 'Sách', shape: 'rect', minLevel: 3 },
  { id: 'o166', label: 'Sách', shape: 'rect', minLevel: 2 },
  { id: 'o167', label: 'Thước kẻ', shape: 'rect', minLevel: 1 },
  { id: 'o168', label: 'Thước kẻ', shape: 'rect', minLevel: 3 },
  { id: 'o169', label: 'Thước kẻ', shape: 'rect', minLevel: 1 },
  { id: 'o170', label: 'Bút', shape: 'rect', minLevel: 2 },
  { id: 'o171', label: 'Bút', shape: 'rect', minLevel: 3 },
  { id: 'o172', label: 'Bút', shape: 'rect', minLevel: 2 },
  { id: 'o173', label: 'Ván gỗ', shape: 'rect', minLevel: 1 },
  { id: 'o174', label: 'Ván gỗ', shape: 'rect', minLevel: 3 },
  { id: 'o175', label: 'Ván gỗ', shape: 'rect', minLevel: 1 },
  { id: 'o176', label: 'Gạch ống', shape: 'rect', minLevel: 2 },
  { id: 'o177', label: 'Gạch ống', shape: 'rect', minLevel: 3 },
  { id: 'o178', label: 'Gạch ống', shape: 'rect', minLevel: 2 },
  { id: 'o179', label: 'Cửa phòng', shape: 'rect', minLevel: 1 },
  { id: 'o180', label: 'Cửa phòng', shape: 'rect', minLevel: 3 },
  { id: 'o181', label: 'Cửa phòng', shape: 'rect', minLevel: 1 },
  { id: 'o182', label: 'Biển báo', shape: 'rect', minLevel: 2 },
  { id: 'o183', label: 'Biển báo', shape: 'rect', minLevel: 3 },
  { id: 'o184', label: 'Biển báo', shape: 'rect', minLevel: 2 },
  { id: 'o185', label: 'Khay đựng bút', shape: 'rect', minLevel: 1 },
  { id: 'o186', label: 'Khay đựng bút', shape: 'rect', minLevel: 3 },
  { id: 'o187', label: 'Khay đựng bút', shape: 'rect', minLevel: 1 },
  { id: 'o188', label: 'Socola', shape: 'rect', minLevel: 2 },
  { id: 'o189', label: 'Socola', shape: 'rect', minLevel: 3 },
  { id: 'o190', label: 'Socola', shape: 'rect', minLevel: 2 },
  { id: 'o191', label: 'Giấy a4', shape: 'rect', minLevel: 1 },
  { id: 'o192', label: 'Giấy a4', shape: 'rect', minLevel: 3 },
  { id: 'o193', label: 'Giấy a4', shape: 'rect', minLevel: 1 },
  { id: 'o194', label: 'Bánh mì', shape: 'triangle', minLevel: 2 },
  { id: 'o195', label: 'Bánh mì', shape: 'triangle', minLevel: 3 },
  { id: 'o196', label: 'Bánh mì', shape: 'triangle', minLevel: 2 },
  { id: 'o197', label: 'Ghi nhớ', shape: 'rect', minLevel: 1 },
  { id: 'o198', label: 'Ghi nhớ', shape: 'rect', minLevel: 3 },
  { id: 'o199', label: 'Ghi nhớ', shape: 'rect', minLevel: 1 },
  { id: 'o200', label: 'Diêm', shape: 'rect', minLevel: 2 },
  { id: 'o201', label: 'Diêm', shape: 'rect', minLevel: 3 },
  { id: 'o202', label: 'Diêm', shape: 'rect', minLevel: 2 },
  { id: 'o203', label: 'Học', shape: 'rect', minLevel: 1 },
  { id: 'o204', label: 'Học', shape: 'rect', minLevel: 3 },
  { id: 'o205', label: 'Học', shape: 'rect', minLevel: 1 },
  { id: 'o206', label: 'Cuộn băng dính', shape: 'parallelogram', minLevel: 2 },
  { id: 'o207', label: 'Cuộn băng dính', shape: 'parallelogram', minLevel: 3 },
  { id: 'o208', label: 'Cuộn băng dính', shape: 'parallelogram', minLevel: 2 },
  { id: 'o209', label: 'Sữa hộp', shape: 'rect', minLevel: 1 },
  { id: 'o210', label: 'Sữa hộp', shape: 'rect', minLevel: 3 },
  { id: 'o211', label: 'Sữa hộp', shape: 'rect', minLevel: 1 },
  { id: 'o212', label: 'Menu', shape: 'rect', minLevel: 2 },
  { id: 'o213', label: 'Menu', shape: 'rect', minLevel: 3 },
  { id: 'o214', label: 'Menu', shape: 'rect', minLevel: 2 },
  { id: 'o215', label: 'Tay vịn ghế', shape: 'rect', minLevel: 1 },
  { id: 'o216', label: 'Tay vịn ghế', shape: 'rect', minLevel: 3 },
  { id: 'o217', label: 'Tay vịn ghế', shape: 'rect', minLevel: 1 },
  { id: 'o218', label: 'Thân bút chì', shape: 'rect', minLevel: 2 },
  { id: 'o219', label: 'Thân bút chì', shape: 'rect', minLevel: 3 },
  { id: 'o220', label: 'Thân bút chì', shape: 'rect', minLevel: 2 },
  { id: 'o221', label: 'Miếng pizza', shape: 'triangle', minLevel: 1 },
  { id: 'o222', label: 'Miếng pizza', shape: 'triangle', minLevel: 3 },
  { id: 'o223', label: 'Miếng pizza', shape: 'triangle', minLevel: 1 },
  { id: 'o224', label: 'Nón lá', shape: 'triangle', minLevel: 2 },
  { id: 'o225', label: 'Nón lá', shape: 'triangle', minLevel: 3 },
  { id: 'o226', label: 'Nón lá', shape: 'triangle', minLevel: 2 },
  { id: 'o227', label: 'Cái ê-tô', shape: 'triangle', minLevel: 1 },
  { id: 'o228', label: 'Cái ê-tô', shape: 'triangle', minLevel: 3 },
  { id: 'o229', label: 'Cái ê-tô', shape: 'triangle', minLevel: 1 },
  { id: 'o230', label: 'Kim tự tháp', shape: 'triangle', minLevel: 2 },
  { id: 'o231', label: 'Kim tự tháp', shape: 'triangle', minLevel: 3 },
  { id: 'o232', label: 'Kim tự tháp', shape: 'triangle', minLevel: 2 },
  { id: 'o233', label: 'Dấu hiệu cảnh báo', shape: 'triangle', minLevel: 1 },
  { id: 'o234', label: 'Dấu hiệu cảnh báo', shape: 'triangle', minLevel: 3 },
  { id: 'o235', label: 'Dấu hiệu cảnh báo', shape: 'triangle', minLevel: 1 },
  { id: 'o236', label: 'Bánh sandwich', shape: 'rect', minLevel: 2 },
  { id: 'o237', label: 'Bánh sandwich', shape: 'rect', minLevel: 3 },
  { id: 'o238', label: 'Bánh sandwich', shape: 'rect', minLevel: 2 },
  { id: 'o239', label: 'Diều', shape: 'triangle', minLevel: 1 },
  { id: 'o240', label: 'Diều', shape: 'triangle', minLevel: 3 },
  { id: 'o241', label: 'Diều', shape: 'triangle', minLevel: 1 },
  { id: 'o242', label: 'Đinh ba trang trí', shape: 'rect', minLevel: 2 },
  { id: 'o243', label: 'Đinh ba trang trí', shape: 'rect', minLevel: 3 },
  { id: 'o244', label: 'Đinh ba trang trí', shape: 'rect', minLevel: 2 },
  { id: 'o245', label: 'Bánh sandwich', shape: 'rect', minLevel: 1 },
  { id: 'o246', label: 'Bánh sandwich', shape: 'rect', minLevel: 3 },
  { id: 'o247', label: 'Bánh sandwich', shape: 'rect', minLevel: 1 },
  { id: 'o248', label: 'Núi nhọn', shape: 'triangle', minLevel: 2 },
  { id: 'o249', label: 'Núi nhọn', shape: 'triangle', minLevel: 3 },
  { id: 'o250', label: 'Núi nhọn', shape: 'triangle', minLevel: 2 },
];
