import type { ObjectItem } from './objectBank';

/** Bổ sung o329–o538 — 1 câu / 1 minh họa (builder o101–o310), cân bằng dạng hình. */
export const OBJECT_SUPPLEMENT_WAVE3: ObjectItem[] = [
  { id: 'o329', label: 'Đồng hồ bàn học', shape: 'square', minLevel: 1 },
  { id: 'o330', label: 'Mặt trăng đêm', shape: 'square', minLevel: 1 },
  { id: 'o331', label: 'Nắp nồi cơm', shape: 'square', minLevel: 1 },
  { id: 'o332', label: 'Bánh donut', shape: 'square', minLevel: 1 },
  { id: 'o333', label: 'Đĩa sứ trắng', shape: 'square', minLevel: 1 },
  { id: 'o334', label: 'Quả bóng đá', shape: 'square', minLevel: 1 },
  { id: 'o335', label: 'Nút áo tròn', shape: 'square', minLevel: 2 },
  { id: 'o336', label: 'Đồng xu lưu niệm', shape: 'square', minLevel: 2 },
  { id: 'o337', label: 'Mặt đồng hồ treo', shape: 'square', minLevel: 1 },
  { id: 'o338', label: 'Bánh bao nhân', shape: 'square', minLevel: 2 },
  { id: 'o339', label: 'Miếng cam', shape: 'square', minLevel: 1 },
  { id: 'o340', label: 'Đĩa nhựa màu', shape: 'square', minLevel: 2 },
  { id: 'o341', label: 'Huy hiệu tròn', shape: 'square', minLevel: 2 },
  { id: 'o342', label: 'Nút bấm điện', shape: 'square', minLevel: 2 },
  { id: 'o343', label: 'Bánh quy tròn', shape: 'square', minLevel: 1 },
  { id: 'o344', label: 'Mặt trời vẽ', shape: 'rect', minLevel: 1 },
  { id: 'o345', label: 'Đĩa gốm men', shape: 'rect', minLevel: 2 },
  { id: 'o346', label: 'Quả táo', shape: 'rect', minLevel: 1 },
  { id: 'o347', label: 'Đồng hồ báo thức', shape: 'triangle', minLevel: 2 },
  { id: 'o348', label: 'Miếng bánh bông lan', shape: 'triangle', minLevel: 2 },
  { id: 'o349', label: 'Nút vặn cửa', shape: 'triangle', minLevel: 2 },
  { id: 'o350', label: 'Đĩa kẹo Tết', shape: 'triangle', minLevel: 1 },
  { id: 'o351', label: 'Huy chương thi đua', shape: 'triangle', minLevel: 2 },
  { id: 'o352', label: 'Quả cam ngọt', shape: 'parallelogram', minLevel: 1 },
  { id: 'o353', label: 'Đồng hồ mini', shape: 'parallelogram', minLevel: 2 },
  { id: 'o354', label: 'Bánh bao chay', shape: 'parallelogram', minLevel: 2 },
  { id: 'o355', label: 'Mặt đồng hồ đỏ', shape: 'parallelogram', minLevel: 1 },
  { id: 'o356', label: 'Đĩa in hoa', shape: 'parallelogram', minLevel: 2 },
  { id: 'o357', label: 'Nút ghim văn phòng', shape: 'parallelogram', minLevel: 2 },
  { id: 'o358', label: 'Quả chanh vàng', shape: 'parallelogram', minLevel: 1 },
  { id: 'o359', label: 'Đồng xu đồng', shape: 'parallelogram', minLevel: 2 },
  { id: 'o360', label: 'Bánh quy socola', shape: 'parallelogram', minLevel: 2 },
  { id: 'o361', label: 'Mặt trăng khuyết', shape: 'parallelogram', minLevel: 1 },
  { id: 'o362', label: 'Đĩa sứ xanh', shape: 'parallelogram', minLevel: 2 },
  { id: 'o363', label: 'Huy hiệu sao', shape: 'parallelogram', minLevel: 2 },
  { id: 'o364', label: 'Quả nho tím', shape: 'parallelogram', minLevel: 2 },
  { id: 'o365', label: 'Đồng hồ kim giờ', shape: 'parallelogram', minLevel: 2 },
  { id: 'o366', label: 'Bánh trung thu tròn', shape: 'parallelogram', minLevel: 1 },
  { id: 'o367', label: 'Nút áo xanh', shape: 'parallelogram', minLevel: 2 },
  { id: 'o368', label: 'Đĩa kẹo dẻo', shape: 'parallelogram', minLevel: 2 },
  { id: 'o369', label: 'Miếng bánh kem tròn', shape: 'parallelogram', minLevel: 2 },
  { id: 'o370', label: 'Quả ổi xanh', shape: 'parallelogram', minLevel: 2 },
  { id: 'o371', label: 'Đồng hồ học sinh', shape: 'parallelogram', minLevel: 2 },
  { id: 'o372', label: 'Bánh quy bơ', shape: 'parallelogram', minLevel: 2 },
  { id: 'o373', label: 'Mặt trời buổi sáng', shape: 'parallelogram', minLevel: 1 },
  { id: 'o374', label: 'Đĩa trái cây', shape: 'parallelogram', minLevel: 2 },
  { id: 'o375', label: 'Viên ngọc trang sức', shape: 'parallelogram', minLevel: 2 },
  { id: 'o376', label: 'Khung thoi dệt', shape: 'parallelogram', minLevel: 2 },
  { id: 'o377', label: 'Gạch hoa lục giác', shape: 'parallelogram', minLevel: 2 },
  { id: 'o378', label: 'Diều giấy nhỏ', shape: 'parallelogram', minLevel: 1 },
  { id: 'o379', label: 'Mảnh kính màu', shape: 'parallelogram', minLevel: 3 },
  { id: 'o380', label: 'Huy hiệu kim cương', shape: 'parallelogram', minLevel: 2 },
  { id: 'o381', label: 'Gạch men xanh', shape: 'parallelogram', minLevel: 2 },
  { id: 'o382', label: 'Viên đá quý', shape: 'parallelogram', minLevel: 3 },
  { id: 'o383', label: 'Khung ảnh nghiêng', shape: 'parallelogram', minLevel: 2 },
  { id: 'o384', label: 'Gạch lát hình thoi', shape: 'parallelogram', minLevel: 2 },
  { id: 'o385', label: 'Cánh diều giấy', shape: 'parallelogram', minLevel: 1 },
  { id: 'o386', label: 'Mảnh gương vỡ', shape: 'parallelogram', minLevel: 3 },
  { id: 'o387', label: 'Huy hiệu lục giác', shape: 'parallelogram', minLevel: 2 },
  { id: 'o388', label: 'Gạch mosaic', shape: 'parallelogram', minLevel: 2 },
  { id: 'o389', label: 'Viên pha lê', shape: 'parallelogram', minLevel: 3 },
  { id: 'o390', label: 'Khung cửa kính', shape: 'parallelogram', minLevel: 2 },
  { id: 'o391', label: 'Gạch sân thể thao', shape: 'parallelogram', minLevel: 2 },
  { id: 'o392', label: 'Diều giấy nhỏ', shape: 'parallelogram', minLevel: 1 },
  { id: 'o393', label: 'Mảnh kính mờ', shape: 'parallelogram', minLevel: 3 },
  { id: 'o394', label: 'Huy hiệu vàng', shape: 'parallelogram', minLevel: 2 },
  { id: 'o395', label: 'Gạch men đỏ', shape: 'parallelogram', minLevel: 2 },
  { id: 'o396', label: 'Viên đá cẩn', shape: 'parallelogram', minLevel: 3 },
  { id: 'o397', label: 'Khung tranh nghiêng', shape: 'rhombus', minLevel: 2 },
  { id: 'o398', label: 'Gạch vỉa hè', shape: 'rhombus', minLevel: 2 },
  { id: 'o399', label: 'Cánh diều rực', shape: 'rhombus', minLevel: 1 },
  { id: 'o400', label: 'Mảnh gương tròn', shape: 'rhombus', minLevel: 3 },
  { id: 'o401', label: 'Huy hiệu bạc', shape: 'rhombus', minLevel: 2 },
  { id: 'o402', label: 'Gạch hoa vàng', shape: 'rhombus', minLevel: 2 },
  { id: 'o403', label: 'Viên ngọc xanh', shape: 'rhombus', minLevel: 3 },
  { id: 'o404', label: 'Khung kính cửa', shape: 'rhombus', minLevel: 2 },
  { id: 'o405', label: 'Gạch lát sân', shape: 'rhombus', minLevel: 2 },
  { id: 'o406', label: 'Diều con nhỏ', shape: 'rhombus', minLevel: 1 },
  { id: 'o407', label: 'Mảnh kính xanh', shape: 'rhombus', minLevel: 3 },
  { id: 'o408', label: 'Huy hiệu đỏ', shape: 'rhombus', minLevel: 2 },
  { id: 'o409', label: 'Gạch men trắng', shape: 'rhombus', minLevel: 2 },
  { id: 'o410', label: 'Viên đá lấp lánh', shape: 'rhombus', minLevel: 3 },
  { id: 'o411', label: 'Khung ảnh kính', shape: 'rhombus', minLevel: 2 },
  { id: 'o412', label: 'Gạch hoa tím', shape: 'rhombus', minLevel: 2 },
  { id: 'o413', label: 'Cánh diều xanh', shape: 'rhombus', minLevel: 1 },
  { id: 'o414', label: 'Mảnh gương nhỏ', shape: 'rhombus', minLevel: 3 },
  { id: 'o415', label: 'Huy hiệu xanh', shape: 'rhombus', minLevel: 2 },
  { id: 'o416', label: 'Gạch mosaic vàng', shape: 'rhombus', minLevel: 2 },
  { id: 'o417', label: 'Viên pha lê hồng', shape: 'rhombus', minLevel: 3 },
  { id: 'o418', label: 'Khung cửa sổ kính', shape: 'rhombus', minLevel: 2 },
  { id: 'o419', label: 'Gạch sân xanh', shape: 'rhombus', minLevel: 2 },
  { id: 'o420', label: 'Diều giấy xanh', shape: 'rhombus', minLevel: 1 },
  { id: 'o421', label: 'Mảnh kính vàng', shape: 'rhombus', minLevel: 3 },
  { id: 'o422', label: 'Huy hiệu tím', shape: 'rhombus', minLevel: 2 },
  { id: 'o423', label: 'Gạch men hồng', shape: 'rhombus', minLevel: 2 },
  { id: 'o424', label: 'Viên ngọc đỏ', shape: 'rhombus', minLevel: 3 },
  { id: 'o425', label: 'Khung tranh kính', shape: 'rhombus', minLevel: 2 },
  { id: 'o426', label: 'Thanh xiên cửa', shape: 'rhombus', minLevel: 2 },
  { id: 'o427', label: 'Mảnh gỗ nghiêng', shape: 'rhombus', minLevel: 2 },
  { id: 'o428', label: 'Nhãn vở xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o429', label: 'Thanh sắt xiên', shape: 'rhombus', minLevel: 3 },
  { id: 'o430', label: 'Mảnh bìa xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o431', label: 'Thanh gỗ pallet', shape: 'rhombus', minLevel: 2 },
  { id: 'o432', label: 'Nhãn dán xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o433', label: 'Thanh nhôm xiên', shape: 'rhombus', minLevel: 3 },
  { id: 'o434', label: 'Mảnh ván xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o435', label: 'Thanh tre xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o436', label: 'Nhãn sách xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o437', label: 'Thanh đồng xiên', shape: 'rhombus', minLevel: 3 },
  { id: 'o438', label: 'Mảnh nhựa xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o439', label: 'Thanh gỗ nghiêng', shape: 'rhombus', minLevel: 2 },
  { id: 'o440', label: 'Nhãn hộp xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o441', label: 'Thanh sắt nhỏ', shape: 'rhombus', minLevel: 3 },
  { id: 'o442', label: 'Mảnh bìa cứng xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o443', label: 'Thanh ván xiên', shape: 'rhombus', minLevel: 2 },
  { id: 'o444', label: 'Nhãn vở màu', shape: 'rhombus', minLevel: 2 },
  { id: 'o445', label: 'Thanh kẽm xiên', shape: 'rhombus', minLevel: 3 },
  { id: 'o446', label: 'Mảnh gỗ nhỏ', shape: 'rhombus', minLevel: 2 },
  { id: 'o447', label: 'Thanh tre nhỏ', shape: 'rhombus', minLevel: 2 },
  { id: 'o448', label: 'Nhãn dán màu', shape: 'trapezoid', minLevel: 2 },
  { id: 'o449', label: 'Thanh nhựa xiên', shape: 'trapezoid', minLevel: 3 },
  { id: 'o450', label: 'Mảnh ván nhỏ', shape: 'trapezoid', minLevel: 2 },
  { id: 'o451', label: 'Thanh gỗ dài', shape: 'trapezoid', minLevel: 2 },
  { id: 'o452', label: 'Nhãn sách màu', shape: 'trapezoid', minLevel: 2 },
  { id: 'o453', label: 'Thanh sắt dài', shape: 'trapezoid', minLevel: 3 },
  { id: 'o454', label: 'Mảnh bìa xiên nhỏ', shape: 'trapezoid', minLevel: 2 },
  { id: 'o455', label: 'Thanh pallet xiên', shape: 'trapezoid', minLevel: 2 },
  { id: 'o456', label: 'Nhãn vở học sinh', shape: 'trapezoid', minLevel: 2 },
  { id: 'o457', label: 'Thanh đồng nhỏ', shape: 'trapezoid', minLevel: 3 },
  { id: 'o458', label: 'Mảnh nhựa nghiêng', shape: 'trapezoid', minLevel: 2 },
  { id: 'o459', label: 'Thanh gỗ học sinh', shape: 'trapezoid', minLevel: 2 },
  { id: 'o460', label: 'Nhãn hộp màu', shape: 'trapezoid', minLevel: 2 },
  { id: 'o461', label: 'Thanh kẽm nhỏ', shape: 'trapezoid', minLevel: 3 },
  { id: 'o462', label: 'Mảnh ván nghiêng', shape: 'trapezoid', minLevel: 2 },
  { id: 'o463', label: 'Thanh tre dài', shape: 'trapezoid', minLevel: 2 },
  { id: 'o464', label: 'Nhãn dán học sinh', shape: 'trapezoid', minLevel: 2 },
  { id: 'o465', label: 'Thanh nhôm nhỏ', shape: 'trapezoid', minLevel: 3 },
  { id: 'o466', label: 'Mảnh gỗ học sinh', shape: 'trapezoid', minLevel: 2 },
  { id: 'o467', label: 'Thanh xiên nhỏ', shape: 'trapezoid', minLevel: 2 },
  { id: 'o468', label: 'Nhãn vở xiên nhỏ', shape: 'trapezoid', minLevel: 2 },
  { id: 'o469', label: 'Thanh sắt học sinh', shape: 'trapezoid', minLevel: 3 },
  { id: 'o470', label: 'Mảnh bìa học sinh', shape: 'trapezoid', minLevel: 2 },
  { id: 'o471', label: 'Mái nhà ngói đỏ', shape: 'trapezoid', minLevel: 1 },
  { id: 'o472', label: 'Cái xẻng nhựa', shape: 'trapezoid', minLevel: 1 },
  { id: 'o473', label: 'Mái hiên nhà', shape: 'trapezoid', minLevel: 1 },
  { id: 'o474', label: 'Chậu hoa lớn', shape: 'trapezoid', minLevel: 2 },
  { id: 'o475', label: 'Mái chùa nhỏ', shape: 'trapezoid', minLevel: 1 },
  { id: 'o476', label: 'Cái cốc loe', shape: 'trapezoid', minLevel: 2 },
  { id: 'o477', label: 'Mái lều trại', shape: 'trapezoid', minLevel: 2 },
  { id: 'o478', label: 'Thùng đựng đồ', shape: 'trapezoid', minLevel: 2 },
  { id: 'o479', label: 'Mái nhà xanh', shape: 'trapezoid', minLevel: 1 },
  { id: 'o480', label: 'Cái ly loe', shape: 'trapezoid', minLevel: 2 },
  { id: 'o481', label: 'Mái vòm nhỏ', shape: 'trapezoid', minLevel: 2 },
  { id: 'o482', label: 'Chậu cây cảnh', shape: 'trapezoid', minLevel: 2 },
  { id: 'o483', label: 'Mái hiên xanh', shape: 'trapezoid', minLevel: 1 },
  { id: 'o484', label: 'Cái bát loe', shape: 'trapezoid', minLevel: 2 },
  { id: 'o485', label: 'Mái lều xanh', shape: 'trapezoid', minLevel: 2 },
  { id: 'o486', label: 'Thùng rác nhựa', shape: 'trapezoid', minLevel: 2 },
  { id: 'o487', label: 'Mái ngói vàng', shape: 'trapezoid', minLevel: 1 },
  { id: 'o488', label: 'Cái cốc nhựa', shape: 'trapezoid', minLevel: 2 },
  { id: 'o489', label: 'Mái chắn nắng', shape: 'trapezoid', minLevel: 2 },
  { id: 'o490', label: 'Chậu hoa nhỏ', shape: 'trapezoid', minLevel: 2 },
  { id: 'o491', label: 'Mái nhà đỏ', shape: 'trapezoid', minLevel: 1 },
  { id: 'o492', label: 'Cái ly nhựa', shape: 'trapezoid', minLevel: 2 },
  { id: 'o493', label: 'Mái vòm đỏ', shape: 'circle', minLevel: 2 },
  { id: 'o494', label: 'Thùng đựng sách', shape: 'circle', minLevel: 2 },
  { id: 'o495', label: 'Mái hiên đỏ', shape: 'circle', minLevel: 1 },
  { id: 'o496', label: 'Cái bát nhựa', shape: 'circle', minLevel: 2 },
  { id: 'o497', label: 'Mái lều đỏ', shape: 'circle', minLevel: 2 },
  { id: 'o498', label: 'Chậu cây nhỏ', shape: 'circle', minLevel: 2 },
  { id: 'o499', label: 'Mái ngói xanh', shape: 'circle', minLevel: 1 },
  { id: 'o500', label: 'Cái xẻng nhỏ', shape: 'circle', minLevel: 2 },
  { id: 'o501', label: 'Mái chùa vàng', shape: 'circle', minLevel: 1 },
  { id: 'o502', label: 'Thùng đựng đồ chơi', shape: 'circle', minLevel: 2 },
  { id: 'o503', label: 'Mái nhà vàng', shape: 'circle', minLevel: 1 },
  { id: 'o504', label: 'Cái cốc loe xanh', shape: 'circle', minLevel: 2 },
  { id: 'o505', label: 'Mái vòm xanh', shape: 'circle', minLevel: 2 },
  { id: 'o506', label: 'Chậu hoa xanh', shape: 'circle', minLevel: 2 },
  { id: 'o507', label: 'Mái hiên vàng', shape: 'circle', minLevel: 1 },
  { id: 'o508', label: 'Cái ly loe đỏ', shape: 'circle', minLevel: 2 },
  { id: 'o509', label: 'Mái lều vàng', shape: 'circle', minLevel: 2 },
  { id: 'o510', label: 'Thùng rác xanh', shape: 'circle', minLevel: 2 },
  { id: 'o511', label: 'Mái ngói đỏ nhỏ', shape: 'circle', minLevel: 1 },
  { id: 'o512', label: 'Cái bát loe vàng', shape: 'circle', minLevel: 2 },
  { id: 'o513', label: 'Mái chắn nắng xanh', shape: 'circle', minLevel: 2 },
  { id: 'o514', label: 'Chậu cây đỏ', shape: 'circle', minLevel: 2 },
  { id: 'o515', label: 'Mái vòm vàng', shape: 'circle', minLevel: 2 },
  { id: 'o516', label: 'Miếng bánh mì nướng', shape: 'circle', minLevel: 1 },
  { id: 'o517', label: 'Nón lá tre', shape: 'circle', minLevel: 1 },
  { id: 'o518', label: 'Cờ cắm lớp học', shape: 'circle', minLevel: 1 },
  { id: 'o519', label: 'Miếng pizza nhỏ', shape: 'circle', minLevel: 2 },
  { id: 'o520', label: 'Diều giấy nhiều màu', shape: 'circle', minLevel: 1 },
  { id: 'o521', label: 'Khăn gấp thổ cẩm', shape: 'circle', minLevel: 1 },
  { id: 'o522', label: 'Miếng bánh chưng', shape: 'circle', minLevel: 1 },
  { id: 'o523', label: 'Ô cờ vua', shape: 'circle', minLevel: 1 },
  { id: 'o524', label: 'Khung ảnh treo tường', shape: 'circle', minLevel: 2 },
  { id: 'o525', label: 'Miếng đậu phụ', shape: 'circle', minLevel: 2 },
  { id: 'o526', label: 'Gạch đỏ lát sân', shape: 'circle', minLevel: 1 },
  { id: 'o527', label: 'Khay nhựa đựng đồ', shape: 'circle', minLevel: 2 },
  { id: 'o528', label: 'Miếng bánh brownie', shape: 'circle', minLevel: 2 },
  { id: 'o529', label: 'Ô bàn cờ caro', shape: 'circle', minLevel: 1 },
  { id: 'o530', label: 'Khung tranh treo phòng', shape: 'circle', minLevel: 2 },
  { id: 'o531', label: 'Miếng phô mai', shape: 'circle', minLevel: 2 },
  { id: 'o532', label: 'Gạch lát sân trường', shape: 'circle', minLevel: 1 },
  { id: 'o533', label: 'Khay đựng đồ ăn', shape: 'circle', minLevel: 2 },
  { id: 'o534', label: 'Miếng bánh quy sữa', shape: 'circle', minLevel: 2 },
  { id: 'o535', label: 'Ô sổ ô ly', shape: 'circle', minLevel: 1 },
  { id: 'o536', label: 'Thước kẻ dài', shape: 'circle', minLevel: 1 },
  { id: 'o537', label: 'Hộp bút chì', shape: 'circle', minLevel: 1 },
  { id: 'o538', label: 'Quyển vở kẻ ngang', shape: 'circle', minLevel: 1 },
];
