import type { FracOpsMcqChallenge } from './challengeTypes';

export const FRAC_OPS_BANK_EXTRA: FracOpsMcqChallenge[] = [
  {
    prompt: '1/6 + 1/6 + 1/6 = ?',
    choices: ['1/2', '1/3', '3/18', '2/6'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-cong-cung-mau',
  },
  {
    prompt: '4/7 + 2/7 = ?',
    choices: ['6/7', '6/14', '2/7', '8/7'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-cong-cung-mau',
  },
  {
    prompt: '11/12 − 5/12 = ?',
    choices: ['6/12', '1/2', '5/12', '16/12'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-tru-cung-mau',
  },
  {
    prompt: '5/9 − 2/9 = ?',
    choices: ['3/9', '1/3', '7/9', '3/18'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-tru-cung-mau',
  },
  {
    prompt: '2/3 + 1/6 = ?',
    choices: ['3/9', '5/6', '1/2', '3/6'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-cong-khac-mau',
  },
  {
    prompt: '3/8 + 1/4 = ?',
    choices: ['4/12', '5/8', '1/2', '4/8'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-cong-khac-mau',
  },
  {
    prompt: 'Anh Nam dùng 1/3 + 2/5 lọ hóa chất. Tổng phần dùng?',
    choices: ['3/8', '11/15', '3/15', '2/8'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-cong-khac-mau',
  },
  {
    prompt: '7/10 − 2/5 = ?',
    choices: ['5/10', '3/10', '1/2', '9/10'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-tru-khac-mau',
  },
  {
    prompt: '4/5 − 1/2 = ?',
    choices: ['3/10', '3/5', '1/2', '7/10'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-tru-khac-mau',
  },
  {
    prompt: '1/2 × 2/3 = ?',
    choices: ['1/3', '2/5', '1/6', '3/4'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-nhan',
  },
  {
    prompt: '5/6 × 3/4 = ?',
    choices: ['8/10', '5/8', '15/24', '8/24'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-nhan',
  },
  {
    prompt: '1/4 của 36 quả táo là bao nhiêu quả?',
    choices: ['6', '8', '9', '12'],
    correctIndex: 2,
    sgkRef: 'toan-ptps-phan-so-cua-so',
  },
  {
    prompt: '3/5 của 45 học sinh là bao nhiêu em?',
    choices: ['9', '15', '27', '30'],
    correctIndex: 2,
    sgkRef: 'toan-ptps-phan-so-cua-so',
  },
  {
    prompt: '1/3 của 24 lít nước là bao nhiêu lít?',
    choices: ['6', '8', '12', '16'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-phan-so-cua-so',
  },
  {
    prompt: '3/4 : 1/6 = ? (mỗi cốc 1/6 bình)',
    choices: ['9/2', '3/24', '1/8', '4/6'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-chia',
  },
  {
    prompt: '2/3 : 4/5 = ?',
    choices: ['8/15', '5/6', '6/5', '10/12'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-chia',
  },
  {
    prompt: '1/5 : 1/10 = ?',
    choices: ['1/50', '2', '1/2', '10/5'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-chia',
  },
  {
    prompt: '8/11 + 2/11 = ?',
    choices: ['10/11', '10/22', '6/11', '1'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-cong-cung-mau',
  },
  {
    prompt: '9/10 − 3/10 = ?',
    choices: ['6/10', '3/5', '12/10', '6/20'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-tru-cung-mau',
  },
  {
    prompt: '1/2 + 1/8 = ?',
    choices: ['2/10', '5/8', '1/4', '3/8'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-cong-khac-mau',
  },
  {
    prompt: '3/4 − 1/6 = ?',
    choices: ['2/2', '7/12', '1/3', '5/12'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-tru-khac-mau',
  },
  {
    prompt: '2/7 × 7/2 = ?',
    choices: ['1', '14/9', '4/7', '7/4'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-nhan',
  },
  {
    prompt: '4/5 của 35 em là bao nhiêu em?',
    choices: ['7', '20', '28', '30'],
    correctIndex: 2,
    sgkRef: 'toan-ptps-phan-so-cua-so',
  },
  {
    prompt: '5/6 của 48 quả cam là bao nhiêu quả?',
    choices: ['30', '40', '42', '45'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-phan-so-cua-so',
  },
  {
    prompt: 'Đội sửa đường ngày 1: 2/9, ngày 2: 5/9. Tổng phần đường đã sửa?',
    choices: ['7/9', '7/18', '3/9', '1'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-cong-cung-mau',
  },
  {
    prompt: '7/8 − 2/8 = ? (phần bánh còn lại)',
    choices: ['5/8', '9/8', '1/4', '3/8'],
    correctIndex: 0,
    sgkRef: 'toan-ptps-tru-cung-mau',
  },
  {
    prompt: '3/5 × 2/3 = ?',
    choices: ['5/8', '2/5', '6/15', '1/2'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-nhan',
  },
  {
    prompt: '1/3 : 1/9 = ?',
    choices: ['1/27', '3', '1/3', '9'],
    correctIndex: 1,
    sgkRef: 'toan-ptps-chia',
  },
];
