import type { VocabPair } from './questions';
/** Tham chiếu 55 nguồn đề lớp 4 (2020-2021 to 2024-2025) — xem docs/content/EXAM_SOURCES_GRADE4.md — 85 cặp */
export const VOCAB_SUPPLEMENT_EXTRA: VocabPair[] = [
  { en: 'classmate', vi: 'bạn cùng lớp', emoji: '👧', level: 1 as const },
  { en: 'homework', vi: 'bài tập về nhà', emoji: '📝', level: 1 as const },
  { en: 'subject', vi: 'môn học', emoji: '📖', level: 1 as const },
  { en: 'pencil case', vi: 'hộp bút', emoji: '✏️', level: 1 as const },
  { en: 'ruler', vi: 'thước kẻ', emoji: '📏', level: 1 as const },
  { en: 'eraser', vi: 'cục tẩy', emoji: '🧽', level: 1 as const },
  { en: 'whiteboard', vi: 'bảng trắng', emoji: '⬜', level: 1 as const },
  { en: 'principal', vi: 'hiệu trưởng', emoji: '🏫', level: 1 as const },
  { en: 'uniform', vi: 'đồng phục', emoji: '👔', level: 1 as const },
  { en: 'cousin', vi: 'anh chị em họ', emoji: '👦', level: 1 as const },
  { en: 'grandparents', vi: 'ông bà', emoji: '👴', level: 1 as const },
  { en: 'nephew', vi: 'cháu trai', emoji: '👦', level: 1 as const },
  { en: 'buffalo', vi: 'con trâu', emoji: '🐃', level: 1 as const },
  { en: 'goat', vi: 'con dê', emoji: '🐐', level: 1 as const },
  { en: 'duck', vi: 'con vịt', emoji: '🦆', level: 1 as const },
  { en: 'peach', vi: 'quả đào', emoji: '🍑', level: 1 as const },
  { en: 'grape', vi: 'quả nho', emoji: '🍇', level: 1 as const },
  { en: 'mango', vi: 'quả xoài', emoji: '🥭', level: 1 as const },
  { en: 'carrot', vi: 'củ cà rốt', emoji: '🥕', level: 1 as const },
  { en: 'potato', vi: 'củ khoai tây', emoji: '🥔', level: 1 as const },
  { en: 'onion', vi: 'củ hành', emoji: '🧅', level: 1 as const },
  { en: 'doctor', vi: 'bác sĩ', emoji: '👨‍⚕️', level: 1 as const },
  { en: 'nurse', vi: 'y tá', emoji: '👩‍⚕️', level: 1 as const },
  { en: 'firefighter', vi: 'lính cứu hỏa', emoji: '🚒', level: 1 as const },
  { en: 'post office', vi: 'bưu điện', emoji: '📮', level: 1 as const },
  { en: 'supermarket', vi: 'siêu thị', emoji: '🛒', level: 1 as const },
  { en: 'pharmacy', vi: 'nhà thuốc', emoji: '💊', level: 1 as const },
  { en: 'desert', vi: 'sa mạc', emoji: '🏜️', level: 1 as const },
  { en: 'island', vi: 'hòn đảo', emoji: '🏝️', level: 1 as const },
  { en: 'waterfall', vi: 'thác nước', emoji: '💦', level: 1 as const },
  { en: 'spring', vi: 'mùa xuân', emoji: '🌸', level: 1 as const },
  { en: 'summer', vi: 'mùa hè', emoji: '☀️', level: 1 as const },
  { en: 'autumn', vi: 'mùa thu', emoji: '🍁', level: 1 as const },
  { en: 'exercise', vi: 'tập thể dục', emoji: '🤸', level: 1 as const },
  { en: 'healthy', vi: 'khỏe mạnh', emoji: '💪', level: 1 as const },
  { en: 'medicine', vi: 'thuốc', emoji: '💊', level: 1 as const },
  { en: 'plastic', vi: 'nhựa', emoji: '🧴', level: 1 as const },
  { en: 'recycle', vi: 'tái chế', emoji: '♻️', level: 1 as const },
  { en: 'pollution', vi: 'ô nhiễm', emoji: '🏭', level: 1 as const },
  { en: 'hobby', vi: 'sở thích', emoji: '🎯', level: 1 as const },
  { en: 'draw', vi: 'vẽ', emoji: '✏️', level: 2 as const },
  { en: 'sing', vi: 'hát', emoji: '🎤', level: 2 as const },
  { en: 'swim', vi: 'bơi', emoji: '🏊', level: 2 as const },
  { en: 'ticket', vi: 'vé', emoji: '🎫', level: 2 as const },
  { en: 'traffic', vi: 'giao thông', emoji: '🚦', level: 2 as const },
  { en: 'helmet', vi: 'mũ bảo hiểm', emoji: '⛑️', level: 2 as const },
  { en: 'brave', vi: 'dũng cảm', emoji: '🦁', level: 2 as const },
  { en: 'polite', vi: 'lịch sự', emoji: '🙂', level: 2 as const },
  { en: 'curious', vi: 'tò mò', emoji: '🔍', level: 2 as const },
  { en: 'worried', vi: 'lo lắng', emoji: '😟', level: 2 as const },
  { en: 'excited', vi: 'hào hứng', emoji: '🎉', level: 2 as const },
  { en: 'grammar', vi: 'ngữ pháp', emoji: '📚', level: 2 as const },
  { en: 'spelling', vi: 'chính tả', emoji: '✏️', level: 2 as const },
  { en: 'question', vi: 'câu hỏi', emoji: '❓', level: 2 as const },
  { en: 'answer', vi: 'câu trả lời', emoji: '✅', level: 2 as const },
  { en: 'weekend', vi: 'cuối tuần', emoji: '📅', level: 2 as const },
  { en: 'birthday', vi: 'sinh nhật', emoji: '🎂', level: 2 as const },
  { en: 'holiday', vi: 'ngày nghỉ', emoji: '🏖️', level: 2 as const },
  { en: 'kitchen', vi: 'nhà bếp', emoji: '🍳', level: 2 as const },
  { en: 'bedroom', vi: 'phòng ngủ', emoji: '🛏️', level: 2 as const },
  { en: 'bathroom', vi: 'phòng tắm', emoji: '🚿', level: 2 as const },
  { en: 'garden', vi: 'khu vườn', emoji: '🌻', level: 2 as const },
  { en: 'forest', vi: 'rừng', emoji: '🌲', level: 2 as const },
  { en: 'ocean', vi: 'đại dương', emoji: '🌊', level: 2 as const },
  { en: 'planet', vi: 'hành tinh', emoji: '🪐', level: 2 as const },
  { en: 'solar system', vi: 'hệ Mặt Trời', emoji: '☀️', level: 2 as const },
  { en: 'gravity', vi: 'trọng lực', emoji: '🌍', level: 2 as const },
  { en: 'magnet', vi: 'nam châm', emoji: '🧲', level: 2 as const },
  { en: 'electricity', vi: 'điện', emoji: '⚡', level: 2 as const },
  { en: 'battery', vi: 'pin', emoji: '🔋', level: 2 as const },
  { en: 'keyboard', vi: 'bàn phím', emoji: '⌨️', level: 2 as const },
  { en: 'screen', vi: 'màn hình', emoji: '🖥️', level: 2 as const },
  { en: 'internet', vi: 'mạng internet', emoji: '🌐', level: 2 as const },
  { en: 'weather', vi: 'thời tiết', emoji: '🌤️', level: 2 as const },
  { en: 'temperature', vi: 'nhiệt độ', emoji: '🌡️', level: 2 as const },
  { en: 'degree', vi: 'độ', emoji: '📐', level: 2 as const },
  { en: 'kilogram', vi: 'kilôgam', emoji: '⚖️', level: 2 as const },
  { en: 'liter', vi: 'lít', emoji: '🥤', level: 2 as const },
  { en: 'meter', vi: 'mét', emoji: '📏', level: 2 as const },
  { en: 'triangle', vi: 'tam giác', emoji: '🔺', level: 2 as const },
  { en: 'circle', vi: 'hình tròn', emoji: '⭕', level: 2 as const },
  { en: 'square', vi: 'hình vuông', emoji: '⬜', level: 2 as const },
  { en: 'rectangle', vi: 'hình chữ nhật', emoji: '▭', level: 2 as const },
  { en: 'fraction', vi: 'phân số', emoji: '➗', level: 2 as const },
  { en: 'decimal', vi: 'số thập phân', emoji: '🔢', level: 2 as const },
];
