import type { VocabPair } from './questions';
/** Từ vựng tiếng Anh lớp 4 — 186 cặp bổ sung */
export const VOCAB_SUPPLEMENT: VocabPair[] = [
  { en: 'classroom', vi: 'lớp học', emoji: '🏫', level: 1 as const },
  { en: 'homework', vi: 'bài tập về nhà', emoji: '📝', level: 1 as const },
  { en: 'subject', vi: 'môn học', emoji: '📖', level: 1 as const },
  { en: 'pencil case', vi: 'hộp bút', emoji: '✏️', level: 1 as const },
  { en: 'ruler', vi: 'thước kẻ', emoji: '📏', level: 1 as const },
  { en: 'eraser', vi: 'cục tẩy', emoji: '🧽', level: 1 as const },
  { en: 'chalk', vi: 'phấn', emoji: '🖍️', level: 1 as const },
  { en: 'uniform', vi: 'đồng phục', emoji: '👔', level: 1 as const },
  { en: 'playground', vi: 'sân chơi', emoji: '🛝', level: 1 as const },
  { en: 'cousin', vi: 'anh chị em họ', emoji: '👧', level: 1 as const },
  { en: 'grandparents', vi: 'ông bà', emoji: '👴', level: 1 as const },
  { en: 'nephew', vi: 'cháu trai', emoji: '👦', level: 1 as const },
  { en: 'niece', vi: 'cháu gái', emoji: '👧', level: 1 as const },
  { en: 'neighbor', vi: 'hàng xóm', emoji: '🏘️', level: 1 as const },
  { en: 'relative', vi: 'người thân', emoji: '👪', level: 1 as const },
  { en: 'buffalo', vi: 'con trâu', emoji: '🐃', level: 1 as const },
  { en: 'goat', vi: 'con dê', emoji: '🐐', level: 1 as const },
  { en: 'duck', vi: 'con vịt', emoji: '🦆', level: 1 as const },
  { en: 'chicken', vi: 'con gà', emoji: '🐔', level: 1 as const },
  { en: 'pig', vi: 'con lợn', emoji: '🐷', level: 1 as const },
  { en: 'sheep', vi: 'con cừu', emoji: '🐑', level: 1 as const },
  { en: 'tiger', vi: 'con hổ', emoji: '🐯', level: 1 as const },
  { en: 'bear', vi: 'con gấu', emoji: '🐻', level: 1 as const },
  { en: 'wolf', vi: 'con sói', emoji: '🐺', level: 1 as const },
  { en: 'peach', vi: 'quả đào', emoji: '🍑', level: 1 as const },
  { en: 'grape', vi: 'quả nho', emoji: '🍇', level: 1 as const },
  { en: 'mango', vi: 'quả xoài', emoji: '🥭', level: 1 as const },
  { en: 'pineapple', vi: 'quả dứa', emoji: '🍍', level: 1 as const },
  { en: 'carrot', vi: 'củ cà rốt', emoji: '🥕', level: 1 as const },
  { en: 'potato', vi: 'củ khoai tây', emoji: '🥔', level: 1 as const },
  { en: 'onion', vi: 'củ hành', emoji: '🧅', level: 1 as const },
  { en: 'tomato', vi: 'quả cà chua', emoji: '🍅', level: 1 as const },
  { en: 'cabbage', vi: 'cải bắp', emoji: '🥬', level: 1 as const },
  { en: 'noodle', vi: 'mì', emoji: '🍜', level: 1 as const },
  { en: 'soup', vi: 'súp', emoji: '🥣', level: 1 as const },
  { en: 'sandwich', vi: 'bánh mì kẹp', emoji: '🥪', level: 1 as const },
  { en: 'juice', vi: 'nước ép', emoji: '🧃', level: 1 as const },
  { en: 'biscuit', vi: 'bánh quy', emoji: '🍪', level: 1 as const },
  { en: 'yogurt', vi: 'sữa chua', emoji: '🥛', level: 1 as const },
  { en: 'doctor', vi: 'bác sĩ', emoji: '👨‍⚕️', level: 1 as const },
  { en: 'nurse', vi: 'y tá', emoji: '👩‍⚕️', level: 1 as const },
  { en: 'police officer', vi: 'cảnh sát', emoji: '👮', level: 1 as const },
  { en: 'firefighter', vi: 'lính cứu hỏa', emoji: '🚒', level: 1 as const },
  { en: 'engineer', vi: 'kỹ sư', emoji: '👷', level: 1 as const },
  { en: 'artist', vi: 'họa sĩ', emoji: '🎨', level: 1 as const },
  { en: 'musician', vi: 'nhạc sĩ', emoji: '🎵', level: 1 as const },
  { en: 'athlete', vi: 'vận động viên', emoji: '🏃', level: 1 as const },
  { en: 'pilot', vi: 'phi công', emoji: '✈️', level: 1 as const },
  { en: 'post office', vi: 'bưu điện', emoji: '📮', level: 1 as const },
  { en: 'supermarket', vi: 'siêu thị', emoji: '🛒', level: 1 as const },
  { en: 'bakery', vi: 'tiệm bánh', emoji: '🥖', level: 2 as const },
  { en: 'pharmacy', vi: 'nhà thuốc', emoji: '💊', level: 2 as const },
  { en: 'stadium', vi: 'sân vận động', emoji: '🏟️', level: 2 as const },
  { en: 'museum', vi: 'bảo tàng', emoji: '🏛️', level: 2 as const },
  { en: 'castle', vi: 'lâu đài', emoji: '🏰', level: 2 as const },
  { en: 'village', vi: 'làng quê', emoji: '🏡', level: 2 as const },
  { en: 'countryside', vi: 'nông thôn', emoji: '🌾', level: 2 as const },
  { en: 'desert', vi: 'sa mạc', emoji: '🏜️', level: 2 as const },
  { en: 'island', vi: 'hòn đảo', emoji: '🏝️', level: 2 as const },
  { en: 'waterfall', vi: 'thác nước', emoji: '💦', level: 2 as const },
  { en: 'volcano', vi: 'núi lửa', emoji: '🌋', level: 2 as const },
  { en: 'rainbow', vi: 'cầu vồng', emoji: '🌈', level: 2 as const },
  { en: 'storm', vi: 'bão', emoji: '🌪️', level: 2 as const },
  { en: 'foggy', vi: 'có sương mù', emoji: '🌫️', level: 2 as const },
  { en: 'windy', vi: 'có gió', emoji: '💨', level: 2 as const },
  { en: 'cloudy', vi: 'nhiều mây', emoji: '☁️', level: 2 as const },
  { en: 'sunny', vi: 'nắng', emoji: '☀️', level: 2 as const },
  { en: 'snowy', vi: 'có tuyết', emoji: '❄️', level: 2 as const },
  { en: 'season', vi: 'mùa', emoji: '🍂', level: 2 as const },
  { en: 'spring', vi: 'mùa xuân', emoji: '🌸', level: 2 as const },
  { en: 'summer', vi: 'mùa hè', emoji: '☀️', level: 2 as const },
  { en: 'autumn', vi: 'mùa thu', emoji: '🍁', level: 2 as const },
  { en: 'winter', vi: 'mùa đông', emoji: '⛄', level: 2 as const },
  { en: 'exercise', vi: 'tập thể dục', emoji: '🤸', level: 2 as const },
  { en: 'healthy', vi: 'khỏe mạnh', emoji: '💪', level: 2 as const },
  { en: 'illness', vi: 'bệnh tật', emoji: '🤒', level: 2 as const },
  { en: 'medicine', vi: 'thuốc', emoji: '💊', level: 2 as const },
  { en: 'toothache', vi: 'đau răng', emoji: '🦷', level: 2 as const },
  { en: 'headache', vi: 'đau đầu', emoji: '🤕', level: 2 as const },
  { en: 'fever', vi: 'sốt', emoji: '🌡️', level: 2 as const },
  { en: 'cough', vi: 'ho', emoji: '😷', level: 2 as const },
  { en: 'recycle', vi: 'tái chế', emoji: '♻️', level: 2 as const },
  { en: 'pollution', vi: 'ô nhiễm', emoji: '🏭', level: 2 as const },
  { en: 'plastic', vi: 'nhựa', emoji: '🧴', level: 2 as const },
  { en: 'metal', vi: 'kim loại', emoji: '🔩', level: 2 as const },
  { en: 'wood', vi: 'gỗ', emoji: '🪵', level: 2 as const },
  { en: 'glass', vi: 'thủy tinh', emoji: '🪟', level: 2 as const },
  { en: 'electricity', vi: 'điện', emoji: '⚡', level: 2 as const },
  { en: 'solar', vi: 'năng lượng mặt trời', emoji: '☀️', level: 2 as const },
  { en: 'battery', vi: 'pin', emoji: '🔋', level: 2 as const },
  { en: 'keyboard', vi: 'bàn phím', emoji: '⌨️', level: 2 as const },
  { en: 'screen', vi: 'màn hình', emoji: '🖥️', level: 2 as const },
  { en: 'internet', vi: 'mạng internet', emoji: '🌐', level: 2 as const },
  { en: 'download', vi: 'tải xuống', emoji: '⬇️', level: 2 as const },
  { en: 'password', vi: 'mật khẩu', emoji: '🔐', level: 2 as const },
  { en: 'website', vi: 'trang web', emoji: '🌐', level: 2 as const },
  { en: 'hobby', vi: 'sở thích', emoji: '🎯', level: 2 as const },
  { en: 'collect', vi: 'sưu tầm', emoji: '📦', level: 2 as const },
  { en: 'draw', vi: 'vẽ', emoji: '✏️', level: 2 as const },
  { en: 'sing', vi: 'hát', emoji: '🎤', level: 2 as const },
  { en: 'dance', vi: 'nhảy', emoji: '💃', level: 2 as const },
  { en: 'swim', vi: 'bơi', emoji: '🏊', level: 2 as const },
  { en: 'skate', vi: 'trượt patin', emoji: '⛸️', level: 2 as const },
  { en: 'camp', vi: 'cắm trại', emoji: '⛺', level: 2 as const },
  { en: 'picnic', vi: 'dã ngoại', emoji: '🧺', level: 2 as const },
  { en: 'ticket', vi: 'vé', emoji: '🎫', level: 2 as const },
  { en: 'passport', vi: 'hộ chiếu', emoji: '🛂', level: 2 as const },
  { en: 'luggage', vi: 'hành lý', emoji: '🧳', level: 2 as const },
  { en: 'airport', vi: 'sân bay', emoji: '✈️', level: 2 as const },
  { en: 'platform', vi: 'sân ga', emoji: '🚉', level: 2 as const },
  { en: 'traffic', vi: 'giao thông', emoji: '🚦', level: 2 as const },
  { en: 'helmet', vi: 'mũ bảo hiểm', emoji: '⛑️', level: 2 as const },
  { en: 'seatbelt', vi: 'dây an toàn', emoji: '🔒', level: 2 as const },
  { en: 'crosswalk', vi: 'vạch sang đường', emoji: '🚶', level: 2 as const },
  { en: 'charity', vi: 'từ thiện', emoji: '❤️', level: 2 as const },
  { en: 'volunteer', vi: 'tình nguyện', emoji: '🤝', level: 2 as const },
  { en: 'respect', vi: 'tôn trọng', emoji: '🙏', level: 2 as const },
  { en: 'honest', vi: 'trung thực', emoji: '✅', level: 2 as const },
  { en: 'brave', vi: 'dũng cảm', emoji: '🦁', level: 2 as const },
  { en: 'polite', vi: 'lịch sự', emoji: '🙂', level: 2 as const },
  { en: 'generous', vi: 'hào phóng', emoji: '🎁', level: 3 as const },
  { en: 'patient', vi: 'kiên nhẫn', emoji: '⏳', level: 3 as const },
  { en: 'creative', vi: 'sáng tạo', emoji: '💡', level: 3 as const },
  { en: 'curious', vi: 'tò mò', emoji: '🔍', level: 3 as const },
  { en: 'confident', vi: 'tự tin', emoji: '💪', level: 3 as const },
  { en: 'friendly', vi: 'thân thiện', emoji: '😊', level: 3 as const },
  { en: 'helpful', vi: 'hay giúp đỡ', emoji: '🤲', level: 3 as const },
  { en: 'careful', vi: 'cẩn thận', emoji: '⚠️', level: 3 as const },
  { en: 'proud', vi: 'tự hào', emoji: '🏆', level: 3 as const },
  { en: 'worried', vi: 'lo lắng', emoji: '😟', level: 3 as const },
  { en: 'excited', vi: 'hào hứng', emoji: '🎉', level: 3 as const },
  { en: 'surprised', vi: 'ngạc nhiên', emoji: '😲', level: 3 as const },
  { en: 'bored', vi: 'chán', emoji: '😑', level: 3 as const },
  { en: 'angry', vi: 'tức giận', emoji: '😠', level: 3 as const },
  { en: 'scared', vi: 'sợ hãi', emoji: '😨', level: 3 as const },
  { en: 'lonely', vi: 'cô đơn', emoji: '😔', level: 3 as const },
  { en: 'grateful', vi: 'biết ơn', emoji: '🙏', level: 3 as const },
  { en: 'fair', vi: 'công bằng', emoji: '⚖️', level: 3 as const },
  { en: 'peace', vi: 'hòa bình', emoji: '☮️', level: 3 as const },
  { en: 'freedom', vi: 'tự do', emoji: '🕊️', level: 3 as const },
  { en: 'culture', vi: 'văn hóa', emoji: '🎭', level: 3 as const },
  { en: 'tradition', vi: 'truyền thống', emoji: '🏮', level: 3 as const },
  { en: 'festival', vi: 'lễ hội', emoji: '🎊', level: 3 as const },
  { en: 'celebrate', vi: 'ăn mừng', emoji: '🎉', level: 3 as const },
  { en: 'decorate', vi: 'trang trí', emoji: '🎀', level: 3 as const },
  { en: 'perform', vi: 'biểu diễn', emoji: '🎭', level: 3 as const },
  { en: 'audience', vi: 'khán giả', emoji: '👥', level: 3 as const },
  { en: 'stage', vi: 'sân khấu', emoji: '🎪', level: 3 as const },
  { en: 'costume', vi: 'trang phục', emoji: '👗', level: 3 as const },
  { en: 'mask', vi: 'mặt nạ', emoji: '🎭', level: 3 as const },
  { en: 'fireworks', vi: 'pháo hoa', emoji: '🎆', level: 3 as const },
  { en: 'lantern', vi: 'đèn lồng', emoji: '🏮', level: 3 as const },
  { en: 'drum', vi: 'trống', emoji: '🥁', level: 3 as const },
  { en: 'flute', vi: 'sáo', emoji: '🎶', level: 3 as const },
  { en: 'violin', vi: 'đàn violin', emoji: '🎻', level: 3 as const },
  { en: 'guitar', vi: 'đàn ghi-ta', emoji: '🎸', level: 3 as const },
  { en: 'piano', vi: 'đàn piano', emoji: '🎹', level: 3 as const },
  { en: 'orchestra', vi: 'dàn nhạc', emoji: '🎼', level: 3 as const },
  { en: 'melody', vi: 'giai điệu', emoji: '🎵', level: 3 as const },
  { en: 'rhythm', vi: 'nhịp điệu', emoji: '🥁', level: 3 as const },
  { en: 'lyrics', vi: 'lời bài hát', emoji: '📝', level: 3 as const },
  { en: 'concert', vi: 'buổi hòa nhạc', emoji: '🎤', level: 3 as const },
  { en: 'album', vi: 'album nhạc', emoji: '💿', level: 3 as const },
  { en: 'photograph', vi: 'bức ảnh', emoji: '📷', level: 3 as const },
  { en: 'camera', vi: 'máy ảnh', emoji: '📸', level: 3 as const },
  { en: 'video', vi: 'video', emoji: '🎬', level: 3 as const },
  { en: 'cartoon', vi: 'phim hoạt hình', emoji: '📺', level: 3 as const },
  { en: 'documentary', vi: 'phim tài liệu', emoji: '🎞️', level: 3 as const },
  { en: 'novel', vi: 'tiểu thuyết', emoji: '📕', level: 3 as const },
  { en: 'poem', vi: 'bài thơ', emoji: '📜', level: 3 as const },
  { en: 'author', vi: 'tác giả', emoji: '✍️', level: 3 as const },
  { en: 'chapter', vi: 'chương sách', emoji: '📑', level: 3 as const },
  { en: 'paragraph', vi: 'đoạn văn', emoji: '📄', level: 3 as const },
  { en: 'dictionary', vi: 'từ điển', emoji: '📖', level: 3 as const },
  { en: 'translate', vi: 'dịch', emoji: '🔤', level: 3 as const },
  { en: 'pronounce', vi: 'phát âm', emoji: '🗣️', level: 3 as const },
  { en: 'grammar', vi: 'ngữ pháp', emoji: '📚', level: 3 as const },
  { en: 'vocabulary', vi: 'từ vựng', emoji: '📝', level: 3 as const },
  { en: 'spelling', vi: 'chính tả', emoji: '✏️', level: 3 as const },
  { en: 'pronoun', vi: 'đại từ', emoji: '👤', level: 3 as const },
  { en: 'adjective', vi: 'tính từ', emoji: '🏷️', level: 3 as const },
  { en: 'adverb', vi: 'trạng từ', emoji: '⏱️', level: 3 as const },
  { en: 'preposition', vi: 'giới từ', emoji: '📍', level: 3 as const },
  { en: 'conjunction', vi: 'liên từ', emoji: '🔗', level: 3 as const },
  { en: 'question', vi: 'câu hỏi', emoji: '❓', level: 3 as const },
  { en: 'answer', vi: 'câu trả lời', emoji: '✅', level: 3 as const },
];
