import type { SuDiaChallenge } from './challengeTypes';

/** Bổ sung độ phủ SGK — wave 2 (đề tham khảo S48, S50, S07) */
export const SU_DIA_BANK_EXTRA: SuDiaChallenge[] = [
  // địa phương
  {
    id: 'x-dp-cay-xanh',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dia-phuong',
    prompt: 'Trồng cây xanh ở trường, làng — SGK «Địa phương em» gắn vùng đồng bằng phía Bắc?',
    cardLabel: 'Cây xanh (Bắc Bộ)',
    region: 'bac-bo',
  },
  {
    id: 'x-dp-sach-se-song',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'dia-phuong',
    prompt: 'Giữ sạch sông, hồ quê em — miền đồng bằng sông lớn phía Nam?',
    cardLabel: 'Sạch sông (Nam Bộ)',
    region: 'nam-bo',
  },
  {
    id: 'x-dp-am-thuc',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'dia-phuong',
    prompt: 'Bánh xèo, hủ tiếu — đặc trưng ẩm thực vùng nào?',
    cardLabel: 'Ẩm thực Nam Bộ',
    region: 'nam-bo',
  },
  {
    id: 'x-dp-lang-nghe',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dia-phuong',
    prompt: 'Làng nghề truyền thống ven biển Trung — vùng?',
    cardLabel: 'Làng nghề biển',
    region: 'trung-bo',
  },

  // trung du Bắc Bộ
  {
    id: 'x-td-yen-bai',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Thác Bà, hồ thủy điện ở miền núi Tây Bắc — vùng?',
    cardLabel: 'Tây Bắc (núi)',
    region: 'bac-bo',
  },
  {
    id: 'x-td-tam-dao',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Tam Đảo (khí hậu mát) thuộc vùng núi phía Bắc?',
    cardLabel: 'Tam Đảo',
    region: 'bac-bo',
  },
  {
    id: 'x-td-thac-bac',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Thác nước ở miền núi Bắc Bộ — vùng thả?',
    cardLabel: 'Thác núi Bắc',
    region: 'bac-bo',
  },
  {
    id: 'x-td-dan-toc-mien-nui',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Trang phục dân tộc Thái, Mông ở miền núi phía Bắc — vùng?',
    cardLabel: 'Dân tộc miền núi Bắc',
    region: 'bac-bo',
  },

  // đồng bằng Bắc Bộ
  {
    id: 'x-db-thu-do-sao',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Ngôi sao đỏ trên bản đồ SGK đánh dấu thủ đô — vùng?',
    cardLabel: 'Thủ đô (sao đỏ)',
    region: 'bac-bo',
  },
  {
    id: 'x-db-chu-thu-phat',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Chùa Hương, chùa một cột — di tích vùng?',
    cardLabel: 'Di tích Hà Nội',
    region: 'bac-bo',
  },
  {
    id: 'x-db-dong-lua',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Hai vụ lúa/năng suất cao ở đồng bằng phía Bắc — vùng?',
    cardLabel: 'Lúa đồng bằng Bắc',
    region: 'bac-bo',
  },
  {
    id: 'x-db-quan-ho',
    kind: 'mix',
    minLevel: 3,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Quan họ Bắc Ninh — văn hóa vùng?',
    cardLabel: 'Quan họ',
    region: 'bac-bo',
  },

  // duyên hải Trung
  {
    id: 'x-dh-quang-nam',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Địa hình hẹp, một bên núi một bên biển — miền?',
    cardLabel: 'Đất hẹp ven biển',
    region: 'trung-bo',
  },
  {
    id: 'x-dh-pho-co',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Tháp Chăm ở Khánh Hòa, Ninh Thuận — miền?',
    cardLabel: 'Tháp Chăm',
    region: 'trung-bo',
  },
  {
    id: 'x-dh-bien-xanh',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Bãi biển đẹp (Nha Trang, Mỹ Khê) — vùng?',
    cardLabel: 'Bãi biển Trung',
    region: 'trung-bo',
  },
  {
    id: 'x-dh-san-hoi',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Muối, nghề biển ở ven biển Trung — vùng?',
    cardLabel: 'Muối biển',
    region: 'trung-bo',
  },

  // Tây Nguyên
  {
    id: 'x-tn-ca-phe',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'tay-nguyen',
    prompt: 'Hạt cà phê nổi tiếng — vùng trồng chính?',
    cardLabel: 'Cà phê',
    region: 'tay-nguyen',
  },
  {
    id: 'x-tn-hoa-lan',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'tay-nguyen',
    prompt: 'Hoa lan, rau Đà Lạt — vùng?',
    cardLabel: 'Hoa Đà Lạt',
    region: 'tay-nguyen',
  },
  {
    id: 'x-tn-thuy-dien',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'tay-nguyen',
    prompt: 'Thủy điện Yaly, Sêrêpôk — vùng cao nguyên?',
    cardLabel: 'Thủy điện Tây Nguyên',
    region: 'tay-nguyen',
  },
  {
    id: 'x-tn-cong-chieng',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'tay-nguyen',
    prompt: 'Không gian cồng chiêng Tây Nguyên — vùng?',
    cardLabel: 'Cồng chiêng',
    region: 'tay-nguyen',
  },

  // ĐBSCL
  {
    id: 'x-dbcl-an-giang',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dbscl',
    prompt: 'Tỉnh An Giang (miền Tây) thuộc vùng?',
    cardLabel: 'An Giang',
    region: 'nam-bo',
  },
  {
    id: 'x-dbcl-dong-thap',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dbscl',
    prompt: 'Đồng Tháp (sen, chim) — vùng?',
    cardLabel: 'Đồng Tháp',
    region: 'nam-bo',
  },
  {
    id: 'x-dbcl-nuoc-man',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'dbscl',
    prompt: 'Xâm nhập mặn ở cửa sông phía Nam — vùng?',
    cardLabel: 'Mặn cửa sông',
    region: 'nam-bo',
  },
  {
    id: 'x-dbcl-tom-cang',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dbscl',
    prompt: 'Tôm càng xanh, lúa tôm — vùng?',
    cardLabel: 'Tôm càng xanh',
    region: 'nam-bo',
  },
  {
    id: 'x-dbcl-song-tien',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'dbscl',
    prompt: 'Sông Tiền, Sông Hậu (nhánh Mekong) — vùng?',
    cardLabel: 'Sông Tiền / Hậu',
    region: 'nam-bo',
  },

  // lịch sử vùng
  {
    id: 'x-ls-tran-hung-dao',
    kind: 'su',
    minLevel: 2,
    sgkUnit: 'lich-su-vung',
    prompt: 'Trần Hưng Đạo chỉ huy trận Bạch Đằng 1288 — sông thuộc vùng?',
    cardLabel: 'Trần Hưng Đạo',
    region: 'bac-bo',
  },
  {
    id: 'x-ls-le-loi',
    kind: 'su',
    minLevel: 2,
    sgkUnit: 'lich-su-vung',
    prompt: 'Lê Lợi khởi nghĩa Lam Sơn (miền núi Trung Bộ phía Bắc) — vùng lớn?',
    cardLabel: 'Lam Sơn',
    region: 'bac-bo',
  },
  {
    id: 'x-ls-quang-trung',
    kind: 'su',
    minLevel: 3,
    sgkUnit: 'lich-su-vung',
    prompt: 'Quang Trung đại phá quân Thanh tại Đống Đa — vùng?',
    cardLabel: 'Quang Trung',
    region: 'bac-bo',
  },
  {
    id: 'x-ls-nguyen-trai',
    kind: 'su',
    minLevel: 3,
    sgkUnit: 'lich-su-vung',
    prompt: 'Bình Ngô đại cáo (Nguyễn Trời) sau Chi Lăng — vùng địa lý Bắc?',
    cardLabel: 'Bình Ngô đại cáo',
    region: 'bac-bo',
  },
  {
    id: 'x-ls-cham-pa',
    kind: 'mix',
    minLevel: 3,
    sgkUnit: 'lich-su-vung',
    prompt: 'Vương quốc Chăm Pa ven biển — miền?',
    cardLabel: 'Chăm Pa',
    region: 'trung-bo',
  },
  {
    id: 'x-ls-cu-chi',
    kind: 'su',
    minLevel: 3,
    sgkUnit: 'lich-su-vung',
    prompt: 'Địa đạo Củ Chi (kháng chiến) — vùng?',
    cardLabel: 'Củ Chi',
    region: 'nam-bo',
  },

  // bản đồ đảo
  {
    id: 'x-bd-hoang-sa-dn',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Hoàng Sa — thành phố Đà Nẵng (theo SGK) — ô thả?',
    cardLabel: 'Hoàng Sa',
    region: 'hoang-sa',
  },
  {
    id: 'x-bd-truong-sa',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Trường Sa trên biển Đông — vùng?',
    cardLabel: 'Trường Sa',
    region: 'truong-sa',
  },
  {
    id: 'x-bd-phu-quoc-vinh',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Phú Quốc ở vịnh Thái Lan — vùng đảo?',
    cardLabel: 'Phú Quốc (vịnh Thái Lan)',
    region: 'phu-quoc',
  },
  {
    id: 'x-bd-con-dao',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Côn Đảo (tỉnh Bà Rịa – Vũng Tàu trước đây) — ô Côn Sơn?',
    cardLabel: 'Côn Đảo',
    region: 'con-son',
  },
  {
    id: 'x-bd-bach-long',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Bạch Long Vĩ (vịnh Bắc Bộ) — vùng?',
    cardLabel: 'Bạch Long Vĩ',
    region: 'bach-long-vi',
  },
  {
    id: 'x-bd-ly-son-ngu',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Nghề biển đảo Lý Sơn — thả vào?',
    cardLabel: 'Lý Sơn',
    region: 'ly-son',
  },
  {
    id: 'x-bd-con-co-hai',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Cồn Cỏ giữa biển (Quảng Trị) — vùng?',
    cardLabel: 'Cồn Cỏ',
    region: 'con-co',
  },
  {
    id: 'x-bd-phu-quy',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Đảo Phú Quý nhỏ phía Nam Trung Bộ — vùng?',
    cardLabel: 'Phú Quý',
    region: 'phu-quy',
  },
  {
    id: 'x-bd-tho-chu-kg',
    kind: 'mix',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Thổ Chu (Kiên Giang) — quần đảo thả?',
    cardLabel: 'Thổ Chu',
    region: 'tho-chu',
  },
  {
    id: 'x-bd-bien-dong',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Lãnh thổ biển đảo phía Đông — Hoàng Sa thuộc vùng?',
    cardLabel: 'Biển Đông (Hoàng Sa)',
    region: 'hoang-sa',
  },
];
