import type { SuDiaChallenge } from './challengeTypes';

/** Bổ sung wave 3 — mở rộng độ phủ SGK / đề S48 S50 (mục tiêu ~200 câu tổng) */
export const SU_DIA_BANK_SUPPLEMENT: SuDiaChallenge[] = [
  // dia-phuong (+8)
  { id: 's-dp-1', kind: 'dia', minLevel: 1, sgkUnit: 'dia-phuong', prompt: 'Em ở tỉnh miền núi phía Bắc — trên bản đồ thuộc vùng?', cardLabel: 'Quê em (miền núi Bắc)', region: 'bac-bo' },
  { id: 's-dp-2', kind: 'mix', minLevel: 1, sgkUnit: 'dia-phuong', prompt: 'Học về quê hương gắn với sông nước miền Tây?', cardLabel: 'Sông quê (miền Tây)', region: 'nam-bo' },
  { id: 's-dp-3', kind: 'dia', minLevel: 2, sgkUnit: 'dia-phuong', prompt: 'Khí hậu quê em khô nắng như Nam Trung Bộ — vùng?', cardLabel: 'Khô nắng (Trung Bộ)', region: 'trung-bo' },
  { id: 's-dp-4', kind: 'mix', minLevel: 2, sgkUnit: 'dia-phuong', prompt: 'Bảo vệ rừng, động vật hoang dã ở cao nguyên — vùng?', cardLabel: 'Bảo vệ rừng (Tây Nguyên)', region: 'tay-nguyen' },
  { id: 's-dp-5', kind: 'dia', minLevel: 1, sgkUnit: 'dia-phuong', prompt: 'Làng quê đồng bằng phía Bắc — vùng thả?', cardLabel: 'Làng quê Bắc Bộ', region: 'bac-bo' },
  { id: 's-dp-6', kind: 'mix', minLevel: 3, sgkUnit: 'dia-phuong', prompt: 'Hội làng, chùa làng ở đồng bằng Bắc — vùng?', cardLabel: 'Hội làng (Bắc)', region: 'bac-bo' },
  { id: 's-dp-7', kind: 'dia', minLevel: 2, sgkUnit: 'dia-phuong', prompt: 'Nghề biển địa phương ven biển Trung — vùng?', cardLabel: 'Nghề biển (Trung)', region: 'trung-bo' },
  { id: 's-dp-8', kind: 'mix', minLevel: 3, sgkUnit: 'dia-phuong', prompt: 'Chợ quê miền Tây sông nước — vùng?', cardLabel: 'Chợ miền Tây', region: 'nam-bo' },

  // trung-du-bac-bo (+10)
  { id: 's-td-1', kind: 'dia', minLevel: 1, sgkUnit: 'trung-du-bac-bo', prompt: 'Tỉnh Lào Cai (cao, lạnh) — vùng?', cardLabel: 'Lào Cai', region: 'bac-bo' },
  { id: 's-td-2', kind: 'dia', minLevel: 2, sgkUnit: 'trung-du-bac-bo', prompt: 'Cao nguyên Mộc Châu thuộc miền núi phía Bắc?', cardLabel: 'Mộc Châu (núi Bắc)', region: 'bac-bo' },
  { id: 's-td-3', kind: 'dia', minLevel: 2, sgkUnit: 'trung-du-bac-bo', prompt: 'Thác Bản Giốc (Cao Bằng) — vùng?', cardLabel: 'Thác Bản Giốc', region: 'bac-bo' },
  { id: 's-td-4', kind: 'dia', minLevel: 3, sgkUnit: 'trung-du-bac-bo', prompt: 'Hồ Ba Bể (Bắc Kạn) — vùng?', cardLabel: 'Hồ Ba Bể', region: 'bac-bo' },
  { id: 's-td-5', kind: 'dia', minLevel: 2, sgkUnit: 'trung-du-bac-bo', prompt: 'Đỉnh núi cao nhất Đông Dương (Phan-xi-păng) — vùng?', cardLabel: 'Fansipan', region: 'bac-bo' },
  { id: 's-td-6', kind: 'mix', minLevel: 3, sgkUnit: 'trung-du-bac-bo', prompt: 'Dân tộc Dao, H’Mông ở miền núi Bắc — vùng?', cardLabel: 'Dân tộc miền núi', region: 'bac-bo' },
  { id: 's-td-7', kind: 'dia', minLevel: 1, sgkUnit: 'trung-du-bac-bo', prompt: 'Sương mù, mùa đông lạnh ở vùng núi phía Bắc?', cardLabel: 'Đông lạnh (Bắc)', region: 'bac-bo' },
  { id: 's-td-8', kind: 'dia', minLevel: 3, sgkUnit: 'trung-du-bac-bo', prompt: 'Tỉnh Sơn La (thung lũng, thủy điện) — vùng?', cardLabel: 'Sơn La', region: 'bac-bo' },
  { id: 's-td-9', kind: 'dia', minLevel: 2, sgkUnit: 'trung-du-bac-bo', prompt: 'Đèo Khau (miền núi Bắc) — vùng lớn?', cardLabel: 'Đèo Khau', region: 'bac-bo' },
  { id: 's-td-10', kind: 'dia', minLevel: 3, sgkUnit: 'trung-du-bac-bo', prompt: 'Chè Shan tỉnh Thái Nguyên — vùng?', cardLabel: 'Chè Thái Nguyên', region: 'bac-bo' },

  // dong-bang-bac-bo (+10)
  { id: 's-db-1', kind: 'dia', minLevel: 1, sgkUnit: 'dong-bang-bac-bo', prompt: 'TP. Hồ Chí Minh không thuộc Bắc Bộ — Hà Nội thuộc vùng?', cardLabel: 'Hà Nội (thủ đô)', region: 'bac-bo' },
  { id: 's-db-2', kind: 'dia', minLevel: 2, sgkUnit: 'dong-bang-bac-bo', prompt: 'Sông Hồng chảy qua đồng bằng phía Bắc — vùng?', cardLabel: 'Lưu vực sông Hồng', region: 'bac-bo' },
  { id: 's-db-3', kind: 'dia', minLevel: 2, sgkUnit: 'dong-bang-bac-bo', prompt: 'Cảng Hải Phòng — vùng?', cardLabel: 'Cảng Hải Phòng', region: 'bac-bo' },
  { id: 's-db-4', kind: 'dia', minLevel: 3, sgkUnit: 'dong-bang-bac-bo', prompt: 'Đồng bằng châu thổ sông Hồng — vùng?', cardLabel: 'Châu thổ sông Hồng', region: 'bac-bo' },
  { id: 's-db-5', kind: 'mix', minLevel: 2, sgkUnit: 'dong-bang-bac-bo', prompt: 'Lễ hội chùa Hương (Hà Nội) — vùng?', cardLabel: 'Chùa Hương', region: 'bac-bo' },
  { id: 's-db-6', kind: 'dia', minLevel: 3, sgkUnit: 'dong-bang-bac-bo', prompt: 'Tỉnh Thái Bình (lúa, tôm) — vùng?', cardLabel: 'Thái Bình', region: 'bac-bo' },
  { id: 's-db-7', kind: 'dia', minLevel: 2, sgkUnit: 'dong-bang-bac-bo', prompt: 'Vịnh Hạ Long (Quảng Ninh) — vùng?', cardLabel: 'Hạ Long', region: 'bac-bo' },
  { id: 's-db-8', kind: 'dia', minLevel: 1, sgkUnit: 'dong-bang-bac-bo', prompt: 'Đông dân, nhiều làng quê ở đồng bằng phía Bắc — vùng?', cardLabel: 'Đông dân (Bắc)', region: 'bac-bo' },
  { id: 's-db-9', kind: 'mix', minLevel: 3, sgkUnit: 'dong-bang-bac-bo', prompt: 'Khu di tích Cổ Loa (Hà Nội) — vùng?', cardLabel: 'Cổ Loa', region: 'bac-bo' },
  { id: 's-db-10', kind: 'dia', minLevel: 3, sgkUnit: 'dong-bang-bac-bo', prompt: 'Sông Cầu, sông Thương — vùng đồng bằng Bắc?', cardLabel: 'Sông Cầu', region: 'bac-bo' },

  // duyen-hai-trung (+10)
  { id: 's-dh-1', kind: 'dia', minLevel: 1, sgkUnit: 'duyen-hai-trung', prompt: 'Đà Nẵng thuộc miền Trung?', cardLabel: 'Đà Nẵng', region: 'trung-bo' },
  { id: 's-dh-2', kind: 'dia', minLevel: 2, sgkUnit: 'duyen-hai-trung', prompt: 'Bán đảo Sơn Trà (Đà Nẵng) — miền?', cardLabel: 'Sơn Trà', region: 'trung-bo' },
  { id: 's-dh-3', kind: 'dia', minLevel: 2, sgkUnit: 'duyen-hai-trung', prompt: 'Cố đô Huế — miền Trung?', cardLabel: 'Huế', region: 'trung-bo' },
  { id: 's-dh-4', kind: 'dia', minLevel: 3, sgkUnit: 'duyen-hai-trung', prompt: 'Thành phố Quy Nhơn (Bình Định) — vùng?', cardLabel: 'Quy Nhơn', region: 'trung-bo' },
  { id: 's-dh-5', kind: 'dia', minLevel: 2, sgkUnit: 'duyen-hai-trung', prompt: 'Đèo Hải Vân ngăn Bắc–Trung — thả vào miền?', cardLabel: 'Đèo Hải Vân → Trung', region: 'trung-bo' },
  { id: 's-dh-6', kind: 'mix', minLevel: 3, sgkUnit: 'duyen-hai-trung', prompt: 'Tháp Chăm Mỹ Sơn — miền?', cardLabel: 'Mỹ Sơn', region: 'trung-bo' },
  { id: 's-dh-7', kind: 'dia', minLevel: 1, sgkUnit: 'duyen-hai-trung', prompt: 'Dải đất hẹp ven biển phía Trung — vùng?', cardLabel: 'Dải ven biển Trung', region: 'trung-bo' },
  { id: 's-dh-8', kind: 'dia', minLevel: 3, sgkUnit: 'duyen-hai-trung', prompt: 'Ninh Thuận (nho, cừu) — miền?', cardLabel: 'Ninh Thuận', region: 'trung-bo' },
  { id: 's-dh-9', kind: 'dia', minLevel: 2, sgkUnit: 'duyen-hai-trung', prompt: 'Bão lũ thường gặp ở miền Trung — vùng?', cardLabel: 'Bão (miền Trung)', region: 'trung-bo' },
  { id: 's-dh-10', kind: 'mix', minLevel: 3, sgkUnit: 'duyen-hai-trung', prompt: 'Phố cổ Hội An — miền?', cardLabel: 'Hội An', region: 'trung-bo' },

  // tay-nguyen (+10)
  { id: 's-tn-1', kind: 'dia', minLevel: 2, sgkUnit: 'tay-nguyen', prompt: 'Đắk Lắk (voi, cà phê) — vùng?', cardLabel: 'Đắk Lắk', region: 'tay-nguyen' },
  { id: 's-tn-2', kind: 'dia', minLevel: 2, sgkUnit: 'tay-nguyen', prompt: 'Gia Lai (Pleiku) — vùng?', cardLabel: 'Gia Lai', region: 'tay-nguyen' },
  { id: 's-tn-3', kind: 'dia', minLevel: 2, sgkUnit: 'tay-nguyen', prompt: 'Đất đỏ bazan Tây Nguyên — vùng?', cardLabel: 'Đất bazan', region: 'tay-nguyen' },
  { id: 's-tn-4', kind: 'dia', minLevel: 3, sgkUnit: 'tay-nguyen', prompt: 'Lâm Đồng (Đà Lạt) — vùng?', cardLabel: 'Lâm Đồng', region: 'tay-nguyen' },
  { id: 's-tn-5', kind: 'mix', minLevel: 2, sgkUnit: 'tay-nguyen', prompt: 'Nhà rông Tây Nguyên — vùng?', cardLabel: 'Nhà rông', region: 'tay-nguyen' },
  { id: 's-tn-6', kind: 'dia', minLevel: 3, sgkUnit: 'tay-nguyen', prompt: 'Rừng thông, thác Dambri — vùng?', cardLabel: 'Thác Dambri', region: 'tay-nguyen' },
  { id: 's-tn-7', kind: 'dia', minLevel: 2, sgkUnit: 'tay-nguyen', prompt: 'Kon Tum (miền núi cao) — vùng?', cardLabel: 'Kon Tum', region: 'tay-nguyen' },
  { id: 's-tn-8', kind: 'mix', minLevel: 3, sgkUnit: 'tay-nguyen', prompt: 'Cồng chiêng Tây Nguyên — vùng?', cardLabel: 'Di sản cồng chiêng', region: 'tay-nguyen' },
  { id: 's-tn-9', kind: 'dia', minLevel: 1, sgkUnit: 'tay-nguyen', prompt: 'Cao nguyên xen giữa Trung và Nam — vùng?', cardLabel: 'Cao nguyên giữa', region: 'tay-nguyen' },
  { id: 's-tn-10', kind: 'dia', minLevel: 3, sgkUnit: 'tay-nguyen', prompt: 'Hồ T’Nưng (Pleiku) — vùng?', cardLabel: 'Hồ T’Nưng', region: 'tay-nguyen' },

  // dbscl (+10)
  { id: 's-cl-1', kind: 'dia', minLevel: 1, sgkUnit: 'dbscl', prompt: 'Miền Tây sông nước — vùng?', cardLabel: 'Miền Tây', region: 'nam-bo' },
  { id: 's-cl-2', kind: 'dia', minLevel: 2, sgkUnit: 'dbscl', prompt: 'Kiên Giang (rừng ngập mặn) — vùng?', cardLabel: 'Kiên Giang', region: 'nam-bo' },
  { id: 's-cl-3', kind: 'dia', minLevel: 2, sgkUnit: 'dbscl', prompt: 'Bến Tre (dừa) — vùng?', cardLabel: 'Bến Tre', region: 'nam-bo' },
  { id: 's-cl-4', kind: 'dia', minLevel: 3, sgkUnit: 'dbscl', prompt: 'Cà Mau (mũi đất cực Nam) — vùng?', cardLabel: 'Cà Mau', region: 'nam-bo' },
  { id: 's-cl-5', kind: 'dia', minLevel: 2, sgkUnit: 'dbscl', prompt: 'Sông Tiền, Sông Hậu — vùng?', cardLabel: 'Nhánh Mekong', region: 'nam-bo' },
  { id: 's-cl-6', kind: 'mix', minLevel: 2, sgkUnit: 'dbscl', prompt: 'Chợ nổi Cái Răng — vùng?', cardLabel: 'Cái Răng', region: 'nam-bo' },
  { id: 's-cl-7', kind: 'dia', minLevel: 3, sgkUnit: 'dbscl', prompt: 'Vườn trái cây miệt vườn — vùng?', cardLabel: 'Miệt vườn', region: 'nam-bo' },
  { id: 's-cl-8', kind: 'dia', minLevel: 1, sgkUnit: 'dbscl', prompt: 'Lúa nước, tôm cá ĐBSCL — vùng?', cardLabel: 'Lúa tôm', region: 'nam-bo' },
  { id: 's-cl-9', kind: 'mix', minLevel: 3, sgkUnit: 'dbscl', prompt: 'Đờn ca tài tử miền Nam — vùng?', cardLabel: 'Cải lương', region: 'nam-bo' },
  { id: 's-cl-10', kind: 'dia', minLevel: 3, sgkUnit: 'dbscl', prompt: 'U Minh (rừng tràm) — vùng?', cardLabel: 'U Minh', region: 'nam-bo' },

  // lich-su-vung (+12)
  { id: 's-ls-1', kind: 'su', minLevel: 1, sgkUnit: 'lich-su-vung', prompt: 'Văn Lang – Âu Lạc ở vùng đồng bằng Bắc — thả?', cardLabel: 'Văn Lang', region: 'bac-bo' },
  { id: 's-ls-2', kind: 'su', minLevel: 2, sgkUnit: 'lich-su-vung', prompt: 'Trần Hưng Đạo – Bạch Đằng 1288 — vùng sông?', cardLabel: '1288 Bạch Đằng', region: 'bac-bo' },
  { id: 's-ls-3', kind: 'su', minLevel: 2, sgkUnit: 'lich-su-vung', prompt: 'Lê Lợi – Lam Sơn (miền núi Trung Bộ phía Bắc) — vùng lớn?', cardLabel: 'Lê Lợi', region: 'bac-bo' },
  { id: 's-ls-4', kind: 'su', minLevel: 3, sgkUnit: 'lich-su-vung', prompt: 'Quang Trung – Đống Đa 1789 — vùng?', cardLabel: '1789 Đống Đa', region: 'bac-bo' },
  { id: 's-ls-5', kind: 'su', minLevel: 2, sgkUnit: 'lich-su-vung', prompt: 'Nguyễn Huệ đại phá quân Thanh — vùng Hà Nội?', cardLabel: 'Nguyễn Huệ', region: 'bac-bo' },
  { id: 's-ls-6', kind: 'su', minLevel: 3, sgkUnit: 'lich-su-vung', prompt: 'Điện Biên Phủ 1954 — vùng núi Tây Bắc?', cardLabel: '1954 Điện Biên', region: 'bac-bo' },
  { id: 's-ls-7', kind: 'su', minLevel: 2, sgkUnit: 'lich-su-vung', prompt: 'Triều Nguyễn – kinh thành Huế — miền?', cardLabel: 'Triều Nguyễn', region: 'trung-bo' },
  { id: 's-ls-8', kind: 'su', minLevel: 3, sgkUnit: 'lich-su-vung', prompt: 'Khởi nghĩa Tây Sơn (Bình Định) — miền?', cardLabel: 'Tây Sơn', region: 'trung-bo' },
  { id: 's-ls-9', kind: 'su', minLevel: 3, sgkUnit: 'lich-su-vung', prompt: 'Địa đạo Củ Chi — vùng?', cardLabel: 'Củ Chi', region: 'nam-bo' },
  { id: 's-ls-10', kind: 'su', minLevel: 2, sgkUnit: 'lich-su-vung', prompt: 'Ngô Quyền 938 — sông Bạch Đằng — vùng?', cardLabel: 'Ngô Quyền 938', region: 'bac-bo' },
  { id: 's-ls-11', kind: 'su', minLevel: 3, sgkUnit: 'lich-su-vung', prompt: 'Chi Lăng 1427 — vùng núi phía Bắc?', cardLabel: '1427 Chi Lăng', region: 'bac-bo' },
  { id: 's-ls-12', kind: 'mix', minLevel: 2, sgkUnit: 'lich-su-vung', prompt: 'Vua Hùng (truyền thuyết) gắn đồng bằng Bắc — vùng?', cardLabel: 'Vua Hùng', region: 'bac-bo' },

  // ban-do-dao (+18)
  { id: 's-bd-1', kind: 'dia', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Hoàng Sa — TP Đà Nẵng — ô thả?', cardLabel: 'Hoàng Sa', region: 'hoang-sa' },
  { id: 's-bd-2', kind: 'dia', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Trường Sa — Khánh Hòa — ô thả?', cardLabel: 'Trường Sa', region: 'truong-sa' },
  { id: 's-bd-3', kind: 'dia', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Phú Quốc — vịnh Thái Lan — ô?', cardLabel: 'Phú Quốc', region: 'phu-quoc' },
  { id: 's-bd-4', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Côn Đảo — ô Côn Sơn?', cardLabel: 'Côn Đảo', region: 'con-son' },
  { id: 's-bd-5', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Bạch Long Vĩ — vịnh Bắc Bộ — ô?', cardLabel: 'Bạch Long Vĩ', region: 'bach-long-vi' },
  { id: 's-bd-6', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Lý Sơn (Quảng Ngãi) — ô?', cardLabel: 'Lý Sơn', region: 'ly-son' },
  { id: 's-bd-7', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Cồn Cỏ — ô?', cardLabel: 'Cồn Cỏ', region: 'con-co' },
  { id: 's-bd-8', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Phú Quý — ô?', cardLabel: 'Phú Quý', region: 'phu-quy' },
  { id: 's-bd-9', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Thổ Chu (Kiên Giang) — ô?', cardLabel: 'Thổ Chu', region: 'tho-chu' },
  { id: 's-bd-10', kind: 'mix', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Lãnh thổ biển đảo phía Đông — Hoàng Sa?', cardLabel: 'Biển Đông (HS)', region: 'hoang-sa' },
  { id: 's-bd-11', kind: 'mix', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Quần đảo Trường Sa thuộc Khánh Hòa — thả?', cardLabel: 'TS (Khánh Hòa)', region: 'truong-sa' },
  { id: 's-bd-12', kind: 'dia', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Đảo lớn nhất VN (Phú Quốc) — ô?', cardLabel: 'Đảo lớn Phú Quốc', region: 'phu-quoc' },
  { id: 's-bd-13', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Côn Sơn xa bờ Nam — ô?', cardLabel: 'Côn Sơn xa bờ', region: 'con-son' },
  { id: 's-bd-14', kind: 'mix', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Nhãn SGK «quần đảo Hoàng Sa» — vùng?', cardLabel: 'Nhãn Hoàng Sa', region: 'hoang-sa' },
  { id: 's-bd-15', kind: 'mix', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Nhãn SGK «quần đảo Trường Sa» — vùng?', cardLabel: 'Nhãn Trường Sa', region: 'truong-sa' },
  { id: 's-bd-16', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Đảo tiền phương Bạch Long Vĩ — ô?', cardLabel: 'Tiền phương BLV', region: 'bach-long-vi' },
  { id: 's-bd-17', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Đảo Lý Sơn — nghề biển — ô?', cardLabel: 'Lý Sơn (biển)', region: 'ly-son' },
  { id: 's-bd-18', kind: 'mix', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Chủ quyền biển đảo — Trường Sa — ô?', cardLabel: 'Chủ quyền TS', region: 'truong-sa' },
  { id: 's-bd-19', kind: 'dia', minLevel: 1, sgkUnit: 'ban-do-dao', prompt: 'Biển Đông — quần đảo phía Đông — Hoàng Sa?', cardLabel: 'Biển Đông', region: 'hoang-sa' },
  { id: 's-bd-20', kind: 'dia', minLevel: 2, sgkUnit: 'ban-do-dao', prompt: 'Vịnh Thái Lan — đảo Phú Quốc — ô?', cardLabel: 'Vịnh Thái Lan', region: 'phu-quoc' },
  { id: 's-mix-1', kind: 'mix', minLevel: 1, sgkUnit: 'dong-bang-bac-bo', prompt: 'Sông Hồng bắt nguồn từ Trung Quốc, chảy qua vùng?', cardLabel: 'Sông Hồng', region: 'bac-bo' },
  { id: 's-mix-2', kind: 'mix', minLevel: 2, sgkUnit: 'duyen-hai-trung', prompt: 'Dải đất hẹp — một bên núi một bên biển — miền?', cardLabel: 'Đất hẹp', region: 'trung-bo' },
  { id: 's-mix-3', kind: 'dia', minLevel: 1, sgkUnit: 'dbscl', prompt: 'Châu thổ sông Cửu Long — vùng?', cardLabel: 'Châu thổ Cửu Long', region: 'nam-bo' },
  { id: 's-mix-4', kind: 'su', minLevel: 2, sgkUnit: 'lich-su-vung', prompt: 'Lê Hoàn đánh Tống 981 — sông Bạch Đằng — vùng?', cardLabel: 'Lê Hoàn 981', region: 'bac-bo' },
  { id: 's-mix-5', kind: 'dia', minLevel: 2, sgkUnit: 'tay-nguyen', prompt: 'Cao nguyên trung bộ nước ta — Tây Nguyên?', cardLabel: 'Cao nguyên TB', region: 'tay-nguyen' },
  { id: 's-mix-6', kind: 'dia', minLevel: 1, sgkUnit: 'trung-du-bac-bo', prompt: 'Núi cao, đồi dốc phía Bắc — vùng?', cardLabel: 'Đồi núi Bắc', region: 'bac-bo' },
  { id: 's-mix-7', kind: 'mix', minLevel: 3, sgkUnit: 'dia-phuong', prompt: 'Yêu quê hương, giữ gìn di tích địa phương — gắn vùng em học?', cardLabel: 'Yêu quê hương', region: 'bac-bo' },
  { id: 's-mix-8', kind: 'dia', minLevel: 3, sgkUnit: 'ban-do-dao', prompt: 'Đảo nhỏ Phú Quý — Nam Trung Bộ — ô?', cardLabel: 'Phú Quý (nhỏ)', region: 'phu-quy' },
];
