import type { SuDiaChallenge } from './challengeTypes';

/** Ngân hàng chính — bám SGK Lịch sử và Địa lí 4 KNTT (Hình 1 + các chương vùng) */
export const SU_DIA_BANK: SuDiaChallenge[] = [
  // —— Địa phương em ——
  {
    id: 'dp-song-dia-phuong',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dia-phuong',
    prompt: 'Sông quê em (ở tỉnh mình) thường được học cùng bài «Địa phương em» — thuộc vùng nào trên bản đồ tổng thể?',
    cardLabel: 'Sông quê (vùng em)',
    region: 'bac-bo',
  },
  {
    id: 'dp-bao-ve-moi-truong',
    kind: 'mix',
    minLevel: 1,
    sgkUnit: 'dia-phuong',
    prompt: 'Trồng cây, giữ sạch môi trường địa phương — SGK gắn với hiểu biết vùng miền. Miền Bắc lục địa?',
    cardLabel: 'Bảo vệ môi trường (Bắc)',
    region: 'bac-bo',
  },
  {
    id: 'dp-le-hoi-dia-phuong',
    kind: 'mix',
    minLevel: 1,
    sgkUnit: 'dia-phuong',
    prompt: 'Lễ hội địa phương (bánh chưng, hội làng…) — vùng đồng bằng phía Nam?',
    cardLabel: 'Lễ hội Nam Bộ',
    region: 'nam-bo',
  },
  {
    id: 'dp-dac-san-mien',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dia-phuong',
    prompt: 'Đặc sản miền Trung (nắng gió, biển) — thuộc vùng nào?',
    cardLabel: 'Đặc sản miền Trung',
    region: 'trung-bo',
  },
  {
    id: 'dp-khi-hau-quen-thuoc',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dia-phuong',
    prompt: 'So sánh khí hậu quê em với vùng cao nguyên phía Nam Trung Bộ?',
    cardLabel: 'Khí hậu Tây Nguyên',
    region: 'tay-nguyen',
  },
  {
    id: 'dp-dan-toc-ban-dia',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'dia-phuong',
    prompt: 'Văn hóa các dân tộc trên cao nguyên (cồng chiêng, nhà rông) — vùng?',
    cardLabel: 'Văn hóa cao nguyên',
    region: 'tay-nguyen',
  },

  // —— Trung du và miền núi Bắc Bộ ——
  {
    id: 'dia-phan-xi-pang',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Đỉnh Phan-xi-păng (Fansipan) thuộc vùng nào?',
    cardLabel: 'Phan-xi-păng',
    region: 'bac-bo',
  },
  {
    id: 'dia-hoang-lien-son',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Dãy núi Hoàng Liên Sơn nằm ở miền nào?',
    cardLabel: 'Hoàng Liên Sơn',
    region: 'bac-bo',
  },
  {
    id: 'dia-moc-chau',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Cao nguyên Mộc Châu (đồi chè, bò sữa) thuộc vùng nào?',
    cardLabel: 'Mộc Châu',
    region: 'bac-bo',
  },
  {
    id: 'dia-sa-pa',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Thị trấn Sa Pa (nhiều sương mù, ruộng bậc thang) thuộc vùng nào?',
    cardLabel: 'Sa Pa',
    region: 'bac-bo',
  },
  {
    id: 'dia-ruong-bac-thang',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Ruộng bậc thang ở miền núi phía Bắc — vùng thả?',
    cardLabel: 'Ruộng bậc thang Bắc',
    region: 'bac-bo',
  },
  {
    id: 'dia-song-da-bac',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Sông Đà (thủy điện Hòa Bình) chảy qua vùng núi phía Bắc — thuộc?',
    cardLabel: 'Sông Đà',
    region: 'bac-bo',
  },
  {
    id: 'dia-khi-hau-mien-nui-bac',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'trung-du-bac-bo',
    prompt: 'Mùa đông lạnh ở vùng núi cao phía Bắc — vùng nào?',
    cardLabel: 'Đông lạnh (miền núi Bắc)',
    region: 'bac-bo',
  },

  // —— Đồng bằng Bắc Bộ ——
  {
    id: 'dia-song-hong',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Đồng bằng sông Hồng thuộc vùng nào?',
    cardLabel: 'Đồng bằng sông Hồng',
    region: 'bac-bo',
  },
  {
    id: 'dia-ha-noi',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Thủ đô Hà Nội nằm ở vùng nào?',
    cardLabel: 'Hà Nội',
    region: 'bac-bo',
  },
  {
    id: 'dia-hai-phong',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Thành phố Hải Phòng (cảng biển) thuộc vùng nào?',
    cardLabel: 'Hải Phòng',
    region: 'bac-bo',
  },
  {
    id: 'dia-vinh-ha-long',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Vịnh Hạ Long thuộc vùng nào?',
    cardLabel: 'Vịnh Hạ Long',
    region: 'bac-bo',
  },
  {
    id: 'dia-dong-bang-bac-bo',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Đồng bằng Bắc Bộ (đông dân, nhiều làng quê) — vùng?',
    cardLabel: 'Đồng bằng Bắc Bộ',
    region: 'bac-bo',
  },
  {
    id: 'dia-song-thai-binh',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Đồng bằng sông Thái Bình nằm ở vùng nào?',
    cardLabel: 'Sông Thái Bình',
    region: 'bac-bo',
  },
  {
    id: 'dia-nam-dinh',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'dong-bang-bac-bo',
    prompt: 'Tỉnh Nam Định (đồng bằng phía Bắc) thuộc vùng?',
    cardLabel: 'Nam Định',
    region: 'bac-bo',
  },

  // —— Duyên hải miền Trung ——
  {
    id: 'dia-deo-hai-van',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Đèo Hải Vân là ranh giới tự nhiên giữa Bắc Bộ và vùng nào?',
    cardLabel: 'Đèo Hải Vân',
    region: 'trung-bo',
  },
  {
    id: 'dia-hue',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Cố đô Huế nằm ở miền nào của Việt Nam?',
    cardLabel: 'Cố đô Huế',
    region: 'trung-bo',
  },
  {
    id: 'dia-da-nang',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Thành phố Đà Nẵng thuộc miền nào?',
    cardLabel: 'Đà Nẵng',
    region: 'trung-bo',
  },
  {
    id: 'dia-nha-trang',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Thành phố Nha Trang thuộc miền nào?',
    cardLabel: 'Nha Trang',
    region: 'trung-bo',
  },
  {
    id: 'dia-bao-lut-trung',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Bão, lũ ở dải đất hẹp ven biển phía Trung — vùng?',
    cardLabel: 'Bão miền Trung',
    region: 'trung-bo',
  },
  {
    id: 'dia-han-han-trung',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Hạn hán ở Nam Trung Bộ (Ninh Thuận, Bình Thuận) — vùng thả?',
    cardLabel: 'Hạn hán (Nam Trung Bộ)',
    region: 'trung-bo',
  },
  {
    id: 'dia-lang-co',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'duyen-hai-trung',
    prompt: 'Làng cổ Hội An (du lịch) thuộc miền nào?',
    cardLabel: 'Hội An',
    region: 'trung-bo',
  },

  // —— Tây Nguyên ——
  {
    id: 'dia-tay-nguyen',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'tay-nguyen',
    prompt: 'Cao nguyên đất đỏ bazan, cà phê — vùng nào?',
    cardLabel: 'Tây Nguyên',
    region: 'tay-nguyen',
  },
  {
    id: 'dia-buon-ma-thuot',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'tay-nguyen',
    prompt: 'Buôn Ma Thuột thuộc vùng nào?',
    cardLabel: 'Buôn Ma Thuột',
    region: 'tay-nguyen',
  },
  {
    id: 'dia-da-lat',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'tay-nguyen',
    prompt: 'Thành phố Đà Lạt (khí hậu mát) thuộc vùng nào?',
    cardLabel: 'Đà Lạt',
    region: 'tay-nguyen',
  },
  {
    id: 'dia-rung-tay-nguyen',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'tay-nguyen',
    prompt: 'Rừng thông, thác nước trên cao nguyên — vùng?',
    cardLabel: 'Rừng Tây Nguyên',
    region: 'tay-nguyen',
  },
  {
    id: 'dia-nha-rong',
    kind: 'mix',
    minLevel: 3,
    sgkUnit: 'tay-nguyen',
    prompt: 'Nhà rông của đồng bào Tây Nguyên — vùng thả?',
    cardLabel: 'Nhà rông',
    region: 'tay-nguyen',
  },
  {
    id: 'dia-pleiku',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'tay-nguyen',
    prompt: 'Pleiku (Gia Lai) thuộc vùng nào?',
    cardLabel: 'Pleiku',
    region: 'tay-nguyen',
  },

  // —— Đồng bằng sông Cửu Long ——
  {
    id: 'dia-dbscl',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dbscl',
    prompt: 'Đồng bằng sông Cửu Long (ĐBSCL) thuộc vùng nào?',
    cardLabel: 'Đồng bằng Cửu Long',
    region: 'nam-bo',
  },
  {
    id: 'dia-can-tho',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dbscl',
    prompt: 'Thành phố Cần Thơ nằm ở vùng nào?',
    cardLabel: 'TP. Cần Thơ',
    region: 'nam-bo',
  },
  {
    id: 'dia-mekong',
    kind: 'dia',
    minLevel: 1,
    sgkUnit: 'dbscl',
    prompt: 'Sông Mekong chảy qua vùng nào trước khi ra biển?',
    cardLabel: 'Sông Mekong',
    region: 'nam-bo',
  },
  {
    id: 'dia-miet-vuon',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dbscl',
    prompt: 'Miệt vườn trái cây (sầu riêng, chôm chôm…) thuộc vùng?',
    cardLabel: 'Miệt vườn',
    region: 'nam-bo',
  },
  {
    id: 'dia-lua-dbscl',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dbscl',
    prompt: 'Vựa lúa, lúa nước ở đồng bằng phía Nam — vùng?',
    cardLabel: 'Vựa lúa ĐBSCL',
    region: 'nam-bo',
  },
  {
    id: 'dia-ca-tra-basa',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'dbscl',
    prompt: 'Nuôi cá tra, cá basa trên sông — vùng?',
    cardLabel: 'Nuôi cá sông',
    region: 'nam-bo',
  },
  {
    id: 'dia-rung-tram',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'dbscl',
    prompt: 'Rừng tràm, đất ngập mặn ở cửa sông Cửu Long — vùng?',
    cardLabel: 'Rừng tràm',
    region: 'nam-bo',
  },
  {
    id: 'dia-cho-noi',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'dbscl',
    prompt: 'Chợ nổi trên sông (Cái Răng, Cai Răng…) — vùng?',
    cardLabel: 'Chợ nổi',
    region: 'nam-bo',
  },

  // —— Lịch sử & văn hóa theo vùng ——
  {
    id: 'su-bach-dang',
    kind: 'su',
    minLevel: 1,
    sgkUnit: 'lich-su-vung',
    prompt: 'Sông Bạch Đằng (trận 938, 981, 1288) nằm ở miền nào?',
    cardLabel: 'Sông Bạch Đằng',
    region: 'bac-bo',
  },
  {
    id: 'su-thang-long',
    kind: 'su',
    minLevel: 1,
    sgkUnit: 'lich-su-vung',
    prompt: 'Kinh đô Thăng Long (nay là Hà Nội) thuộc vùng nào?',
    cardLabel: 'Kinh đô Thăng Long',
    region: 'bac-bo',
  },
  {
    id: 'su-hoa-lu',
    kind: 'su',
    minLevel: 2,
    sgkUnit: 'lich-su-vung',
    prompt: 'Kinh đô Hoa Lư (Ninh Bình) thuộc vùng nào?',
    cardLabel: 'Kinh đô Hoa Lư',
    region: 'bac-bo',
  },
  {
    id: 'su-chi-lang',
    kind: 'su',
    minLevel: 2,
    sgkUnit: 'lich-su-vung',
    prompt: 'Chiến thắng Chi Lăng (1427) ở vùng núi phía Bắc — thuộc?',
    cardLabel: 'Chi Lăng',
    region: 'bac-bo',
  },
  {
    id: 'su-dong-da',
    kind: 'su',
    minLevel: 3,
    sgkUnit: 'lich-su-vung',
    prompt: 'Chiến thắng Đống Đa (1789) diễn ra ở vùng nào?',
    cardLabel: 'Đống Đa (Hà Nội)',
    region: 'bac-bo',
  },
  {
    id: 'su-dien-bien-phu',
    kind: 'su',
    minLevel: 3,
    sgkUnit: 'lich-su-vung',
    prompt: 'Chiến thắng Điện Biên Phủ (1954) ở vùng núi phía Tây Bắc — thuộc?',
    cardLabel: 'Điện Biên Phủ',
    region: 'bac-bo',
  },
  {
    id: 'su-co-do-hue',
    kind: 'su',
    minLevel: 2,
    sgkUnit: 'lich-su-vung',
    prompt: 'Kinh thành Huế (triều Nguyễn) thuộc miền nào?',
    cardLabel: 'Kinh thành Huế',
    region: 'trung-bo',
  },
  {
    id: 'su-ngo-quyen',
    kind: 'su',
    minLevel: 2,
    sgkUnit: 'lich-su-vung',
    prompt: 'Ngô Quyền đánh quân Nam Hán trên sông Bạch Đằng — sông thuộc vùng?',
    cardLabel: 'Trận 938 (Bạch Đằng)',
    region: 'bac-bo',
  },

  // —— Bản đồ Hình 1 — quần đảo & đảo ——
  {
    id: 'dia-hoang-sa',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Quần đảo Hoàng Sa (TP Đà Nẵng – Việt Nam) nằm ở vùng nào trên bản đồ?',
    cardLabel: 'Quần đảo Hoàng Sa',
    region: 'hoang-sa',
  },
  {
    id: 'dia-truong-sa',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Quần đảo Trường Sa (tỉnh Khánh Hòa – Việt Nam) thuộc vùng nào?',
    cardLabel: 'Quần đảo Trường Sa',
    region: 'truong-sa',
  },
  {
    id: 'dia-phu-quoc',
    kind: 'dia',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Đảo Phú Quốc thuộc vùng nào trên bản đồ?',
    cardLabel: 'Đảo Phú Quốc',
    region: 'phu-quoc',
  },
  {
    id: 'dia-con-son',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Đảo Côn Sơn (Côn Đảo) nằm ở vùng nào?',
    cardLabel: 'Đảo Côn Sơn',
    region: 'con-son',
  },
  {
    id: 'dia-bach-long-vi',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Đảo Bạch Long Vĩ nằm ở vùng nào trên bản đồ?',
    cardLabel: 'Bạch Long Vĩ',
    region: 'bach-long-vi',
  },
  {
    id: 'dia-ly-son',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Đảo Lý Sơn (Quảng Ngãi) trên bản đồ Hình 1 — vùng thả?',
    cardLabel: 'Đảo Lý Sơn',
    region: 'ly-son',
  },
  {
    id: 'dia-con-co',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Đảo Cồn Cỏ (vịnh Bắc Bộ) — vùng thả?',
    cardLabel: 'Đảo Cồn Cỏ',
    region: 'con-co',
  },
  {
    id: 'dia-phu-quy',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Đảo Phú Quý (Bình Thuận) — vùng thả?',
    cardLabel: 'Đảo Phú Quý',
    region: 'phu-quy',
  },
  {
    id: 'dia-tho-chu',
    kind: 'dia',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Quần đảo Thổ Chu (Kiên Giang) — vùng thả?',
    cardLabel: 'QĐ. Thổ Chu',
    region: 'tho-chu',
  },
  {
    id: 'mix-hoang-sa-label',
    kind: 'mix',
    minLevel: 2,
    sgkUnit: 'ban-do-dao',
    prompt: 'Kéo nhãn đúng theo SGK: quần đảo Hoàng Sa',
    cardLabel: 'Hoàng Sa (Đà Nẵng)',
    region: 'hoang-sa',
  },
  {
    id: 'mix-truong-sa-khanh-hoa',
    kind: 'mix',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Trường Sa thuộc tỉnh Khánh Hòa — thả vào vùng đảo nào?',
    cardLabel: 'Trường Sa (Khánh Hòa)',
    region: 'truong-sa',
  },
  {
    id: 'mix-phu-quoc-kien-giang',
    kind: 'mix',
    minLevel: 3,
    sgkUnit: 'ban-do-dao',
    prompt: 'Phú Quốc thuộc tỉnh Kiên Giang — vùng thả?',
    cardLabel: 'Phú Quốc',
    region: 'phu-quoc',
  },
];
