import type { SpellingChallenge } from '../challengeTypes';
/** Bổ sung HK1/HK2 — 119 câu (ch / tr) */
export const LEVEL2_SUPPLEMENT: SpellingChallenge[] = [
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chăm', distractors: ['trăm', 'chăm chỉ', 'trăng'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trường', distractors: ['chường', 'trườn', 'chườn'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trình bày', distractors: ['chình bày', 'trình', 'chình'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'bác', distractors: ['trác', 'bách', 'trác sĩ'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trang nghiêm', distractors: ['chang nghiêm', 'trang', 'chang'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'tre', distractors: ['che', 'cre', 'tre xanh'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trồng', distractors: ['chồng', 'trồng cây', 'chồng cây'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trĩu', distractors: ['chĩu', 'trĩu quả', 'chĩu quả'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trong', distractors: ['chong', 'trong veo', 'chong veo'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trước', distractors: ['chước', 'trước cổng', 'chước cổng'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chạy', distractors: ['trạy', 'chạy bộ', 'trạy bộ'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trả lời', distractors: ['chả lời', 'trả', 'chả'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chân', distractors: ['trân', 'chân tay', 'trân tay'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chảo', distractors: ['trảo', 'chảo nấu', 'trảo nấu'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chưa', distractors: ['trưa', 'chưa xong', 'trưa xong'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chê', distractors: ['trê', 'chê bai', 'trê bai'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chép', distractors: ['trép', 'chép bài', 'trép bài'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chấm', distractors: ['trấm', 'chấm điểm', 'trấm điểm'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'nhảy', distractors: ['trảy', 'chảy', 'nhảy dây'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chan', distractors: ['tran', 'chan nước', 'tran nước'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chim', distractors: ['trim', 'chim chóc', 'trim chóc'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trời', distractors: ['chời', 'trời đẹp', 'chời đẹp'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chữ', distractors: ['trữ', 'chữ viết', 'trữ viết'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trẻ', distractors: ['chẻ', 'trẻ em', 'chẻ em'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chợ', distractors: ['trợ', 'chợ quê', 'trợ quê'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'truyện', distractors: ['chuyện', 'truyện cổ', 'chuyện cổ'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chính', distractors: ['trính', 'chính xác', 'trính xác'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trung thành', distractors: ['chung thành', 'trung', 'chung'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chung', distractors: ['trung', 'chung tay', 'trung tay'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trách nhiệm', distractors: ['chách nhiệm', 'trách', 'chách'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chọn', distractors: ['trọn', 'chọn lọc', 'trọn lọc'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trong lành', distractors: ['chong lành', 'trong', 'chong'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chăm sóc', distractors: ['trăm sóc', 'chăm', 'trăm'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'truyền thống', distractors: ['chuyền thống', 'truyền', 'chuyền'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chúc mừng', distractors: ['trúc mừng', 'chúc', 'trúc'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trân trọng', distractors: ['chân trọng', 'trân', 'chân'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chủ nhật', distractors: ['trủ nhật', 'chủ', 'trủ'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trưa nay', distractors: ['chưa nay', 'trưa', 'chưa'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chăn nuôi', distractors: ['trăn nuôi', 'chăn', 'trăn'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trồng trọt', distractors: ['chồng trọt', 'trồng', 'chồng'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chăm chỉ', distractors: ['trăm chỉ', 'chăm', 'trăm'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trí tuệ', distractors: ['chí tuệ', 'trí', 'chí'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chính trực', distractors: ['trính trực', 'chính', 'trính'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trung bình', distractors: ['chung bình', 'trung', 'chung'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chung sức', distractors: ['trung sức', 'chung', 'trung'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'truyền đạt', distractors: ['chuyền đạt', 'truyền', 'chuyền'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chủ động', distractors: ['trủ động', 'chủ', 'trủ'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trung kiên', distractors: ['chung kiên', 'trung', 'chung'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trí nhớ', distractors: ['chí nhớ', 'trí', 'chí'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trách', distractors: ['chách', 'trach', 'chach'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trốn', distractors: ['chốn', 'tron', 'chon'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trúc', distractors: ['chúc', 'truc', 'chuc'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trượt', distractors: ['chượt', 'truot', 'chuot'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trượng', distractors: ['chượng', 'truong', 'chuong'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'truyền', distractors: ['chuyền', 'truyen', 'chuyen'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trừng phạt', distractors: ['chừng phạt', 'trung phat', 'chung phat'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trường', distractors: ['chường', 'trườn', 'chườn'], hint: 'ch / tr' },
  { before: 'Em viết chữ ', after: '.', answer: 'trình bày', distractors: ['chình bày', 'trình', 'chình'], hint: 'ch / tr' },
  { before: 'Câu văn có từ ', after: ' rất hay.', answer: 'bác', distractors: ['trác', 'bách', 'trác sĩ'], hint: 'ch / tr' },
  { before: 'Bạn Nam đọc to từ ', after: '.', answer: 'trang nghiêm', distractors: ['chang nghiêm', 'trang', 'chang'], hint: 'ch / tr' },
  { before: 'Trong bài tập có từ ', after: '.', answer: 'tre', distractors: ['che', 'cre', 'tre xanh'], hint: 'ch / tr' },
  { before: 'Cô giáo hướng dẫn viết ', after: '.', answer: 'trồng', distractors: ['chồng', 'trồng cây', 'chồng cây'], hint: 'ch / tr' },
  { before: 'Sách giáo khoa có từ ', after: '.', answer: 'trĩu', distractors: ['chĩu', 'trĩu quả', 'chĩu quả'], hint: 'ch / tr' },
  { before: 'Em chọn từ ', after: ' cho đúng.', answer: 'trong', distractors: ['chong', 'trong veo', 'chong veo'], hint: 'ch / tr' },
  { before: 'Đoạn thơ có chữ ', after: ' rất đẹp.', answer: 'trước', distractors: ['chước', 'trước cổng', 'chước cổng'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trả lời', distractors: ['chả lời', 'trả', 'chả'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chân', distractors: ['trân', 'chân tay', 'trân tay'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chảo', distractors: ['trảo', 'chảo nấu', 'trảo nấu'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chưa', distractors: ['trưa', 'chưa xong', 'trưa xong'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chê', distractors: ['trê', 'chê bai', 'trê bai'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chép', distractors: ['trép', 'chép bài', 'trép bài'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chấm', distractors: ['trấm', 'chấm điểm', 'trấm điểm'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'nhảy', distractors: ['trảy', 'chảy', 'nhảy dây'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chan', distractors: ['tran', 'chan nước', 'tran nước'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chim', distractors: ['trim', 'chim chóc', 'trim chóc'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trời', distractors: ['chời', 'trời đẹp', 'chời đẹp'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chữ', distractors: ['trữ', 'chữ viết', 'trữ viết'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trẻ', distractors: ['chẻ', 'trẻ em', 'chẻ em'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chợ', distractors: ['trợ', 'chợ quê', 'trợ quê'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'truyện', distractors: ['chuyện', 'truyện cổ', 'chuyện cổ'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chính', distractors: ['trính', 'chính xác', 'trính xác'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trung thành', distractors: ['chung thành', 'trung', 'chung'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chung', distractors: ['trung', 'chung tay', 'trung tay'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trách nhiệm', distractors: ['chách nhiệm', 'trách', 'chách'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chọn', distractors: ['trọn', 'chọn lọc', 'trọn lọc'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trong lành', distractors: ['chong lành', 'trong', 'chong'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chăm sóc', distractors: ['trăm sóc', 'chăm', 'trăm'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'truyền thống', distractors: ['chuyền thống', 'truyền', 'chuyền'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chúc mừng', distractors: ['trúc mừng', 'chúc', 'trúc'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trân trọng', distractors: ['chân trọng', 'trân', 'chân'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chủ nhật', distractors: ['trủ nhật', 'chủ', 'trủ'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trưa nay', distractors: ['chưa nay', 'trưa', 'chưa'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chăn nuôi', distractors: ['trăn nuôi', 'chăn', 'trăn'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trồng trọt', distractors: ['chồng trọt', 'trồng', 'chồng'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chăm chỉ', distractors: ['trăm chỉ', 'chăm', 'trăm'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trí tuệ', distractors: ['chí tuệ', 'trí', 'chí'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chính trực', distractors: ['trính trực', 'chính', 'trính'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trung bình', distractors: ['chung bình', 'trung', 'chung'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chung sức', distractors: ['trung sức', 'chung', 'trung'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'truyền đạt', distractors: ['chuyền đạt', 'truyền', 'chuyền'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chủ động', distractors: ['trủ động', 'chủ', 'trủ'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trung kiên', distractors: ['chung kiên', 'trung', 'chung'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trí nhớ', distractors: ['chí nhớ', 'trí', 'chí'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trách', distractors: ['chách', 'trach', 'chach'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trốn', distractors: ['chốn', 'tron', 'chon'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trúc', distractors: ['chúc', 'truc', 'chuc'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trượt', distractors: ['chượt', 'truot', 'chuot'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trượng', distractors: ['chượng', 'truong', 'chuong'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'truyền', distractors: ['chuyền', 'truyen', 'chuyen'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trừng phạt', distractors: ['chừng phạt', 'trung phat', 'chung phat'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chăm', distractors: ['trăm', 'chăm chỉ', 'trăng'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'bác', distractors: ['trác', 'bách', 'trác sĩ'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trang nghiêm', distractors: ['chang nghiêm', 'trang', 'chang'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'tre', distractors: ['che', 'cre', 'tre xanh'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trồng', distractors: ['chồng', 'trồng cây', 'chồng cây'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trĩu', distractors: ['chĩu', 'trĩu quả', 'chĩu quả'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trong', distractors: ['chong', 'trong veo', 'chong veo'], hint: 'ch / tr' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'trước', distractors: ['chước', 'trước cổng', 'chước cổng'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'chạy', distractors: ['trạy', 'chạy bộ', 'trạy bộ'], hint: 'ch / tr' },
];
