import type { SpellingChallenge } from '../challengeTypes';
/** Bổ sung HK1/HK2 — 133 câu (d / gi / r / đ) */
export const LEVEL3_SUPPLEMENT: SpellingChallenge[] = [
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đại', distractors: ['dại', 'giải', 'rại'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'biết', distractors: ['diet', 'riet', 'giet'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'chảy', distractors: ['trảy', 'giảy', 'rảy'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'chu đáo', distractors: ['tru đáo', 'giu đáo', 'riu đáo'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'trôi', distractors: ['chôi', 'giôi', 'rôi'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'kể', distractors: ['cể', 'gể', 'rể'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đi', distractors: ['ri', 'gi', 'di'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đỏ', distractors: ['rỏ', 'giỏ', 'dỏ'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'giỏi', distractors: ['dỏi', 'rỏi', 'giỏi giang'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'dễ', distractors: ['giễ', 'rễ', 'dễ làm'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'ra', distractors: ['da', 'gra', 'ra sân'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đẹp', distractors: ['rẹp', 'giẹp', 'dẹp'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đứng', distractors: ['rứng', 'giứng', 'dứng'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đọc', distractors: ['rọc', 'giọc', 'dọc'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đúng', distractors: ['rúng', 'giúng', 'dúng'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'điểm', distractors: ['riểm', 'giểm', 'diểm'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đạt', distractors: ['rạt', 'giạt', 'dạt'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đều', distractors: ['rều', 'giều', 'dều'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đặt', distractors: ['rặt', 'giặt', 'dặt'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đổi', distractors: ['rổi', 'giổi', 'dổi'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đợi', distractors: ['rợi', 'giợi', 'dợi'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đá', distractors: ['rá', 'giá', 'dá'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đầy', distractors: ['rầy', 'giầy', 'dầy'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đủ', distractors: ['rủ', 'giủ', 'dủ'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đưa', distractors: ['rưa', 'giưa', 'dưa'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đón', distractors: ['rón', 'gión', 'dón'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đạp', distractors: ['ráp', 'giáp', 'dáp'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đánh', distractors: ['ránh', 'giánh', 'dánh'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đỡ', distractors: ['rỡ', 'giỡ', 'dỡ'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đồng', distractors: ['rồng', 'giồng', 'dồng'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đất', distractors: ['rất', 'giất', 'dất'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đường', distractors: ['rường', 'giường', 'dường'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đội', distractors: ['rội', 'giội', 'dội'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'động', distractors: ['rộng', 'giộng', 'dộng'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đoàn', distractors: ['roàn', 'gioàn', 'doàn'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đoạt', distractors: ['roạt', 'gioạt', 'doạt'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đoạn', distractors: ['roạn', 'gioạn', 'doạn'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đo lường', distractors: ['ro lường', 'gio lường', 'do lường'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đoàn kết', distractors: ['roàn kết', 'gioàn kết', 'doàn kết'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đoàn viên', distractors: ['roàn viên', 'gioàn viên', 'doàn viên'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lá', distractors: ['ná', 'la', 'na'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'làm', distractors: ['nàm', 'lam', 'nam'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lúa', distractors: ['núa', 'lua', 'nua'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lợn', distractors: ['nợn', 'lon', 'non'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lời', distractors: ['nời', 'loi', 'noi'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lạ', distractors: ['nạ', 'la', 'na'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lòng', distractors: ['nòng', 'long', 'nong'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lấy', distractors: ['nấy', 'lay', 'nay'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lắng', distractors: ['nắng', 'lang', 'nang'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lặng', distractors: ['nặng', 'lang', 'nang'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lười', distractors: ['nười', 'luoi', 'nuoi'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lướt', distractors: ['nướt', 'luot', 'nuot'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'loài', distractors: ['noài', 'loai', 'noai'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lối', distractors: ['nối', 'loi', 'noi'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lội', distractors: ['nội', 'loi', 'noi'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lơ', distractors: ['nơ', 'lo', 'no'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lơ đãng', distractors: ['nơ đãng', 'lơ lửng', 'nơ lửng'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lao động', distractors: ['nao động', 'lao', 'nao'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lạnh', distractors: ['nạnh', 'lanh', 'nanh'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lấp lánh', distractors: ['nấp lánh', 'lap lanh', 'nap nanh'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lần', distractors: ['nần', 'lan', 'nan'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lẫn', distractors: ['nẫn', 'lan', 'nan'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lập', distractors: ['nập', 'lap', 'nap'], hint: 'd / gi / r / đ' },
  { before: 'Em viết chữ ', after: '.', answer: 'đại', distractors: ['dại', 'giải', 'rại'], hint: 'd / gi / r / đ' },
  { before: 'Câu văn có từ ', after: ' rất hay.', answer: 'biết', distractors: ['diet', 'riet', 'giet'], hint: 'd / gi / r / đ' },
  { before: 'Bạn Nam đọc to từ ', after: '.', answer: 'chảy', distractors: ['trảy', 'giảy', 'rảy'], hint: 'd / gi / r / đ' },
  { before: 'Trong bài tập có từ ', after: '.', answer: 'chu đáo', distractors: ['tru đáo', 'giu đáo', 'riu đáo'], hint: 'd / gi / r / đ' },
  { before: 'Cô giáo hướng dẫn viết ', after: '.', answer: 'trôi', distractors: ['chôi', 'giôi', 'rôi'], hint: 'd / gi / r / đ' },
  { before: 'Sách giáo khoa có từ ', after: '.', answer: 'kể', distractors: ['cể', 'gể', 'rể'], hint: 'd / gi / r / đ' },
  { before: 'Em chọn từ ', after: ' cho đúng.', answer: 'đi', distractors: ['ri', 'gi', 'di'], hint: 'd / gi / r / đ' },
  { before: 'Đoạn thơ có chữ ', after: ' rất đẹp.', answer: 'đỏ', distractors: ['rỏ', 'giỏ', 'dỏ'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'dễ', distractors: ['giễ', 'rễ', 'dễ làm'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'ra', distractors: ['da', 'gra', 'ra sân'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đẹp', distractors: ['rẹp', 'giẹp', 'dẹp'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đứng', distractors: ['rứng', 'giứng', 'dứng'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đọc', distractors: ['rọc', 'giọc', 'dọc'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đúng', distractors: ['rúng', 'giúng', 'dúng'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'điểm', distractors: ['riểm', 'giểm', 'diểm'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đạt', distractors: ['rạt', 'giạt', 'dạt'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đều', distractors: ['rều', 'giều', 'dều'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đặt', distractors: ['rặt', 'giặt', 'dặt'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đổi', distractors: ['rổi', 'giổi', 'dổi'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đợi', distractors: ['rợi', 'giợi', 'dợi'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đá', distractors: ['rá', 'giá', 'dá'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đầy', distractors: ['rầy', 'giầy', 'dầy'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đủ', distractors: ['rủ', 'giủ', 'dủ'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đưa', distractors: ['rưa', 'giưa', 'dưa'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đón', distractors: ['rón', 'gión', 'dón'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đạp', distractors: ['ráp', 'giáp', 'dáp'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đánh', distractors: ['ránh', 'giánh', 'dánh'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đỡ', distractors: ['rỡ', 'giỡ', 'dỡ'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đồng', distractors: ['rồng', 'giồng', 'dồng'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đất', distractors: ['rất', 'giất', 'dất'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đường', distractors: ['rường', 'giường', 'dường'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đội', distractors: ['rội', 'giội', 'dội'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'động', distractors: ['rộng', 'giộng', 'dộng'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đoàn', distractors: ['roàn', 'gioàn', 'doàn'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đoạt', distractors: ['roạt', 'gioạt', 'doạt'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đoạn', distractors: ['roạn', 'gioạn', 'doạn'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đo lường', distractors: ['ro lường', 'gio lường', 'do lường'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đoàn kết', distractors: ['roàn kết', 'gioàn kết', 'doàn kết'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đoàn viên', distractors: ['roàn viên', 'gioàn viên', 'doàn viên'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lá', distractors: ['ná', 'la', 'na'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'làm', distractors: ['nàm', 'lam', 'nam'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lúa', distractors: ['núa', 'lua', 'nua'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lợn', distractors: ['nợn', 'lon', 'non'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lời', distractors: ['nời', 'loi', 'noi'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lạ', distractors: ['nạ', 'la', 'na'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lòng', distractors: ['nòng', 'long', 'nong'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lấy', distractors: ['nấy', 'lay', 'nay'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lắng', distractors: ['nắng', 'lang', 'nang'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lặng', distractors: ['nặng', 'lang', 'nang'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lười', distractors: ['nười', 'luoi', 'nuoi'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lướt', distractors: ['nướt', 'luot', 'nuot'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'loài', distractors: ['noài', 'loai', 'noai'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lối', distractors: ['nối', 'loi', 'noi'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lội', distractors: ['nội', 'loi', 'noi'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lơ', distractors: ['nơ', 'lo', 'no'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lơ đãng', distractors: ['nơ đãng', 'lơ lửng', 'nơ lửng'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lao động', distractors: ['nao động', 'lao', 'nao'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lạnh', distractors: ['nạnh', 'lanh', 'nanh'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lấp lánh', distractors: ['nấp lánh', 'lap lanh', 'nap nanh'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lần', distractors: ['nần', 'lan', 'nan'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'lẫn', distractors: ['nẫn', 'lan', 'nan'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'lập', distractors: ['nập', 'lap', 'nap'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'biết', distractors: ['diet', 'riet', 'giet'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'chảy', distractors: ['trảy', 'giảy', 'rảy'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'chu đáo', distractors: ['tru đáo', 'giu đáo', 'riu đáo'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'trôi', distractors: ['chôi', 'giôi', 'rôi'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'kể', distractors: ['cể', 'gể', 'rể'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'đi', distractors: ['ri', 'gi', 'di'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'đỏ', distractors: ['rỏ', 'giỏ', 'dỏ'], hint: 'd / gi / r / đ' },
  { before: 'Việc này rất ', after: '.', answer: 'giỏi', distractors: ['dỏi', 'rỏi', 'giỏi giang'], hint: 'd / gi / r / đ' },
];
