import type { SpellingChallenge } from '../challengeTypes';

/** Danh hiệu 3 — phân biệt d / gi / r / đ (60 câu, lớp 4) */
export const LEVEL3_BANK: SpellingChallenge[] = [
  { before: 'Bác Hồ là vị lãnh tụ vĩ ', after: '.', answer: 'đại', distractors: ['dại', 'giải', 'rại'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' ơn thầy cô.', answer: 'biết', distractors: ['diet', 'riet', 'giet'], hint: 'd / gi / r / đ' },
  { before: 'Dòng sông ', after: ' qua làng.', answer: 'chảy', distractors: ['trảy', 'giảy', 'rảy'], hint: 'd / gi / r / đ' },
  { before: 'Bạn ấy rất ', after: ' lòng với mọi người.', answer: 'chu đáo', distractors: ['tru đáo', 'giu đáo', 'riu đáo'], hint: 'd / gi / r / đ' },
  { before: 'Chiếc thuyền ', after: ' trên sông.', answer: 'trôi', distractors: ['chôi', 'giôi', 'rôi'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' chuyện cho bạn nghe.', answer: 'kể', distractors: ['cể', 'gể', 'rể'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' học cùng bạn.', answer: 'đi', distractors: ['ri', 'gi', 'di'], hint: 'd / gi / r / đ' },
  { before: 'Mặt trời ', after: ' sáng.', answer: 'đỏ', distractors: ['rỏ', 'giỏ', 'dỏ'], hint: 'd / gi / r / đ' },
  { before: 'Bạn Nam rất ', after: ' học.', answer: 'giỏi', distractors: ['dỏi', 'rỏi', 'giỏi giang'], hint: 'd / gi / r / đ' },
  { before: 'Công việc này rất ', after: '.', answer: 'dễ', distractors: ['giễ', 'rễ', 'dễ làm'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' ra sân chơi.', answer: 'ra', distractors: ['da', 'gra', 'ra sân'], hint: 'd / gi / r / đ' },
  { before: 'Bố em ', after: ' xe đạp đi làm.', answer: 'đạp', distractors: ['rạp', 'giạp', 'dạp'], hint: 'd / gi / r / đ' },
  { before: 'Hoa phượng nở ', after: '.', answer: 'đỏ', distractors: ['rỏ', 'giỏ', 'dỏ'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' bài tập đầy đủ.', answer: 'làm', distractors: ['làm', 'ràm', 'giàm'], hint: 'd / gi / r / đ' },
  { before: 'Bạn ấy ', after: ' điểm cao.', answer: 'đạt', distractors: ['rạt', 'giạt', 'dạt'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' mũ khi trời lạnh.', answer: 'đội', distractors: ['rội', 'giội', 'dội'], hint: 'd / gi / r / đ' },
  { before: 'Cô giáo ', after: ' em đọc bài.', answer: 'dạy', distractors: ['rạy', 'giạy', 'dạy bảo'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' ơn bố mẹ.', answer: 'biết', distractors: ['diet', 'riet', 'giet'], hint: 'd / gi / r / đ' },
  { before: 'Dòng kênh ', after: ' nước trong veo.', answer: 'dẫn', distractors: ['rẫn', 'giẫn', 'dẫn nước'], hint: 'd / gi / r / đ' },
  { before: 'Bạn em rất ', after: ' dạ.', answer: 'hiền', distractors: ['hiền', 'riền', 'giền'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' tay chào cờ.', answer: 'giơ', distractors: ['dơ', 'rơ', 'giơ tay'], hint: 'd / gi / r / đ' },
  { before: 'Bác ấy ', after: ' chuyện rất hay.', answer: 'kể', distractors: ['cể', 'gể', 'rể'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' quyển vở vào cặp.', answer: 'để', distractors: ['rể', 'gể', 'dể'], hint: 'd / gi / r / đ' },
  { before: 'Trời mưa ', after: ' rất to.', answer: 'dữ', distractors: ['rữ', 'giữ', 'dữ dội'], hint: 'd / gi / r / đ' },
  { before: 'Bạn Nam ', after: ' bài toán hay.', answer: 'giải', distractors: ['dải', 'rải', 'giải đề'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' mắt nhìn tranh.', answer: 'dán', distractors: ['rán', 'gián', 'dán mắt'], hint: 'd / gi / r / đ' },
  { before: 'Cây cam ', after: ' quả chín vàng.', answer: 'ra', distractors: ['da', 'gra', 'ra quả'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' bài hát trước lớp.', answer: 'hát', distractors: ['rát', 'giát', 'dát'], hint: 'd / gi / r / đ' },
  { before: 'Bố em ', after: ' nước vào bình.', answer: 'đổ', distractors: ['rổ', 'giổ', 'dổ'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' đứng ngay ngắn.', answer: 'đứng', distractors: ['rứng', 'giứng', 'dứng'], hint: 'd / gi / r / đ' },
  { before: 'Bạn ấy ', after: ' lời rất lịch sự.', answer: 'nói', distractors: ['nói', 'rói', 'giới'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' quà cho bà.', answer: 'tặng', distractors: ['tặng', 'rặng', 'giặng'], hint: 'd / gi / r / đ' },
  { before: 'Cô giáo ', after: ' em viết đẹp.', answer: 'khen', distractors: ['khen', 'rhen', 'ghen'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' nhà sau giờ học.', answer: 'về', distractors: ['về', 'rề', 'gề'], hint: 'd / gi / r / đ' },
  { before: 'Bác Hồ ', after: ' dạy chúng em.', answer: 'dạy', distractors: ['rạy', 'giạy', 'dạy bảo'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' tay rửa bát.', answer: 'dưới', distractors: ['rưới', 'giới', 'dưới vòi'], hint: 'd / gi / r / đ' },
  { before: 'Bạn em ', after: ' bài rất cẩn thận.', answer: 'làm', distractors: ['ràm', 'giàm', 'làm bài'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' lòng yêu quê hương.', answer: 'dạt', distractors: ['rạt', 'giạt', 'dạt dào'], hint: 'd / gi / r / đ' },
  { before: 'Nước sông ', after: ' xiết.', answer: 'dâng', distractors: ['râng', 'giâng', 'dâng cao'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' bút viết chữ.', answer: 'cầm', distractors: ['cầm', 'rầm', 'giầm'], hint: 'd / gi / r / đ' },
  { before: 'Bố em ', after: ' cửa trước khi đi.', answer: 'đóng', distractors: ['róng', 'gióng', 'dóng'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' mắt nhìn bản đồ.', answer: 'dõi', distractors: ['rõi', 'giõi', 'dõi theo'], hint: 'd / gi / r / đ' },
  { before: 'Bạn Nam ', after: ' điểm thi cao.', answer: 'đạt', distractors: ['rạt', 'giạt', 'dạt'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' hoa lên bàn thờ.', answer: 'dâng', distractors: ['râng', 'giâng', 'dâng hoa'], hint: 'd / gi / r / đ' },
  { before: 'Cây tre ', after: ' lá xanh.', answer: 'đuốc', distractors: ['ruốc', 'giuốc', 'duốc'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' giấy gói quà.', answer: 'gói', distractors: ['gói', 'rói', 'dói'], hint: 'd / gi / r / đ' },
  { before: 'Bác ấy ', after: ' đường cho khách.', answer: 'dẫn', distractors: ['rẫn', 'giẫn', 'dẫn đường'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' bài thơ Bác Hồ.', answer: 'đọc', distractors: ['rọc', 'giọc', 'dọc'], hint: 'd / gi / r / đ' },
  { before: 'Bạn ấy ', after: ' rất thật thà.', answer: 'thật', distractors: ['thật', 'rật', 'giật'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' nước cho cây.', answer: 'tưới', distractors: ['tưới', 'rưới', 'giới'], hint: 'd / gi / r / đ' },
  { before: 'Lá cờ ', after: ' bay trong gió.', answer: 'đỏ', distractors: ['rỏ', 'giỏ', 'dỏ'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' quyết học giỏi.', answer: 'quyết', distractors: ['quyết', 'ruyết', 'guyết'], hint: 'd / gi / r / đ' },
  { before: 'Bố em ', after: ' lúa trên cánh đồng.', answer: 'gặt', distractors: ['rặt', 'giặt', 'dặt'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' lời khi nhận quà.', answer: 'cảm ơn', distractors: ['cảm ơn', 'rảm ơn', 'giảm ơn'], hint: 'd / gi / r / đ' },
  { before: 'Cô giáo ', after: ' em làm bài.', answer: 'chấm', distractors: ['chấm', 'rấm', 'giấm'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' đèn khi trời tối.', answer: 'bật', distractors: ['bật', 'rật', 'giật'], hint: 'd / gi / r / đ' },
  { before: 'Bạn em ', after: ' quả cam ngọt.', answer: 'gọt', distractors: ['gọt', 'rọt', 'dọt'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' mình trên ghế.', answer: 'ngồi', distractors: ['ngồi', 'rồi', 'giồi'], hint: 'd / gi / r / đ' },
  { before: 'Dòng sông ', after: ' qua thôn.', answer: 'chảy', distractors: ['trảy', 'giảy', 'rảy'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' quyển sách hay.', answer: 'đọc', distractors: ['rọc', 'giọc', 'dọc'], hint: 'd / gi / r / đ' },
  { before: 'Bác Hồ ', after: ' thương nhân dân.', answer: 'yêu', distractors: ['yêu', 'rêu', 'giêu'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' bạn khi bạn ốm.', answer: 'thăm', distractors: ['thăm', 'răm', 'giăm'], hint: 'd / gi / r / đ' },
  { before: 'Bạn Nam ', after: ' bài rất nhanh.', answer: 'làm', distractors: ['ràm', 'giàm', 'làm bài'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' đáp án đúng.', answer: 'điền', distractors: ['riền', 'giền', 'diền'], hint: 'd / gi / r / đ' },
  { before: 'Cây hoa ', after: ' sắc thật đẹp.', answer: 'rực', distractors: ['dực', 'giực', 'rực rỡ'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' lời hứa với mẹ.', answer: 'giữ', distractors: ['dữ', 'rữ', 'giữ lời'], hint: 'd / gi / r / đ' },
  { before: 'Bố em ', after: ' nhà sạch sẽ.', answer: 'dọn', distractors: ['rọn', 'gọn', 'dọn nhà'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' nét chữ đẹp.', answer: 'rèn', distractors: ['dèn', 'gièn', 'rèn luyện'], hint: 'd / gi / r / đ' },
  { before: 'Chúng em ', after: ' bảo vệ môi trường.', answer: 'giữ', distractors: ['dữ', 'rữ', 'giữ gìn'], hint: 'd / gi / r / đ' },
  { before: 'Bạn ấy ', after: ' đường về nhà.', answer: 'dẫn', distractors: ['rẫn', 'giẫn', 'dẫn đường'], hint: 'd / gi / r / đ' },
  { before: 'Em ', after: ' quà tặng cô.', answer: 'tặng', distractors: ['rặng', 'giặng', 'tặng quà'], hint: 'd / gi / r / đ' },
];
