import type { SpellingChallenge } from '../challengeTypes';

/** Danh hiệu 2 — phân biệt ch / tr (60 câu, lớp 4) */
export const LEVEL2_BANK: SpellingChallenge[] = [
  { before: 'Bạn Nam học rất ', after: '.', answer: 'chăm', distractors: ['trăm', 'chăm chỉ', 'trăng'], hint: 'ch / tr' },
  { before: 'Chúng em đến ', after: ' học.', answer: 'trường', distractors: ['chường', 'trườn', 'chườn'], hint: 'ch / tr' },
  { before: 'Cô giáo ', after: ' bài rất hay.', answer: 'trình bày', distractors: ['chình bày', 'trình', 'chình'], hint: 'ch / tr' },
  { before: 'Bố em là ', after: ' sĩ.', answer: 'bác', distractors: ['trác', 'bách', 'trác sĩ'], hint: 'ch / tr' },
  { before: 'Chúng em đứng ', after: ' hát Quốc ca.', answer: 'trang nghiêm', distractors: ['chang nghiêm', 'trang', 'chang'], hint: 'ch / tr' },
  { before: 'Cây ', after: ' xanh tốt trong vườn.', answer: 'tre', distractors: ['che', 'tre xanh', 'cre'], hint: 'ch / tr' },
  { before: 'Bố em ', after: ' ngô trên ruộng.', answer: 'trồng', distractors: ['chồng', 'trồng cây', 'chồng cây'], hint: 'ch / tr' },
  { before: 'Cây cam ', after: ' nhiều quả.', answer: 'trĩu', distractors: ['chĩu', 'trĩu quả', 'chĩu quả'], hint: 'ch / tr' },
  { before: 'Nước giếng rất ', after: '.', answer: 'trong', distractors: ['chong', 'trong veo', 'chong veo'], hint: 'ch / tr' },
  { before: 'Em đứng ', after: ' cổng trường.', answer: 'trước', distractors: ['chước', 'trước cổng', 'chước cổng'], hint: 'ch / tr' },
  { before: 'Bạn ấy ', after: ' rất nhanh.', answer: 'chạy', distractors: ['trạy', 'chạy bộ', 'trạy bộ'], hint: 'ch / tr' },
  { before: 'Em ', after: ' lời câu hỏi.', answer: 'trả lời', distractors: ['chả lời', 'trả', 'chả'], hint: 'ch / tr' },
  { before: 'Đôi ', after: ' em đi giày.', answer: 'chân', distractors: ['trân', 'chân tay', 'trân tay'], hint: 'ch / tr' },
  { before: 'Mẹ nấu canh trong ', after: '.', answer: 'chảo', distractors: ['trảo', 'chảo nấu', 'trảo nấu'], hint: 'ch / tr' },
  { before: 'Em ', after: ' làm bài tập.', answer: 'chưa', distractors: ['trưa', 'chưa xong', 'trưa xong'], hint: 'ch / tr' },
  { before: 'Cô giáo ', after: ' bạn viết sai.', answer: 'chê', distractors: ['trê', 'chê bai', 'trê bai'], hint: 'ch / tr' },
  { before: 'Bạn ấy ', after: ' bài vào vở.', answer: 'chép', distractors: ['trép', 'chép bài', 'trép bài'], hint: 'ch / tr' },
  { before: 'Cô giáo ', after: ' bài kiểm tra.', answer: 'chấm', distractors: ['trấm', 'chấm điểm', 'trấm điểm'], hint: 'ch / tr' },
  { before: 'Chúng em ', after: ' dây ở sân.', answer: 'nhảy', distractors: ['trảy', 'chảy', 'nhảy dây'], hint: 'ch / tr' },
  { before: 'Bố em ', after: ' xe máy đi làm.', answer: 'chạy', distractors: ['trạy', 'chạy xe', 'trạy xe'], hint: 'ch / tr' },
  { before: 'Em ', after: ' nước cho bạn.', answer: 'chan', distractors: ['tran', 'chan nước', 'tran nước'], hint: 'ch / tr' },
  { before: 'Bác bảo vệ ', after: ' cổng trường.', answer: 'trông', distractors: ['chông', 'trông coi', 'chông coi'], hint: 'ch / tr' },
  { before: 'Em ', after: ' mắt nhìn bảng.', answer: 'chăm', distractors: ['trăm', 'chăm chú', 'trăm chú'], hint: 'ch / tr' },
  { before: 'Cô giáo khen em ', after: '.', answer: 'chăm chỉ', distractors: ['trăm chỉ', 'chăm', 'trăm'], hint: 'ch / tr' },
  { before: 'Bố em sửa ', after: ' điện cửa.', answer: 'chuông', distractors: ['truông', 'chương', 'chuông cửa'], hint: 'ch / tr' },
  { before: 'Em ', after: ' bạn khi bạn ngã.', answer: 'chở', distractors: ['trở', 'chở bạn', 'trở bạn'], hint: 'ch / tr' },
  { before: 'Bạn ấy ', after: ' tiếng hát hay.', answer: 'trầm', distractors: ['chầm', 'trầm ấm', 'chầm ấm'], hint: 'ch / tr' },
  { before: 'Em ', after: ' lại quyển vở.', answer: 'chọn', distractors: ['trọn', 'chọn sách', 'trọn sách'], hint: 'ch / tr' },
  { before: 'Lá ', after: ' rụng mùa thu.', answer: 'trầu', distractors: ['chầu', 'trầu cau', 'chầu cau'], hint: 'ch / tr' },
  { before: 'Em ', after: ' mắt ngắm cảnh.', answer: 'trầm', distractors: ['chầm', 'trầm ngâm', 'chầm ngâm'], hint: 'ch / tr' },
  { before: 'Em ', after: ' tay lau bảng.', answer: 'chùi', distractors: ['trùi', 'chùi bảng', 'trùi bảng'], hint: 'ch / tr' },
  { before: 'Lớp em ', after: ' ảnh tập thể.', answer: 'chụp', distractors: ['trụp', 'chụp ảnh', 'trụp ảnh'], hint: 'ch / tr' },
  { before: 'Em ', after: ' mũ khi trời nắng.', answer: 'che', distractors: ['tre', 'che nắng', 'tre nắng'], hint: 'ch / tr' },
  { before: 'Cây bàng ', after: ' lá mùa thu.', answer: 'trụi', distractors: ['chụi', 'trụi lá', 'chụi lá'], hint: 'ch / tr' },
  { before: 'Em ', after: ' lòng biết ơn.', answer: 'trân', distractors: ['chân', 'trân trọng', 'chân trọng'], hint: 'ch / tr' },
  { before: 'Bác ấy ', after: ' chuyện rất hay.', answer: 'kể', distractors: ['cể', 'trể', 'chể'], hint: 'ch / tr' },
  { before: 'Chúng em ', after: ' cây xanh.', answer: 'trồng', distractors: ['chồng', 'trồng cây', 'chồng cây'], hint: 'ch / tr' },
  { before: 'Bạn em ', after: ' rất thật thà.', answer: 'chân thật', distractors: ['trân thật', 'chân', 'trân'], hint: 'ch / tr' },
  { before: 'Em ', after: ' hàng cho mẹ.', answer: 'trông', distractors: ['chông', 'trông nom', 'chông nom'], hint: 'ch / tr' },
  { before: 'Cây ', after: ' cao giữa sân.', answer: 'tre', distractors: ['che', 'tre xanh', 'che xanh'], hint: 'ch / tr' },
  { before: 'Bạn Nam ', after: ' bài rất đúng.', answer: 'chép', distractors: ['trép', 'chép bài', 'trép bài'], hint: 'ch / tr' },
  { before: 'Em ', after: ' sách vào cặp.', answer: 'cất', distractors: ['trất', 'chất', 'cất sách'], hint: 'ch / tr' },
  { before: 'Chúng em ', after: ' vệ sinh lớp.', answer: 'trực', distractors: ['chực', 'trực nhật', 'chực nhật'], hint: 'ch / tr' },
  { before: 'Bạn ấy ', after: ' điểm cao.', answer: 'đạt', distractors: ['trạt', 'chạt', 'đạt điểm'], hint: 'ch / tr' },
  { before: 'Em ', after: ' lời khi được khen.', answer: 'cảm ơn', distractors: ['trảm ơn', 'chảm ơn', 'cảm ơn bạn'], hint: 'ch / tr' },
  { before: 'Câu chuyện rất ', after: '.', answer: 'thú vị', distractors: ['trú vị', 'chú vị', 'thú vị'], hint: 'ch / tr' },
  { before: 'Em ', after: ' thư cho ông.', answer: 'viết', distractors: ['triết', 'chiết', 'viết thư'], hint: 'ch / tr' },
  { before: 'Lớp em ', after: ' đi thăm viện bảo tàng.', answer: 'được', distractors: ['trược', 'chược', 'được đi'], hint: 'ch / tr' },
  { before: 'Bạn Nam ', after: ' đề toán.', answer: 'giải', distractors: ['trải', 'chải', 'giải đề'], hint: 'ch / tr' },
  { before: 'Chúng em ', after: ' hình lên giấy.', answer: 'tô', distractors: ['trô', 'chô', 'tô màu'], hint: 'ch / tr' },
  { before: 'Em ', after: ' ong bảo vệ cây.', answer: 'trồng', distractors: ['chồng', 'trồng cây', 'chồng cây'], hint: 'ch / tr' },
  { before: 'Bố em ', after: ' cá ở ao.', answer: 'câu', distractors: ['trâu', 'châu', 'câu cá'], hint: 'ch / tr' },
  { before: 'Sân trường rất ', after: '.', answer: 'rộng', distractors: ['trộng', 'chộng', 'rộng lớn'], hint: 'ch / tr' },
  { before: 'Chúng em ', after: ' tay bảo vệ môi trường.', answer: 'chung', distractors: ['trung', 'chung tay', 'trung tay'], hint: 'ch / tr' },
  { before: 'Em ', after: ' bài thơ trước lớp.', answer: 'đọc', distractors: ['trọc', 'chọc', 'đọc thuộc'], hint: 'ch / tr' },
  { before: 'Cô giáo ', after: ' em đọc to.', answer: 'cho', distractors: ['tro', 'cho', 'trô'], hint: 'ch / tr' },
  { before: 'Bạn em ', after: ' bài hát dân ca.', answer: 'thuộc', distractors: ['truộc', 'chuộc', 'thuộc bài'], hint: 'ch / tr' },
  { before: 'Em ', after: ' mũ trước khi về.', answer: 'đội', distractors: ['trội', 'chội', 'đội mũ'], hint: 'ch / tr' },
  { before: 'Lá cờ bay ', after: ' trong gió.', answer: 'phấp phới', distractors: ['trấp phới', 'chấp phới', 'phấp phới'], hint: 'ch / tr' },
  { before: 'Bạn ấy ', after: ' rất thông minh.', answer: 'thông minh', distractors: ['trông minh', 'chông minh', 'thông minh'], hint: 'ch / tr' },
  { before: 'Em ', after: ' lời hứa với thầy.', answer: 'giữ', distractors: ['trữ', 'chữ', 'giữ lời'], hint: 'ch / tr' },
  { before: 'Cây hoa ', after: ' thơm trong gió.', answer: 'trồng', distractors: ['chồng', 'trồng hoa', 'chồng hoa'], hint: 'ch / tr' },
  { before: 'Bác nông dân ', after: ' lúa.', answer: 'gặt', distractors: ['trặt', 'chặt', 'gặt lúa'], hint: 'ch / tr' },
  { before: 'Chúng em ', after: ' nhạc Quốc ca.', answer: 'hát', distractors: ['trát', 'chát', 'hát hay'], hint: 'ch / tr' },
  { before: 'Em ', after: ' quyển truyện hay.', answer: 'truyện', distractors: ['chuyện', 'truyện tranh', 'chuyện tranh'], hint: 'ch / tr' },
  { before: 'Bạn Nam rất ', after: ' thật.', answer: 'chính', distractors: ['trính', 'chính xác', 'trính xác'], hint: 'ch / tr' },
  { before: 'Em ', after: ' nước sôi vào ly.', answer: 'chan', distractors: ['tran', 'chan nước', 'tran nước'], hint: 'ch / tr' },
  { before: 'Cô giáo ', after: ' bài trên bảng.', answer: 'trình', distractors: ['chình', 'trình bày', 'chình bày'], hint: 'ch / tr' },
  { before: 'Bạn em ', after: ' đường về nhà.', answer: 'trông', distractors: ['chông', 'trông đường', 'chông đường'], hint: 'ch / tr' },
  { before: 'Em ', after: ' tay rửa sạch.', answer: 'chà', distractors: ['trà', 'chà xát', 'trà xát'], hint: 'ch / tr' },
  { before: 'Lớp em ', after: ' bài hát đồng ca.', answer: 'hát', distractors: ['trát', 'chát', 'hát hay'], hint: 'ch / tr' },
  { before: 'Bác Hồ ', after: ' dạy học sinh.', answer: 'dạy', distractors: ['trạy', 'chạy', 'dạy bảo'], hint: 'ch / tr' },
];
