import type { SpellingChallenge } from '../challengeTypes';
/** Bổ sung HK1/HK2 — 173 câu (s / x) */
export const LEVEL1_SUPPLEMENT: SpellingChallenge[] = [
  { before: 'Trên bầu trời có ', after: '.', answer: 'sao', distractors: ['xao', 'sau', 'xau'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xinh', distractors: ['sinh', 'xịn', 'sin'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sắn', distractors: ['xắn', 'sân', 'xân'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sóng', distractors: ['xóng', 'sông', 'xông'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sáng', distractors: ['xáng', 'san', 'xan'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'soạn', distractors: ['xoạn', 'soan', 'xoan'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sen', distractors: ['xen', 'san', 'xén'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sương', distractors: ['xương', 'sươn', 'xươn'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sung', distractors: ['xung', 'sum', 'xum'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sữa', distractors: ['xữa', 'sửa', 'xửa'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sưởi', distractors: ['xưởi', 'sưỡi', 'xưỡi'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sẻ', distractors: ['xẻ', 'sế', 'xế'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sơn', distractors: ['xơn', 'son', 'xon'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sút', distractors: ['xút', 'súc', 'xúc'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xuân', distractors: ['suân', 'xân', 'suân'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xanh', distractors: ['sanh', 'san', 'xan'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xúc', distractors: ['súc', 'súc động', 'xúc động'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xóm', distractors: ['sóm', 'xom', 'som'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xấu', distractors: ['sấu', 'xẩu', 'sẩu'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'siêng', distractors: ['xiêng', 'siêng năng', 'xiêng năng'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sàn', distractors: ['xàn', 'san', 'xach'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xưa', distractors: ['sưa', 'xừa', 'sưa kia'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xào', distractors: ['sào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sào', distractors: ['xào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xúm', distractors: ['súm', 'xum', 'sum'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sơ', distractors: ['xơ', 'so', 'xo'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xối', distractors: ['sối', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sát', distractors: ['xát', 'sat', 'xat'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'suối', distractors: ['xuối', 'suoi', 'xuoi'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sạch', distractors: ['xạch', 'sach', 'xach'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xót', distractors: ['sót', 'xot', 'sot'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sót', distractors: ['xót', 'sot', 'xot'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xén', distractors: ['sén', 'xen', 'sen'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xới', distractors: ['sới', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sới', distractors: ['xới', 'soi', 'xoi'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sán', distractors: ['xán', 'san', 'xan'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sưu tầm', distractors: ['xưu tầm', 'sưu', 'xưu'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xinh đẹp', distractors: ['sinh đẹp', 'xinh xắn', 'sinh xắn'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sư tử', distractors: ['xư tử', 'sư', 'xư'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xoa', distractors: ['soa', 'xoa đầu', 'soa đầu'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sao băng', distractors: ['xao băng', 'sao chổi', 'xao chổi'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sương mù', distractors: ['xương mù', 'sương mai', 'xương mai'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xum xếp', distractors: ['sum xếp', 'xum', 'sum'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sấm sét', distractors: ['xấm sét', 'sấm', 'xấm'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xao xuyến', distractors: ['sao xuyến', 'xao', 'sao'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sinh hoạt', distractors: ['xinh hoạt', 'sinh', 'xinh'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xung quanh', distractors: ['sung quanh', 'xung', 'sung'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sơ đồ', distractors: ['xơ đồ', 'sơ', 'xơ'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xung phong', distractors: ['sung phong', 'xung', 'sung'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sư phụ', distractors: ['xư phụ', 'sư', 'xư'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xung đột', distractors: ['sung đột', 'xung', 'sung'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sơ sinh', distractors: ['xơ sinh', 'sơ', 'xơ'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xung khắc', distractors: ['sung khắc', 'xung', 'sung'], hint: 's / x' },
  { before: 'Em viết chữ ', after: '.', answer: 'sao', distractors: ['xao', 'sau', 'xau'], hint: 's / x' },
  { before: 'Câu văn có từ ', after: ' rất hay.', answer: 'xinh', distractors: ['sinh', 'xịn', 'sin'], hint: 's / x' },
  { before: 'Bạn Nam đọc to từ ', after: '.', answer: 'sắn', distractors: ['xắn', 'sân', 'xân'], hint: 's / x' },
  { before: 'Trong bài tập có từ ', after: '.', answer: 'sóng', distractors: ['xóng', 'sông', 'xông'], hint: 's / x' },
  { before: 'Cô giáo hướng dẫn viết ', after: '.', answer: 'sáng', distractors: ['xáng', 'san', 'xan'], hint: 's / x' },
  { before: 'Sách giáo khoa có từ ', after: '.', answer: 'soạn', distractors: ['xoạn', 'soan', 'xoan'], hint: 's / x' },
  { before: 'Em chọn từ ', after: ' cho đúng.', answer: 'sen', distractors: ['xen', 'san', 'xén'], hint: 's / x' },
  { before: 'Đoạn thơ có chữ ', after: ' rất đẹp.', answer: 'sương', distractors: ['xương', 'sươn', 'xươn'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sung', distractors: ['xung', 'sum', 'xum'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sữa', distractors: ['xữa', 'sửa', 'xửa'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sưởi', distractors: ['xưởi', 'sưỡi', 'xưỡi'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sẻ', distractors: ['xẻ', 'sế', 'xế'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sơn', distractors: ['xơn', 'son', 'xon'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sút', distractors: ['xút', 'súc', 'xúc'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xuân', distractors: ['suân', 'xân', 'suân'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xanh', distractors: ['sanh', 'san', 'xan'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xúc', distractors: ['súc', 'súc động', 'xúc động'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xóm', distractors: ['sóm', 'xom', 'som'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xấu', distractors: ['sấu', 'xẩu', 'sẩu'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'siêng', distractors: ['xiêng', 'siêng năng', 'xiêng năng'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sàn', distractors: ['xàn', 'san', 'xach'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xưa', distractors: ['sưa', 'xừa', 'sưa kia'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xào', distractors: ['sào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sào', distractors: ['xào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xúm', distractors: ['súm', 'xum', 'sum'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sơ', distractors: ['xơ', 'so', 'xo'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xối', distractors: ['sối', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sát', distractors: ['xát', 'sat', 'xat'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'suối', distractors: ['xuối', 'suoi', 'xuoi'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sạch', distractors: ['xạch', 'sach', 'xach'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xót', distractors: ['sót', 'xot', 'sot'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sót', distractors: ['xót', 'sot', 'xot'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xén', distractors: ['sén', 'xen', 'sen'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xới', distractors: ['sới', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sới', distractors: ['xới', 'soi', 'xoi'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sán', distractors: ['xán', 'san', 'xan'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sưu tầm', distractors: ['xưu tầm', 'sưu', 'xưu'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xinh đẹp', distractors: ['sinh đẹp', 'xinh xắn', 'sinh xắn'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sư tử', distractors: ['xư tử', 'sư', 'xư'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xoa', distractors: ['soa', 'xoa đầu', 'soa đầu'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sao băng', distractors: ['xao băng', 'sao chổi', 'xao chổi'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sương mù', distractors: ['xương mù', 'sương mai', 'xương mai'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xum xếp', distractors: ['sum xếp', 'xum', 'sum'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sấm sét', distractors: ['xấm sét', 'sấm', 'xấm'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xao xuyến', distractors: ['sao xuyến', 'xao', 'sao'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sinh hoạt', distractors: ['xinh hoạt', 'sinh', 'xinh'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xung quanh', distractors: ['sung quanh', 'xung', 'sung'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sơ đồ', distractors: ['xơ đồ', 'sơ', 'xơ'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xung phong', distractors: ['sung phong', 'xung', 'sung'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sư phụ', distractors: ['xư phụ', 'sư', 'xư'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xung đột', distractors: ['sung đột', 'xung', 'sung'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sơ sinh', distractors: ['xơ sinh', 'sơ', 'xơ'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xung khắc', distractors: ['sung khắc', 'xung', 'sung'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xinh', distractors: ['sinh', 'xịn', 'sin'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sắn', distractors: ['xắn', 'sân', 'xân'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sóng', distractors: ['xóng', 'sông', 'xông'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sáng', distractors: ['xáng', 'san', 'xan'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'soạn', distractors: ['xoạn', 'soan', 'xoan'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sen', distractors: ['xen', 'san', 'xén'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sương', distractors: ['xương', 'sươn', 'xươn'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sung', distractors: ['xung', 'sum', 'xum'], hint: 's / x' },
  { before: 'Em viết chữ ', after: '.', answer: 'sữa', distractors: ['xữa', 'sửa', 'xửa'], hint: 's / x' },
  { before: 'Câu văn có từ ', after: ' rất hay.', answer: 'sưởi', distractors: ['xưởi', 'sưỡi', 'xưỡi'], hint: 's / x' },
  { before: 'Bạn Nam đọc to từ ', after: '.', answer: 'sẻ', distractors: ['xẻ', 'sế', 'xế'], hint: 's / x' },
  { before: 'Trong bài tập có từ ', after: '.', answer: 'sơn', distractors: ['xơn', 'son', 'xon'], hint: 's / x' },
  { before: 'Cô giáo hướng dẫn viết ', after: '.', answer: 'sút', distractors: ['xút', 'súc', 'xúc'], hint: 's / x' },
  { before: 'Sách giáo khoa có từ ', after: '.', answer: 'xuân', distractors: ['suân', 'xân', 'suân'], hint: 's / x' },
  { before: 'Em chọn từ ', after: ' cho đúng.', answer: 'xanh', distractors: ['sanh', 'san', 'xan'], hint: 's / x' },
  { before: 'Đoạn thơ có chữ ', after: ' rất đẹp.', answer: 'xúc', distractors: ['súc', 'súc động', 'xúc động'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'siêng', distractors: ['xiêng', 'siêng năng', 'xiêng năng'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sàn', distractors: ['xàn', 'san', 'xach'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xưa', distractors: ['sưa', 'xừa', 'sưa kia'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xào', distractors: ['sào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sào', distractors: ['xào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xúm', distractors: ['súm', 'xum', 'sum'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sơ', distractors: ['xơ', 'so', 'xo'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xối', distractors: ['sối', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sát', distractors: ['xát', 'sat', 'xat'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'suối', distractors: ['xuối', 'suoi', 'xuoi'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sạch', distractors: ['xạch', 'sach', 'xach'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xót', distractors: ['sót', 'xot', 'sot'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sót', distractors: ['xót', 'sot', 'xot'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xén', distractors: ['sén', 'xen', 'sen'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xới', distractors: ['sới', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sới', distractors: ['xới', 'soi', 'xoi'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sán', distractors: ['xán', 'san', 'xan'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sưu tầm', distractors: ['xưu tầm', 'sưu', 'xưu'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xinh đẹp', distractors: ['sinh đẹp', 'xinh xắn', 'sinh xắn'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sư tử', distractors: ['xư tử', 'sư', 'xư'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xoa', distractors: ['soa', 'xoa đầu', 'soa đầu'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sao băng', distractors: ['xao băng', 'sao chổi', 'xao chổi'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sương mù', distractors: ['xương mù', 'sương mai', 'xương mai'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xum xếp', distractors: ['sum xếp', 'xum', 'sum'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sấm sét', distractors: ['xấm sét', 'sấm', 'xấm'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xao xuyến', distractors: ['sao xuyến', 'xao', 'sao'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sinh hoạt', distractors: ['xinh hoạt', 'sinh', 'xinh'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xung quanh', distractors: ['sung quanh', 'xung', 'sung'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sơ đồ', distractors: ['xơ đồ', 'sơ', 'xơ'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xung phong', distractors: ['sung phong', 'xung', 'sung'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sư phụ', distractors: ['xư phụ', 'sư', 'xư'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xung đột', distractors: ['sung đột', 'xung', 'sung'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sơ sinh', distractors: ['xơ sinh', 'sơ', 'xơ'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xung khắc', distractors: ['sung khắc', 'xung', 'sung'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sao', distractors: ['xao', 'sau', 'xau'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xinh', distractors: ['sinh', 'xịn', 'sin'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sắn', distractors: ['xắn', 'sân', 'xân'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sóng', distractors: ['xóng', 'sông', 'xông'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sáng', distractors: ['xáng', 'san', 'xan'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'soạn', distractors: ['xoạn', 'soan', 'xoan'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sen', distractors: ['xen', 'san', 'xén'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sương', distractors: ['xương', 'sươn', 'xươn'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sưởi', distractors: ['xưởi', 'sưỡi', 'xưỡi'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'sẻ', distractors: ['xẻ', 'sế', 'xế'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'sơn', distractors: ['xơn', 'son', 'xon'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'sút', distractors: ['xút', 'súc', 'xúc'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xuân', distractors: ['suân', 'xân', 'suân'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xanh', distractors: ['sanh', 'san', 'xan'], hint: 's / x' },
  { before: 'Trên bầu trời có ', after: '.', answer: 'xúc', distractors: ['súc', 'súc động', 'xúc động'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xóm', distractors: ['sóm', 'xom', 'som'], hint: 's / x' },
  { before: 'Hôm nay trời ', after: ' quang.', answer: 'xấu', distractors: ['sấu', 'xẩu', 'sẩu'], hint: 's / x' },
];
