import type { SpellingChallenge } from '../challengeTypes';

/** Danh hiệu 1 — phân biệt s / x (60 câu, lớp 4) */
export const LEVEL1_BANK: SpellingChallenge[] = [
  { before: 'Trên bầu trời có rất nhiều ', after: '.', answer: 'sao', distractors: ['xao', 'sau', 'xau'], hint: 's / x' },
  { before: 'Bé Lan rất ', after: '.', answer: 'xinh', distractors: ['sinh', 'sinh đẹp', 'xịn'], hint: 's / x' },
  { before: 'Mẹ nấu ', after: ' cho cả nhà.', answer: 'sắn', distractors: ['xắn', 'sân', 'xân'], hint: 's / x' },
  { before: 'Sóng biển ', after: ' ào ào.', answer: 'sóng', distractors: ['xóng', 'sông', 'xông'], hint: 's / x' },
  { before: 'Hôm nay trời rất ', after: '.', answer: 'sáng', distractors: ['xáng', 'sáng sủa', 'xán'], hint: 's / x' },
  { before: 'Bé đang ', after: ' bài tập.', answer: 'soạn', distractors: ['xoạn', 'soan', 'xoan'], hint: 's / x' },
  { before: 'Hoa ', after: ' nở đầy vườn.', answer: 'sen', distractors: ['xen', 'san', 'xén'], hint: 's / x' },
  { before: 'Sáng sớm trên cánh đồng có ', after: '.', answer: 'sương', distractors: ['xương', 'sươn', 'xương mù'], hint: 's / x' },
  { before: 'Cây măng non ', after: ' cao sau mưa.', answer: 'sung', distractors: ['xung', 'sumg', 'xumg'], hint: 's / x' },
  { before: 'Bé uống một cốc ', after: ' nóng.', answer: 'sữa', distractors: ['xữa', 'sửa', 'xửa'], hint: 's / x' },
  { before: 'Bà em ', after: ' ấm đôi tay.', answer: 'sưởi', distractors: ['xưởi', 'sưỡi', 'xưỡi'], hint: 's / x' },
  { before: 'Chim ', after: ' hót trên cành tre.', answer: 'sẻ', distractors: ['xẻ', 'sế', 'xế'], hint: 's / x' },
  { before: 'Bức tường được quét màu ', after: '.', answer: 'sơn', distractors: ['xơn', 'son', 'xon'], hint: 's / x' },
  { before: 'Cầu thủ ', after: ' bóng rất xa.', answer: 'sút', distractors: ['xút', 'xúc', 'súc'], hint: 's / x' },
  { before: 'Mùa ', after: ' đến thật ấm áp.', answer: 'xuân', distractors: ['suân', 'xân', 'suân'], hint: 's / x' },
  { before: 'Lá cây màu ', after: ' tươi tốt.', answer: 'xanh', distractors: ['sanh', 'san', 'xanh lá'], hint: 's / x' },
  { before: 'Em bị ', after: ' động khi nghe tin vui.', answer: 'xúc', distractors: ['súc', 'súc động', 'xúc động'], hint: 's / x' },
  { before: 'Nhà em ở trong ', after: ' làng.', answer: 'xóm', distractors: ['sóm', 'xom', 'som'], hint: 's / x' },
  { before: 'Việc đó thật ', after: '.', answer: 'xấu', distractors: ['sấu', 'xẩu', 'sẩu'], hint: 's / x' },
  { before: 'Bạn Nam học rất ', after: '.', answer: 'siêng', distractors: ['xiêng', 'siêng năng', 'xiêng năng'], hint: 's / x' },
  { before: 'Em lau nhà ', after: ' sạch sẽ.', answer: 'sàn', distractors: ['xàn', 'san', 'sàn nhà'], hint: 's / x' },
  { before: 'Ngày ', after: ' ấy bà kể chuyện cổ.', answer: 'xưa', distractors: ['sưa', 'xừa', 'sưa kia'], hint: 's / x' },
  { before: 'Mẹ ', after: ' rau trong bếp.', answer: 'xào', distractors: ['sào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Cây ', after: ' tre rất cao.', answer: 'sào', distractors: ['xào', 'xao', 'sao'], hint: 's / x' },
  { before: 'Hai bàn tay ', after: ' lại ấm áp.', answer: 'xúm', distractors: ['súm', 'xum', 'sum'], hint: 's / x' },
  { before: 'Con đường làng thật ', after: '.', answer: 'sơ', distractors: ['xơ', 'so', 'xo'], hint: 's / x' },
  { before: 'Trời mưa ', after: ' rất to.', answer: 'xối', distractors: ['sối', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Đàn chim bay ', after: ' trên trời.', answer: 'sát', distractors: ['xát', 'sat', 'xat'], hint: 's / x' },
  { before: 'Dòng nước ', after: ' chảy trong veo.', answer: 'suối', distractors: ['xuối', 'suoi', 'xuoi'], hint: 's / x' },
  { before: 'Em viết chữ ', after: ' vào vở.', answer: 'sạch', distractors: ['xạch', 'sach', 'xach'], hint: 's / x' },
  { before: 'Em ', after: ' xa quê hương.', answer: 'xót', distractors: ['sót', 'xot', 'sot'], hint: 's / x' },
  { before: 'Mẹ ', after: ' tiếc khi con ốm.', answer: 'sót', distractors: ['xót', 'sot', 'xot'], hint: 's / x' },
  { before: 'Chim non kêu ', after: '.', answer: 'xén', distractors: ['sén', 'xen', 'sen'], hint: 's / x' },
  { before: 'Bác nông dân ', after: ' đất nhà.', answer: 'xới', distractors: ['sới', 'xoi', 'soi'], hint: 's / x' },
  { before: 'Ruộng đất ', after: ' tơm xốp.', answer: 'sới', distractors: ['xới', 'soi', 'xoi'], hint: 's / x' },
  { before: 'Đàn cá ', after: ' dưới ao.', answer: 'sán', distractors: ['xán', 'san', 'xan'], hint: 's / x' },
  { before: 'Không khí lễ hội thật ', after: '.', answer: 'sung', distractors: ['xung', 'sumg', 'xumg'], hint: 's / x' },
  { before: 'Xe máy cần đổ ', after: '.', answer: 'xăng', distractors: ['săng', 'xăng dầu', 'săng dầu'], hint: 's / x' },
  { before: 'Bạn em ', after: ' sàng giúp người già.', answer: 'sàng', distractors: ['xàng', 'sang', 'xang'], hint: 's / x' },
  { before: 'Em ', after: ' ca khúc trước lớp.', answer: 'xướng', distractors: ['sướng', 'xướn', 'sướn'], hint: 's / x' },
  { before: 'Em ', after: ' tay chào thầy cô.', answer: 'xoà', distractors: ['soà', 'xoa', 'soa'], hint: 's / x' },
  { before: 'Quả ớt rất ', after: '.', answer: 'sắc', distractors: ['xắc', 'sắt', 'xắt'], hint: 's / x' },
  { before: 'Con ', after: ' bơi trong ao.', answer: 'sâu', distractors: ['xâu', 'sau', 'xau'], hint: 's / x' },
  { before: 'Trời hôm qua rất ', after: '.', answer: 'sương', distractors: ['xương', 'sươn', 'xương mù'], hint: 's / x' },
  { before: 'Cây bưởi ra ', after: ' nhiều quả.', answer: 'sung', distractors: ['xung', 'sumg', 'xumg'], hint: 's / x' },
  { before: 'Mùi ', after: ' thơm từ bếp nhà.', answer: 'sướng', distractors: ['xướng', 'sướn', 'xướn'], hint: 's / x' },
  { before: 'Bạn Hùng rất ', after: ' nết.', answer: 'sáng', distractors: ['xáng', 'xán', 'sán'], hint: 's / x' },
  { before: 'Lớp em hát ', after: ' rất hay.', answer: 'sôi', distractors: ['xôi', 'soi', 'xoi'], hint: 's / x' },
  { before: 'Mẹ gọi em ', after: ' ăn cơm.', answer: 'xuống', distractors: ['suống', 'xuốn', 'suốn'], hint: 's / x' },
  { before: 'Ruộng lúa chuyển ', after: ' vàng ươm.', answer: 'sắc', distractors: ['xắc', 'sắt', 'xắt'], hint: 's / x' },
  { before: 'Em ', after: ' bài thơ trước lớp.', answer: 'xướng', distractors: ['sướng', 'đọc', 'sướn'], hint: 's / x' },
  { before: 'Nắng ', after: ' gay gắt buổi trưa.', answer: 'sớm', distractors: ['xớm', 'som', 'xom'], hint: 's / x' },
  { before: 'Bé ', after: ' cười thật tươi.', answer: 'sún', distractors: ['xún', 'sun', 'xun'], hint: 's / x' },
  { before: 'Hoa mai nở ', after: ' Tết.', answer: 'sớm', distractors: ['xớm', 'som', 'xom'], hint: 's / x' },
  { before: 'Em ', after: ' mình trên ghế cao.', answer: 'sơ', distractors: ['xơ', 'so', 'xo'], hint: 's / x' },
  { before: 'Cô bé mặc áo ', after: '.', answer: 'sẫm', distractors: ['xẫm', 'sam', 'xam'], hint: 's / x' },
  { before: 'Trận bóng rất ', after: '.', answer: 'sôi', distractors: ['xôi', 'soi', 'xoi'], hint: 's / x' },
  { before: 'Bác ấy nói ', after: ' tiếng.', answer: 'sào', distractors: ['xào', 'sao', 'xao'], hint: 's / x' },
  { before: 'Em ', after: ' tay rửa sạch.', answer: 'xoa', distractors: ['soa', 'xoà', 'soà'], hint: 's / x' },
  { before: 'Ruộng ', after: ' nước sau mưa.', answer: 'sũng', distractors: ['xũng', 'sung', 'xung'], hint: 's / x' },
  { before: 'Chữ viết còn ', after: '.', answer: 'sấu', distractors: ['xấu', 'sau', 'xau'], hint: 's / x' },
  { before: 'Bạn em rất ', after: ' tính.', answer: 'sung', distractors: ['xung', 'sumg', 'xumg'], hint: 's / x' },
  { before: 'Em nhặt ', after: ' rau luộc.', answer: 'súng', distractors: ['xúng', 'sung', 'xung'], hint: 's / x' },
  { before: 'Cây ', after: ' nghiêng sau gió.', answer: 'so', distractors: ['xo', 'sơ', 'xơ'], hint: 's / x' },
  { before: 'Bức thư viết rất ', after: '.', answer: 'sau', distractors: ['xau', 'sao', 'xao'], hint: 's / x' },
  { before: 'Em ', after: ' mũ khi trời lạnh.', answer: 'sơ', distractors: ['xơ', 'so', 'xo'], hint: 's / x' },
];
