import type { SkinId } from './textureLibrary';

export interface ObjectSkinProfile {
  primary: SkinId;
  secondary?: SkinId;
}

/** Vật liệu chính cho từng đồ vật (100 mẫu). */
export const OBJECT_SKINS: Record<string, ObjectSkinProfile> = {
  o001: { primary: 'wood', secondary: 'wood' },
  o002: { primary: 'brick' },
  o003: { primary: 'wood' },
  o004: { primary: 'wood', secondary: 'paper' },
  o005: { primary: 'grass', secondary: 'food' },
  o006: { primary: 'fabric' },
  o007: { primary: 'paper', secondary: 'fabric' },
  o008: { primary: 'plastic', secondary: 'metal' },
  o009: { primary: 'wood', secondary: 'metal' },
  o010: { primary: 'slate', secondary: 'wood' },
  o011: { primary: 'plastic' },
  o012: { primary: 'bread' },
  o013: { primary: 'plastic' },
  o014: { primary: 'paper' },
  o015: { primary: 'food' },
  o016: { primary: 'metal' },
  o017: { primary: 'wood' },
  o018: { primary: 'ceramic' },
  o019: { primary: 'ceramic' },
  o020: { primary: 'bread' },
  o021: { primary: 'ceramic' },
  o022: { primary: 'paper' },
  o023: { primary: 'plastic' },
  o024: { primary: 'food' },
  o025: { primary: 'plastic' },
  o026: { primary: 'fabric' },
  o027: { primary: 'food' },
  o028: { primary: 'wood' },
  o029: { primary: 'food' },
  o030: { primary: 'plastic' },
  o031: { primary: 'wood' },
  o032: { primary: 'plastic' },
  o033: { primary: 'bread' },
  o034: { primary: 'wood' },

  o035: { primary: 'brick' },
  o036: { primary: 'wood' },
  o037: { primary: 'metal' },
  o038: { primary: 'brick' },
  o039: { primary: 'wood' },
  o040: { primary: 'plastic' },
  o041: { primary: 'wood' },
  o042: { primary: 'plastic' },
  o043: { primary: 'bread' },
  o044: { primary: 'paper' },
  o045: { primary: 'cardboard' },
  o046: { primary: 'wood' },
  o047: { primary: 'plastic' },
  o048: { primary: 'wood' },
  o049: { primary: 'metal' },
  o050: { primary: 'paper' },
  o051: { primary: 'bamboo' },
  o052: { primary: 'food' },
  o053: { primary: 'fabric', secondary: 'wood' },
  o054: { primary: 'fabric' },
  o055: { primary: 'food' },
  o056: { primary: 'slate' },
  o057: { primary: 'ceramic' },
  o058: { primary: 'paper' },
  o059: { primary: 'metal' },
  o060: { primary: 'plastic' },
  o061: { primary: 'plastic' },
  o062: { primary: 'food' },
  o063: { primary: 'plastic' },
  o064: { primary: 'metal' },
  o065: { primary: 'paper' },
  o066: { primary: 'paper' },
  o067: { primary: 'wood' },

  o068: { primary: 'roof' },
  o069: { primary: 'fabric' },
  o070: { primary: 'rubber' },
  o071: { primary: 'fabric' },
  o072: { primary: 'food' },
  o073: { primary: 'wood' },
  o074: { primary: 'roof' },
  o075: { primary: 'fabric' },
  o076: { primary: 'bamboo' },
  o077: { primary: 'roof' },
  o078: { primary: 'bread' },
  o079: { primary: 'roof' },
  o080: { primary: 'fabric' },
  o081: { primary: 'food' },
  o082: { primary: 'metal' },
  o083: { primary: 'fabric' },
  o084: { primary: 'metal' },
  o085: { primary: 'food' },
  o086: { primary: 'food' },
  o087: { primary: 'fabric' },
  o088: { primary: 'fabric' },
  o089: { primary: 'concrete' },
  o090: { primary: 'food' },
  o091: { primary: 'food' },
  o092: { primary: 'roof' },
  o093: { primary: 'metal' },
  o094: { primary: 'plastic' },
  o095: { primary: 'food' },
  o096: { primary: 'roof' },
  o097: { primary: 'wood' },
  o098: { primary: 'fabric' },
  o099: { primary: 'food' },
  o100: { primary: 'plastic' },
};

export function skinProfileForObject(objectId: string): ObjectSkinProfile {
  return OBJECT_SKINS[objectId] ?? { primary: 'wood' };
}
