import type { SpellingChallenge } from '../challengeTypes';

/**
 * Danh hiệu 2 — ch/tr. Chỉ trích SGK / bài chính tả lớp 4 (xem docs/content/SGK_TIENG_VIET_4_CHINH_TA.md).
 */
export const LEVEL2_BANK: SpellingChallenge[] = [
  // Cháu nghe câu chuyện của bà — Nguyễn Văn Thắng (SGK TV4 T1 tr.26)
  {
    before: 'Cái gậy đi trước, ',
    after: ' bà theo sau.',
    answer: 'chân',
    distractors: ['trân', 'chăn', 'trăn'],
    hint: 'ch / tr',
    sgkRef: 'kntt-chau-ba',
  },
  {
    before: '',
    after: ' nghe câu chuyện của bà',
    answer: 'Cháu',
    distractors: ['Tráu', 'Cháo', 'Tráo'],
    hint: 'ch / tr',
    sgkRef: 'kntt-chau-ba',
  },
  {
    before: 'Bỗng nhiên lạc giữa đường quê, ',
    after: ' à !',
    answer: 'cháu',
    distractors: ['tráu', 'cháo', 'tráo'],
    hint: 'ch / tr',
    sgkRef: 'kntt-chau-ba',
  },
  // Đoạn luyện ch/tr kèm SGK TV4 tr.27 (bài Cháu nghe câu chuyện của bà)
  {
    before: 'Như tre mọc thẳng, con người không ',
    after: ' khuất.',
    answer: 'chịu',
    distractors: ['trịu', 'triệu', 'chị'],
    hint: 'ch / tr',
    sgkRef: 'kntt-chau-ba',
  },
  {
    before: 'Người xưa có câu: "',
    after: ' dầu cháy, đốt ngay vẫn thẳng".',
    answer: 'Trúc',
    distractors: ['Chúc', 'Trúk', 'Chúk'],
    hint: 'ch / tr',
    sgkRef: 'kntt-chau-ba',
  },
  {
    before: 'Ta kháng chiến, tre lại là đồng ',
    after: ' chiến đấu của ta,',
    answer: 'chí',
    distractors: ['trí', 'tri', 'chỉ'],
    hint: 'ch / tr',
    sgkRef: 'kntt-chau-ba',
  },
  {
    before: 'tre lại là đồng chí ',
    after: ' đấu của ta,',
    answer: 'chiến',
    distractors: ['triến', 'trấn', 'chiền'],
    hint: 'ch / tr',
    sgkRef: 'kntt-chau-ba',
  },
  // Ngu Công dời núi — VBT chính tả tuần 12 (tr/ch)
  {
    before: 'Ngày xưa, ở ',
    after: ' Quốc có một cụ già chín mươi tuổi tên là Ngu Công.',
    answer: 'Trung',
    distractors: ['Chung', 'Trùng', 'Chùng'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: 'Bực mình vì hai ',
    after: ' núi Thái Hàng và Vương Ốc chắn ngang đường vào nhà,',
    answer: 'trái',
    distractors: ['chái', 'trại', 'chại'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: 'Thái Hàng và Vương Ốc ',
    after: ' ngang đường vào nhà,',
    answer: 'chắn',
    distractors: ['trắn', 'chắn', 'trắng'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: 'Có người ',
    after: ' cười cụ làm vậy uổng công.',
    answer: 'chê',
    distractors: ['trê', 'chê', 'tre'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: 'Tôi ',
    after: ' thì con tôi đào.',
    answer: 'chết',
    distractors: ['trết', 'chết', 'trệt'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: 'Con tôi chết thì ',
    after: ' tôi đào.',
    answer: 'cháu',
    distractors: ['tráu', 'cháu', 'tráo'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: 'Cháu tôi chết thì ',
    after: ' của tôi đào.',
    answer: 'chắt',
    distractors: ['trắt', 'chắt', 'trật'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: 'Núi ',
    after: ' thể mọc cao hơn được nên nhất định sẽ có ngày bị san bằng."',
    answer: 'chẳng',
    distractors: ['trẳng', 'chẳng', 'trắng'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  {
    before: '',
    after: ' nghe cụ già nói vậy, liền đẩy hai trái núi ra xa để cụ có lối đi lại.',
    answer: 'Trời',
    distractors: ['Chời', 'Trời', 'Chời'],
    hint: 'ch / tr',
    sgkRef: 'kntt-vbt-12',
  },
  // Điều kì diệu — Huỳnh Mai Liên (KNTT Bài 1)
  {
    before: 'Cùng ngân nga câu hát\n',
    after: ' giọng nào giống nhau.',
    answer: 'Chẳng',
    distractors: ['Trẳng', 'Chẳng', 'Trắng'],
    hint: 'ch / tr',
    sgkRef: 'kntt-bai-01',
  },
  {
    before: 'Tớ bỗng phát hiện ra\n',
    after: ' vườn hoa của mẹ',
    answer: 'Trong',
    distractors: ['Chong', 'Trong', 'Chông'],
    hint: 'ch / tr',
    sgkRef: 'kntt-bai-01',
  },
  {
    before: 'Cũng giống như ',
    after: ' mình',
    answer: 'chúng',
    distractors: ['trúng', 'chúng', 'trung'],
    hint: 'ch / tr',
    sgkRef: 'kntt-bai-01',
  },
  // Lên nương — CTST T1 (tr.25–26 OCR)
  {
    before: 'Liêm ',
    after: ' lại chiếc quai gùi trên vai.',
    answer: 'xách',
    distractors: ['sách', 'xạch', 'sạch'],
    hint: 'ch / tr',
    sgkRef: 'ct-len-nuong',
  },
  {
    before: 'Hai con bò nuôi nhốt trong ',
    after: '.',
    answer: 'chuồng',
    distractors: ['truồng', 'chuồn', 'truồn'],
    hint: 'ch / tr',
    sgkRef: 'ct-len-nuong',
  },
  {
    before: 'Hôm nay, Liêm lên nương ',
    after: ' cỏ voi cho bò.',
    answer: 'chặt',
    distractors: ['trặt', 'chắt', 'trắt'],
    hint: 'ch / tr',
    sgkRef: 'ct-len-nuong',
  },
  {
    before: 'những bó cỏ voi đều “',
    after: '” từ trên nương về trên lưng của bố.',
    answer: 'chạy',
    distractors: ['trạy', 'chẩy', 'trẩy'],
    hint: 'ch / tr',
    sgkRef: 'ct-len-nuong',
  },
  {
    before: 'Mỗi ',
    after: ' một bó cỏ là đủ rồi.',
    answer: 'chuyến',
    distractors: ['truyến', 'chuyền', 'truyền'],
    hint: 'ch / tr',
    sgkRef: 'ct-len-nuong',
  },
  // Ca dao về tình yêu thương — CTST T1 (tr.47 OCR)
  {
    before: 'Cơm cha, áo mẹ, ',
    after: ' thầy',
    answer: 'chữ',
    distractors: ['trữ', 'chứ', 'trứ'],
    hint: 'ch / tr',
    sgkRef: 'ct-ca-dao-tinh-yeu',
  },
  {
    before: 'Cùng ',
    after: ' bác mẹ, một nhà cùng thân.',
    answer: 'chung',
    distractors: ['trung', 'chũng', 'trũng'],
    hint: 'ch / tr',
    sgkRef: 'ct-ca-dao-tinh-yeu',
  },
  {
    before: 'Yêu nhau như thế tay ',
    after: ',',
    answer: 'chân',
    distractors: ['trân', 'chăn', 'trăn'],
    hint: 'ch / tr',
    sgkRef: 'ct-ca-dao-tinh-yeu',
  },
  {
    before: 'Anh em hoà ',
    after: ', hai thân vui vầy.',
    answer: 'thuận',
    distractors: ['thuấn', 'truận', 'thuần'],
    hint: 'ch / tr',
    sgkRef: 'ct-ca-dao-tinh-yeu',
  },
  // Gieo ngày mới — Ngọc Hà
  {
    before: 'Giòn tan bằng một ',
    after: ' cười!',
    answer: 'chuỗi',
    distractors: ['truỗi', 'chuỗn', 'truỗn'],
    hint: 'ch / tr',
    sgkRef: 'ct-gieo-ngay-moi',
  },
];
