import type { SpellingChallenge } from '../challengeTypes';

/**
 * Danh hiệu 3 — d / gi / r / đ. Chỉ trích SGK / bài chính tả lớp 4 (xem docs/content/SGK_TIENG_VIET_4_CHINH_TA.md).
 */
export const LEVEL3_BANK: SpellingChallenge[] = [
  // Kéo co — SGK TV4 T1 tr.156 (nghe–viết r/d/gi)
  {
    before: 'Nhưng dù bên nào thắng thì cuộc thi vẫn ',
    after: ' là vui.',
    answer: 'rất',
    distractors: ['dất', 'giất', 'đất'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'Vui ở sự ganh đua, vui ở tiếng hò ',
    after: ', khuyến khích của người xem hội.',
    answer: 'reo',
    distractors: ['deo', 'gèo', 'dèo'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'Làng Tích Sơn thuộc thị xã Vĩnh Yên, tỉnh Vĩnh Phúc lại có tục thi kéo co giữa ',
    after: ' tráng hai giáp trong làng.',
    answer: 'trai',
    distractors: ['drai', 'grai', 'đai'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'thi kéo co ',
    after: ' nam và nữ.',
    answer: 'giữa',
    distractors: ['dữa', 'rữa', 'đữa'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'Nhiều khi có ',
    after: ' thua keo đầu, tới keo thứ hai,',
    answer: 'giáp',
    distractors: ['ráp', 'dáp', 'đáp'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'Nhiều khi có giáp thua keo đầu, tới keo thứ hai, ',
    after: ' ông trong giáp kéo đến đông hơn,',
    answer: 'đàn',
    distractors: ['ràn', 'giàn', 'dàn'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'đàn ông trong giáp kéo ',
    after: ' đông hơn,',
    answer: 'đến',
    distractors: ['rến', 'giến', 'dến'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'đàn ông trong giáp kéo đến ',
    after: ' hơn,',
    answer: 'đông',
    distractors: ['rông', 'giông', 'dông'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  // Trai ngọc và hải quỳ — KNTT (đọc HK1)
  {
    before: 'Cá mực lễ phép trả lời ',
    after: ' vội vã bơi đi,',
    answer: 'rồi',
    distractors: ['dồi', 'giồi', 'đồi'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'Cá mực lễ phép trả lời rồi vội vã bơi ',
    after: ',',
    answer: 'đi',
    distractors: ['ri', 'gi', 'di'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'nó hơi sợ khi nhìn thấy vỏ ngoài của cô ',
    after: '.',
    answer: 'trai',
    distractors: ['drai', 'grai', 'đai'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'Cá mực ',
    after: ' nhanh đến một bông hoa nhiều màu sắc bên kia lối đi.',
    answer: 'bơi',
    distractors: ['dơi', 'rơi', 'giơi'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'Chợt tiếng cô trai gọi ',
    after: ' lại:',
    answer: 'giật',
    distractors: ['dật', 'rật', 'đật'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'Cá mực ',
    after: ' ném lọ mực vào bông hoa để mực loang ra, cá cơm có thể chạy trốn.',
    answer: 'định',
    distractors: ['rịnh', 'giịnh', 'dịnh'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'một chú cá cơm bé tí bơi đến ',
    after: ' nghịch với những cánh hoa mềm mại',
    answer: 'đùa',
    distractors: ['rùa', 'giùa', 'dùa'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'Cá mực ',
    after: ' gần hơn, những cánh hoa mừng rỡ múa mãi lên.',
    answer: 'đến',
    distractors: ['rến', 'giến', 'dến'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: '– Bông hoa đẹp đẽ thế kia nhưng ',
    after: ' dữ.',
    answer: 'rất',
    distractors: ['dất', 'giất', 'đất'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: '– Bông hoa đẹp đẽ thế kia nhưng rất ',
    after: '.',
    answer: 'dữ',
    distractors: ['rữ', 'giữ', 'đữ'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  {
    before: 'Cô trai căn ',
    after: ':',
    answer: 'dặn',
    distractors: ['rặn', 'giặn', 'đặn'],
    hint: 'd / gi / r / đ',
    sgkRef: 'kntt-trai-ngoc',
  },
  // Lên nương — CTST T1 (tr.25 OCR)
  {
    before: 'Một cơn gió thổi từ phía thung ',
    after: ' lên mát rượi.',
    answer: 'lũng',
    distractors: ['giũng', 'rũng', 'đũng'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-len-nuong',
  },
  {
    before: 'Liêm ',
    after: ' lại hít hà.',
    answer: 'dừng',
    distractors: ['rừng', 'giừng', 'đừng'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-len-nuong',
  },
  {
    before: 'Em ngửi thấy mùi ngô non thơm ',
    after: ' trong gió.',
    answer: 'dịu',
    distractors: ['rịu', 'giịu', 'địu'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-len-nuong',
  },
  // Chợ Tết — CTST T2 (OCR tr.66)
  {
    before: 'Vài cụ già chống gậy bước lom ',
    after: '',
    answer: 'khom',
    distractors: ['ghom', 'rhom', 'đom'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-cho-tet',
  },
  {
    before: 'Sương trắng ',
    after: ' đầu cành như giọt sữa tươi',
    answer: 'rỏ',
    distractors: ['dỏ', 'giỏ', 'đỏ'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-cho-tet',
  },
  // Ca dao về tình yêu thương — CTST T1 (tr.47 OCR)
  {
    before: 'Nghĩa mẹ bằng trời chín tháng ',
    after: ' mang.',
    answer: 'cưu',
    distractors: ['trưu', 'giưu', 'dưu'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-ca-dao-tinh-yeu',
  },
  {
    before: 'Bầu ơi thương lấy ',
    after: ' cùng',
    answer: 'bí',
    distractors: ['dí', 'gií', 'rí'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-ca-dao-tinh-yeu',
  },
  {
    before: 'Tuy rằng khác giống nhưng chung một ',
    after: '.',
    answer: 'giàn',
    distractors: ['dàn', 'riàn', 'ràn'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-ca-dao-tinh-yeu',
  },
  // Mùa thu — Huỳnh Thị Thu Hương
  {
    before: 'Mùa thu, những khu vườn ',
    after: ' lá vàng xao động, trái bưởi bỗng tròn căng',
    answer: 'dãy',
    distractors: ['giãy', 'rãy', 'đãy'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-mua-thu',
  },
  {
    before: 'Tết ',
    after: ' từ đại dương',
    answer: 'xuống',
    distractors: ['dướng', 'giướng', 'rướng'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-xuan-bach-long-vi',
  },
  // Kéo co — bổ sung
  {
    before: 'Vui ở sự ganh ',
    after: ', vui ở tiếng hò reo, khuyến khích của người xem hội.',
    answer: 'đua',
    distractors: ['rua', 'giua', 'dua'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
  {
    before: 'Làng Tích Sơn thuộc thị xã Vĩnh Yên, tỉnh Vĩnh Phúc lại có tục thi ',
    after: ' co giữa trai tráng hai giáp trong làng.',
    answer: 'kéo',
    distractors: ['déo', 'géo', 'réo'],
    hint: 'd / gi / r / đ',
    sgkRef: 'ct-keo-co',
  },
];
