import type { SpellingChallenge } from '../challengeTypes';

/**
 * Danh hiệu 1 — s/x. Chỉ trích SGK / bài chính tả lớp 4 (xem docs/content/SGK_TIENG_VIET_4_CHINH_TA.md).
 */
export const LEVEL1_BANK: SpellingChallenge[] = [
  // Chiếc áo búp bê — Nguyễn Thanh Bình (chính tả lớp 4, nghe–viết s/x)
  {
    before: 'Tôi ',
    after: ' chị Khánh được tấc vải xa tanh màu mật ong, khâu chiếc áo cho bé.',
    answer: 'xin',
    distractors: ['xinh', 'sin', 'xịn'],
    hint: 's / x',
    sgkRef: 'ct-chiec-ao',
  },
  {
    before: 'Tôi xin chị Khánh được ',
    after: ' vải xa tanh màu mật ong, khâu chiếc áo cho bé.',
    answer: 'tấc',
    distractors: ['xấc', 'tác', 'xác'],
    hint: 's / x',
    sgkRef: 'ct-chiec-ao',
  },
  {
    before: 'Tôi xin chị Khánh được tấc vải ',
    after: ' tanh màu mật ong, khâu chiếc áo cho bé.',
    answer: 'xa',
    distractors: ['sa', 'xà', 'sà'],
    hint: 's / x',
    sgkRef: 'ct-chiec-ao',
  },
  {
    before: 'Các mép áo đều được viền bằng vải ',
    after: ', rất nổi.',
    answer: 'xanh',
    distractors: ['sanh', 'sánh', 'xanh lá'],
    hint: 's / x',
    sgkRef: 'ct-chiec-ao',
  },
  {
    before: 'Chắc bé ',
    after: ' thích chiếc áo nhỏ xíu này vì tự tay tôi đã may cho bé.',
    answer: 'sẽ',
    distractors: ['xẽ', 'xế', 'sế'],
    hint: 's / x',
    sgkRef: 'ct-chiec-ao',
  },
  {
    before: 'Chắc bé sẽ thích chiếc áo nhỏ ',
    after: ' này vì tự tay tôi đã may cho bé.',
    answer: 'xíu',
    distractors: ['síu', 'xịu', 'sịu'],
    hint: 's / x',
    sgkRef: 'ct-chiec-ao',
  },
  // Chợ Tết — Nguyễn Đình Thi (nhớ–viết, SGK TV4 T2)
  {
    before: '',
    after: ' hồng lam ôm ấp nóc nhà tranh,',
    answer: 'Sương',
    distractors: ['Xương', 'Sướng', 'Xướng'],
    hint: 's / x',
    sgkRef: 'ct-cho-tet',
  },
  {
    before: 'Người các ấp ',
    after: ' bừng ra chợ Tết.',
    answer: 'tưng',
    distractors: ['xưng', 'tung', 'sưng'],
    hint: 's / x',
    sgkRef: 'ct-cho-tet',
  },
  {
    before: 'Những thằng cu áo đỏ chạy lon ',
    after: ',',
    answer: 'xon',
    distractors: ['son', 'xôn', 'sôn'],
    hint: 's / x',
    sgkRef: 'ct-cho-tet',
  },
  {
    before: 'Hai người thôn gánh lợn chạy đi đầu,\nCon bò vàng ngộ nghĩnh đuổi theo ',
    after: '.',
    answer: 'sau',
    distractors: ['xau', 'sao', 'xao'],
    hint: 's / x',
    sgkRef: 'ct-cho-tet',
  },
  // Bài thơ về tiểu đội xe không kính — Phạm Huy Thông
  {
    before: 'Nhìn thấy gió vào ',
    after: ' mắt đắng',
    answer: 'xoa',
    distractors: ['soa', 'xoà', 'soà'],
    hint: 's / x',
    sgkRef: 'ct-xe-khong-kinh',
  },
  {
    before: 'Không có kính, ừ thì ướt áo\nMưa tuôn, mưa ',
    after: ' như ngoài trời',
    answer: 'xối',
    distractors: ['sối', 'xoi', 'soi'],
    hint: 's / x',
    sgkRef: 'ct-xe-khong-kinh',
  },
  {
    before: 'Gặp bạn bè ',
    after: ' dọc đường đi tới',
    answer: 'suốt',
    distractors: ['xuốt', 'suôt', 'xuôt'],
    hint: 's / x',
    sgkRef: 'ct-xe-khong-kinh',
  },
  // Điều kì diệu — KNTT Bài 1 (Huỳnh Mai Liên)
  {
    before: 'Từng bông hoa tươi ',
    after: '',
    answer: 'xinh',
    distractors: ['sinh', 'xịn', 'sính'],
    hint: 's / x',
    sgkRef: 'kntt-bai-01',
  },
  {
    before: 'Lung linh màu ',
    after: ' thế',
    answer: 'sắc',
    distractors: ['xắc', 'sắt', 'xắt'],
    hint: 's / x',
    sgkRef: 'kntt-bai-01',
  },
  // Ngôi trường nơi đầu ngọn sóng — CTST T1 (Nghe–viết, tr.77 OCR)
  {
    before: 'cây bàng vuông ',
    after: ' thẫm trên đảo Sinh Tồn đầy nắng gió.',
    answer: 'xanh',
    distractors: ['sanh', 'xanh lá', 'sánh'],
    hint: 's / x',
    sgkRef: 'ct-ngoi-truong-sinh-ton',
  },
  {
    before: 'Hằng năm, trường đều nhận được sự quan tâm, hỗ trợ của Uỷ ban nhân dân xã Sinh ',
    after: ',',
    answer: 'Tồn',
    distractors: ['Tồm', 'Tổn', 'Tôn'],
    hint: 's / x',
    sgkRef: 'ct-ngoi-truong-sinh-ton',
  },
  // Nha Trang — CTST T2 (Nghe–viết, tr.75 OCR)
  {
    before: '',
    after: ' xanh mặt biển, da trời,',
    answer: 'Xanh',
    distractors: ['Sanh', 'Xanh lá', 'Sánh'],
    hint: 's / x',
    sgkRef: 'ct-nha-trang',
  },
  {
    before: 'Cảnh ',
    after: ' quyến rũ lòng người khó quên!',
    answer: 'sao',
    distractors: ['xao', 'sau', 'xau'],
    hint: 's / x',
    sgkRef: 'ct-nha-trang',
  },
  // Xuân trên đảo Bạch Long Vĩ — CTST T1 (Nghe–viết, tr.146 OCR)
  {
    before: 'Bây giờ đứng quấn khăn ',
    after: '',
    answer: 'sương',
    distractors: ['xương', 'sướng', 'xướng'],
    hint: 's / x',
    sgkRef: 'ct-xuan-bach-long-vi',
  },
  {
    before: 'Làng chài nức mùi cá ',
    after: '',
    answer: 'nướng',
    distractors: ['xướng', 'sướng', 'nước'],
    hint: 's / x',
    sgkRef: 'ct-xuan-bach-long-vi',
  },
  // Chợ Tết — bổ sung từ CTST T2 (OCR tr.66)
  {
    before: '',
    after: ' trắng rỏ đầu cành như giọt sữa tươi',
    answer: 'Sương',
    distractors: ['Xương', 'Sướng', 'Xướng'],
    hint: 's / x',
    sgkRef: 'ct-cho-tet',
  },
  {
    before: 'Tia nắng tía nháy hoài trong ruộng ',
    after: '',
    answer: 'lúa',
    distractors: ['xúa', 'lũa', 'súa'],
    hint: 's / x',
    sgkRef: 'ct-cho-tet',
  },
  // Mùa thu — Huỳnh Thị Thu Hương (CTST T1, tr.39–40 OCR)
  {
    before: 'Tiếng đám ',
    after: ' non tíu tít nhảy nhót',
    answer: 'sẻ',
    distractors: ['xẻ', 'sè', 'xè'],
    hint: 's / x',
    sgkRef: 'ct-mua-thu',
  },
  {
    before: 'trên nền trời chi chít ánh ',
    after: '.',
    answer: 'sao',
    distractors: ['xao', 'sau', 'xau'],
    hint: 's / x',
    sgkRef: 'ct-mua-thu',
  },
  {
    before: 'những khu vườn dãy lá vàng ',
    after: ' động, trái bưởi bỗng tròn căng',
    answer: 'xao',
    distractors: ['sao', 'xau', 'sau'],
    hint: 's / x',
    sgkRef: 'ct-mua-thu',
  },
  {
    before: 'Tia nắng sớm mai như vô tình đậu lên trang vở mới,\nbừng ',
    after: ' lung linh những ước mơ.',
    answer: 'sáng',
    distractors: ['xáng', 'sảng', 'xạng'],
    hint: 's / x',
    sgkRef: 'ct-mua-thu',
  },
  // Gieo ngày mới — Ngọc Hà (CTST T1, tr.20 OCR)
  {
    before: 'Gieo thành bao ước mơ ',
    after: '',
    answer: 'xanh',
    distractors: ['sanh', 'xanh lá', 'sánh'],
    hint: 's / x',
    sgkRef: 'ct-gieo-ngay-moi',
  },
  {
    before: 'Cho cả trời ',
    after: ' lấp lánh',
    answer: 'sao',
    distractors: ['xao', 'sau', 'xau'],
    hint: 's / x',
    sgkRef: 'ct-gieo-ngay-moi',
  },
  // Đất lành chim đậu — Sơn Nam (CTST T2 Nghe–viết, tr.135 OCR)
  {
    before: 'Từng sân tụ tập hàng vạn con chim lớn. Chúng\n',
    after: ' nảy nở, tạo lập một thế giới riêng',
    answer: 'sinh',
    distractors: ['xinh', 'sin', 'xịn'],
    hint: 's / x',
    sgkRef: 'ct-dat-lanh-chim-dau',
  },
  {
    before: 'sinh ',
    after: ' nảy nở, tạo lập một thế giới riêng',
    answer: 'sôi',
    distractors: ['xôi', 'soi', 'xoi'],
    hint: 's / x',
    sgkRef: 'ct-dat-lanh-chim-dau',
  },
];
