import type { CountryProfile } from './types';

function q(
  id: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: [string, string, string],
  correctIndex: 0 | 1 | 2
) {
  return { id, difficulty, prompt, options, correctIndex };
}

export const COUNTRIES: CountryProfile[] = [
  {
    id: 'usa',
    name: 'Hoa Kỳ',
    flagColors: ['#b22234', '#ffffff', '#3c3b6e'],
    culture: 'Hoa Kỳ có nhiều công viên quốc gia rộng lớn và đa dạng văn hóa.',
    footballHistory: 'Đội tuyển Mỹ từng vào tứ kết World Cup 2002 và là một trong ba nước đồng chủ nhà World Cup 2026.',
    signatureFood: 'Burger và hot dog là món ăn nhanh nổi tiếng.',
    figure: 'Landon Donovan từng là biểu tượng bóng đá Mỹ nhiều năm.',
    questions: [
      q('usa-e1', 'easy', 'Thủ đô của Hoa Kỳ là?', ['Washington D.C.', 'New York', 'Los Angeles'], 0),
      q('usa-e2', 'easy', 'Màu chính trên cờ Mỹ gồm?', ['Đỏ, trắng, xanh', 'Vàng, đỏ, xanh', 'Đen, trắng, đỏ'], 0),
      q('usa-m1', 'medium', 'World Cup 2026 có bao nhiêu nước đồng chủ nhà?', ['1', '2', '3'], 2),
      q('usa-m2', 'medium', 'Món ăn nhanh nổi tiếng của Mỹ?', ['Phở', 'Burger', 'Sushi'], 1),
      q('usa-h1', 'hard', 'Hoa Kỳ từng vào vòng nào tại World Cup 2002?', ['Vòng bảng', 'Tứ kết', 'Chung kết'], 1),
      q('usa-h2', 'hard', 'Giải bóng đá nhà nghề lớn của Mỹ là?', ['MLS', 'NBA', 'NFL'], 0),
    ],
  },
  {
    id: 'mexico',
    name: 'Mexico',
    flagColors: ['#006847', '#ffffff', '#ce1126'],
    culture: 'Mexico nổi tiếng với lễ hội Día de los Muertos đầy màu sắc.',
    footballHistory: 'Mexico là đội bóng mạnh nhất CONCACAF và từng nhiều lần vào vòng 16 đội World Cup.',
    signatureFood: 'Taco và guacamole là món ăn đặc trưng.',
    figure: 'Hugo Sánchez là huyền thoại bóng đá Mexico.',
    questions: [
      q('mx-e1', 'easy', 'Màu xanh lá trên cờ Mexico tượng trưng điều gì?', ['Hy vọng', 'Biển', 'Núi'], 0),
      q('mx-e2', 'easy', 'Thủ đô Mexico là?', ['Mexico City', 'Guadalajara', 'Cancún'], 0),
      q('mx-m1', 'medium', 'Mexico đồng chủ nhà World Cup 2026 cùng nước nào?', ['Brazil và Argentina', 'Mỹ và Canada', 'Pháp và Đức'], 1),
      q('mx-m2', 'medium', 'Món ăn Mexico nổi tiếng?', ['Taco', 'Pizza', 'Pad thai'], 0),
      q('mx-h1', 'hard', 'Sân vận động Azteca ở đâu?', ['Mexico City', 'Monterrey', 'Puebla'], 0),
      q('mx-h2', 'hard', 'Mexico từng đăng cai World Cup mấy lần?', ['1', '2', '3'], 1),
    ],
  },
  {
    id: 'canada',
    name: 'Canada',
    flagColors: ['#ff0000', '#ffffff', '#ff0000'],
    culture: 'Canada nổi tiếng với phong cảnh thiên nhiên hùng vĩ và lá phong.',
    footballHistory: 'Canada lần đầu vào World Cup 1986 và trở lại mạnh mẽ nhờ giải MLS phát triển.',
    signatureFood: 'Siro maple và poutine là món đặc trưng.',
    figure: 'Alphonso Davies là ngôi sao bóng đá Canada hiện nay.',
    questions: [
      q('ca-e1', 'easy', 'Biểu tượng lá trên cờ Canada là?', ['Lá phong', 'Lá tre', 'Lá cọ'], 0),
      q('ca-e2', 'easy', 'Thủ đô Canada là?', ['Ottawa', 'Toronto', 'Vancouver'], 0),
      q('ca-m1', 'medium', 'Món poutine gồm khoai tây chiên và gì?', ['Phô mai và nước sốt', 'Cá hồi', 'Bơ'], 0),
      q('ca-m2', 'medium', 'Canada đồng chủ nhà World Cup 2026 với?', ['Anh và Pháp', 'Mỹ và Mexico', 'Nhật và Hàn'], 1),
      q('ca-h1', 'hard', 'Alphonso Davies chơi ở vị trí nào?', ['Hậu vệ cánh', 'Thủ môn', 'Trọng tài'], 0),
      q('ca-h2', 'hard', 'Canada lần đầu dự World Cup năm nào?', ['1966', '1986', '2010'], 1),
    ],
  },
  {
    id: 'brazil',
    name: 'Brazil',
    flagColors: ['#009c3b', '#ffdf00', '#002776'],
    culture: 'Brazil nổi tiếng với carnival Rio và âm nhạc samba sôi động.',
    footballHistory: 'Brazil vô địch World Cup 5 lần, nhiều nhất thế giới.',
    signatureFood: 'Feijoada là món hầm đậu đen truyền thống.',
    figure: 'Pelé là huyền thoại bóng đá vĩ đại nhất của Brazil.',
    questions: [
      q('br-e1', 'easy', 'Brazil vô địch World Cup bao nhiêu lần?', ['3', '5', '7'], 1),
      q('br-e2', 'easy', 'Màu vàng trên cờ Brazil tượng trưng?', ['Vàng kim', 'Mặt trời', 'Cát biển'], 0),
      q('br-m1', 'medium', 'Thủ đô Brazil là?', ['Brasília', 'Rio de Janeiro', 'São Paulo'], 0),
      q('br-m2', 'medium', 'Pelé từng chơi cho đội tuyển nào?', ['Brazil', 'Argentina', 'Bồ Đào Nha'], 0),
      q('br-h1', 'hard', 'Brazil vô địch World Cup lần đầu năm nào?', ['1958', '1970', '1994'], 0),
      q('br-h2', 'hard', 'Sân Maracanã nằm ở thành phố nào?', ['Rio de Janeiro', 'Salvador', 'Recife'], 0),
    ],
  },
  {
    id: 'argentina',
    name: 'Argentina',
    flagColors: ['#74acdf', '#ffffff', '#74acdf'],
    culture: 'Argentina nổi tiếng với tango và văn hóa ẩm thực phong phú.',
    footballHistory: 'Argentina vô địch World Cup 3 lần, gần nhất là năm 2022.',
    signatureFood: 'Asado là món nướng thịt bò truyền thống.',
    figure: 'Lionel Messi là biểu tượng bóng đá Argentina.',
    questions: [
      q('ar-e1', 'easy', 'Argentina vô địch World Cup 2022 tại quốc gia nào?', ['Qatar', 'Nga', 'Brazil'], 0),
      q('ar-e2', 'easy', 'Biểu tượng trên cờ Argentina là?', ['Mặt trời', 'Ngôi sao đỏ', 'Chữ thập'], 0),
      q('ar-m1', 'medium', 'Messi chơi vị trí nào?', ['Tiền đạo/Tiền vệ tấn công', 'Thủ môn', 'Trọng tài'], 0),
      q('ar-m2', 'medium', 'Thủ đô Argentina là?', ['Buenos Aires', 'Córdoba', 'Mendoza'], 0),
      q('ar-h1', 'hard', 'Argentina vô địch World Cup lần đầu năm nào?', ['1978', '1986', '1990'], 0),
      q('ar-h2', 'hard', 'Maradona ghi bàn nổi tiếng ở World Cup nào?', ['1986', '1994', '2002'], 0),
    ],
  },
  {
    id: 'france',
    name: 'Pháp',
    flagColors: ['#0055a4', '#ffffff', '#ef4135'],
    culture: 'Pháp nổi tiếng với tháp Eiffel và nghệ thuật ẩm thực tinh tế.',
    footballHistory: 'Pháp vô địch World Cup 1998 và 2018.',
    signatureFood: 'Bánh mì baguette và phô mai là biểu tượng ẩm thực Pháp.',
    figure: 'Zinedine Zidane là huyền thoại bóng đá Pháp.',
    questions: [
      q('fr-e1', 'easy', 'Thủ đô Pháp là?', ['Paris', 'Lyon', 'Marseille'], 0),
      q('fr-e2', 'easy', 'Cờ Pháp có mấy dải màu dọc?', ['2', '3', '4'], 1),
      q('fr-m1', 'medium', 'Pháp vô địch World Cup 2018 tại nước nào?', ['Nga', 'Qatar', 'Brazil'], 0),
      q('fr-m2', 'medium', 'Zidane từng chơi cho đội tuyển nào?', ['Pháp', 'Ý', 'Tây Ban Nha'], 0),
      q('fr-h1', 'hard', 'Pháp vô địch World Cup 1998 trên sân nhà, đánh bại ai ở chung kết?', ['Brazil', 'Đức', 'Argentina'], 0),
      q('fr-h2', 'hard', 'Mbappé ghi bao nhiêu bàn ở chung kết World Cup 2022?', ['2', '3', '4'], 1),
    ],
  },
  {
    id: 'germany',
    name: 'Đức',
    flagColors: ['#000000', '#dd0000', '#ffce00'],
    culture: 'Đức nổi tiếng với lễ hội Oktoberfest và kiến trúc cổ kính.',
    footballHistory: 'Đức vô địch World Cup 4 lần và từng nhiều lần vào bán kết.',
    signatureFood: 'Xúc xích Bratwurst và bánh pretzel là món đặc trưng.',
    figure: 'Franz Beckenbauer là huyền thoại bóng đá Đức.',
    questions: [
      q('de-e1', 'easy', 'Đức vô địch World Cup bao nhiêu lần?', ['2', '4', '6'], 1),
      q('de-e2', 'easy', 'Màu vàng trên cờ Đức là?', ['Vàng kim', 'Cam', 'Hồng'], 0),
      q('de-m1', 'medium', 'Thủ đô Đức là?', ['Berlin', 'Munich', 'Hamburg'], 0),
      q('de-m2', 'medium', 'Đức vô địch World Cup 2014 tại Brazil, hạ ai ở chung kết?', ['Argentina', 'Brazil', 'Pháp'], 0),
      q('de-h1', 'hard', 'Beckenbauer được gọi là gì?', ['Kaiser', 'Maestro', 'El Pibe'], 0),
      q('de-h2', 'hard', 'Đức đăng cai World Cup gần nhất năm nào?', ['2006', '2010', '2014'], 0),
    ],
  },
  {
    id: 'spain',
    name: 'Tây Ban Nha',
    flagColors: ['#aa151b', '#f1bf00', '#aa151b'],
    culture: 'Tây Ban Nha nổi tiếng với flamenco và kiến trúc Gaudi.',
    footballHistory: 'Tây Ban Nha vô địch World Cup 2010 và Euro 2008, 2012.',
    signatureFood: 'Paella là món cơm hải sản nổi tiếng.',
    figure: 'Andrés Iniesta ghi bàn quyết định ở chung kết World Cup 2010.',
    questions: [
      q('es-e1', 'easy', 'Tây Ban Nha vô địch World Cup năm nào?', ['2006', '2010', '2014'], 1),
      q('es-e2', 'easy', 'Thủ đô Tây Ban Nha là?', ['Madrid', 'Barcelona', 'Seville'], 0),
      q('es-m1', 'medium', 'Món paella thường có gì?', ['Cơm và hải sản', 'Bánh mì', 'Mì Ý'], 0),
      q('es-m2', 'medium', 'Iniesta ghi bàn ở chung kết World Cup 2010 hạ đội nào?', ['Hà Lan', 'Đức', 'Brazil'], 0),
      q('es-h1', 'hard', 'Real Madrid và Barcelona thuộc giải đấu nào?', ['La Liga', 'Premier League', 'Serie A'], 0),
      q('es-h2', 'hard', 'Tây Ban Nha vô địch Euro liên tiếp mấy lần?', ['1', '2', '3'], 1),
    ],
  },
  {
    id: 'england',
    name: 'Anh',
    flagColors: ['#ffffff', '#ce1124', '#ffffff'],
    culture: 'Anh nổi tiếng với Cung điện Buckingham và truyền thống trà chiều.',
    footballHistory: 'Anh vô địch World Cup 1966 trên sân nhà và là nơi ra đời bóng đá hiện đại.',
    signatureFood: 'Fish and chips là món ăn đường phố nổi tiếng.',
    figure: 'Bobby Charlton là huyền thoại bóng đá Anh.',
    questions: [
      q('en-e1', 'easy', 'Anh vô địch World Cup năm nào?', ['1966', '1970', '1990'], 0),
      q('en-e2', 'easy', 'Thủ đô Anh là?', ['London', 'Manchester', 'Liverpool'], 0),
      q('en-m1', 'medium', 'Giải bóng đá nhà nghề Anh là?', ['Premier League', 'La Liga', 'Bundesliga'], 0),
      q('en-m2', 'medium', 'Món fish and chips gồm?', ['Cá chiên và khoai tây', 'Bánh mì và phô mai', 'Cơm và thịt'], 0),
      q('en-h1', 'hard', 'Wembley là gì?', ['Sân vận động', 'Sông', 'Núi'], 0),
      q('en-h2', 'hard', 'Anh được gọi là quê hương của môn thể thao nào?', ['Bóng đá hiện đại', 'Bóng rổ', 'Cricket'], 0),
    ],
  },
  {
    id: 'japan',
    name: 'Nhật Bản',
    flagColors: ['#ffffff', '#bc002d', '#ffffff'],
    culture: 'Nhật Bản nổi tiếng với hoa anh đào và văn hóa trà đạo.',
    footballHistory: 'Nhật Bản phát triển bóng đá mạnh ở châu Á và thường vào vòng 16 đội World Cup.',
    signatureFood: 'Sushi và ramen là món ăn nổi tiếng toàn cầu.',
    figure: 'Hidetoshi Nakata là biểu tượng bóng đá Nhật Bản đầu tiên ở châu Âu.',
    questions: [
      q('jp-e1', 'easy', 'Biểu tượng trên cờ Nhật Bản là?', ['Mặt trời đỏ', 'Ngôi sao vàng', 'Chữ thập'], 0),
      q('jp-e2', 'easy', 'Thủ đô Nhật Bản là?', ['Tokyo', 'Osaka', 'Kyoto'], 0),
      q('jp-m1', 'medium', 'Món sushi thường dùng gì?', ['Cơm và cá', 'Bánh mì', 'Mì Ý'], 0),
      q('jp-m2', 'medium', 'Nhật Bản đồng chủ nhà World Cup 2002 cùng nước nào?', ['Hàn Quốc', 'Trung Quốc', 'Thái Lan'], 0),
      q('jp-h1', 'hard', 'J-League là giải bóng đá của nước nào?', ['Nhật Bản', 'Hàn Quốc', 'Trung Quốc'], 0),
      q('jp-h2', 'hard', 'Nhật Bản vào vòng 16 đội World Cup 2022 hạ đội nào?', ['Đức', 'Brazil', 'Pháp'], 0),
    ],
  },
  {
    id: 'morocco',
    name: 'Morocco',
    flagColors: ['#c1272d', '#006233', '#c1272d'],
    culture: 'Morocco nổi tiếng với chợ Medina và kiến trúc Hồi giáo đẹp mắt.',
    footballHistory: 'Morocco vào bán kết World Cup 2022, thành tích tốt nhất châu Phi.',
    signatureFood: 'Tagine là món hầm gia vị truyền thống.',
    figure: 'Achraf Hakimi là hậu vệ ngôi sao của Morocco.',
    questions: [
      q('ma-e1', 'easy', 'Morocco thuộc châu lục nào?', ['Châu Phi', 'Châu Á', 'Châu Âu'], 0),
      q('ma-e2', 'easy', 'Thủ đô Morocco là?', ['Rabat', 'Casablanca', 'Marrakech'], 0),
      q('ma-m1', 'medium', 'Morocco vào vòng nào tại World Cup 2022?', ['Vòng 16', 'Tứ kết', 'Bán kết'], 2),
      q('ma-m2', 'medium', 'Món tagine là?', ['Món hầm', 'Bánh ngọt', 'Đồ uống'], 0),
      q('ma-h1', 'hard', 'Hakimi chơi vị trí nào?', ['Hậu vệ cánh', 'Thủ môn', 'Tiền đạo'], 0),
      q('ma-h2', 'hard', 'Morocco thua ai ở bán kết World Cup 2022?', ['Pháp', 'Argentina', 'Croatia'], 0),
    ],
  },
  {
    id: 'portugal',
    name: 'Bồ Đào Nha',
    flagColors: ['#006600', '#ff0000', '#ffff00'],
    culture: 'Bồ Đào Nha nổi tiếng với fado và cầu Luis I ở Porto.',
    footballHistory: 'Bồ Đào Nha vô địch Euro 2016 và Nations League 2019.',
    signatureFood: 'Pastel de nata là bánh trứng ngọt nổi tiếng.',
    figure: 'Cristiano Ronaldo là biểu tượng bóng đá Bồ Đào Nha.',
    questions: [
      q('pt-e1', 'easy', 'Cristiano Ronaldo đến từ nước nào?', ['Bồ Đào Nha', 'Brazil', 'Tây Ban Nha'], 0),
      q('pt-e2', 'easy', 'Thủ đô Bồ Đào Nha là?', ['Lisbon', 'Porto', 'Faro'], 0),
      q('pt-m1', 'medium', 'Bồ Đào Nha vô địch Euro năm nào?', ['2012', '2016', '2020'], 1),
      q('pt-m2', 'medium', 'Pastel de nata là loại gì?', ['Bánh trứng ngọt', 'Món mặn', 'Đồ uống'], 0),
      q('pt-h1', 'hard', 'Ronaldo ghi nhiều bàn nhất cho đội tuyển nước nào?', ['Bồ Đào Nha', 'Brazil', 'Anh'], 0),
      q('pt-h2', 'hard', 'Bồ Đào Nha vô địch Euro 2016 hạ đội nào?', ['Pháp', 'Đức', 'Tây Ban Nha'], 0),
    ],
  },
];
