import type { CountryProfile } from './types';
import { COUNTRY_QUESTION_BANK } from './questionBank';

export const COUNTRIES: CountryProfile[] = [
  {
    id: 'usa',
    name: 'Hoa Kỳ',
    flagColors: ['#b22234', '#ffffff', '#3c3b6e'],
    culture: 'Hoa Kỳ có nhiều công viên quốc gia rộng lớn và đa dạng văn hóa.',
    footballHistory: 'Đội tuyển Mỹ từng vào tứ kết World Cup 2002 và là một trong ba nước đồng chủ nhà World Cup 2026.',
    signatureFood: 'Burger và hot dog là món ăn nhanh nổi tiếng.',
    figure: 'Landon Donovan từng là biểu tượng bóng đá Mỹ nhiều năm.',
    questions: COUNTRY_QUESTION_BANK.usa!,
  },
  {
    id: 'mexico',
    name: 'Mexico',
    flagColors: ['#006847', '#ffffff', '#ce1126'],
    culture: 'Mexico nổi tiếng với lễ hội Día de los Muertos đầy màu sắc.',
    footballHistory: 'Mexico là đội bóng mạnh nhất CONCACAF và từng nhiều lần vào vòng 16 đội World Cup.',
    signatureFood: 'Taco và guacamole là món ăn đặc trưng.',
    figure: 'Hugo Sánchez là huyền thoại bóng đá Mexico.',
    questions: COUNTRY_QUESTION_BANK.mexico!,
  },
  {
    id: 'canada',
    name: 'Canada',
    flagColors: ['#ff0000', '#ffffff', '#ff0000'],
    culture: 'Canada nổi tiếng với phong cảnh thiên nhiên hùng vĩ và lá phong.',
    footballHistory: 'Canada lần đầu vào World Cup 1986 và trở lại mạnh mẽ nhờ giải MLS phát triển.',
    signatureFood: 'Siro maple và poutine là món đặc trưng.',
    figure: 'Alphonso Davies là ngôi sao bóng đá Canada hiện nay.',
    questions: COUNTRY_QUESTION_BANK.canada!,
  },
  {
    id: 'brazil',
    name: 'Brazil',
    flagColors: ['#009c3b', '#ffdf00', '#002776'],
    culture: 'Brazil nổi tiếng với carnival Rio và âm nhạc samba sôi động.',
    footballHistory: 'Brazil vô địch World Cup 5 lần, nhiều nhất thế giới.',
    signatureFood: 'Feijoada là món hầm đậu đen truyền thống.',
    figure: 'Pelé là huyền thoại bóng đá vĩ đại nhất của Brazil.',
    questions: COUNTRY_QUESTION_BANK.brazil!,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    flagColors: ['#74acdf', '#ffffff', '#74acdf'],
    culture: 'Argentina nổi tiếng với tango và văn hóa ẩm thực phong phú.',
    footballHistory: 'Argentina vô địch World Cup 3 lần, gần nhất là năm 2022.',
    signatureFood: 'Asado là món nướng thịt bò truyền thống.',
    figure: 'Lionel Messi là biểu tượng bóng đá Argentina.',
    questions: COUNTRY_QUESTION_BANK.argentina!,
  },
  {
    id: 'france',
    name: 'Pháp',
    flagColors: ['#0055a4', '#ffffff', '#ef4135'],
    culture: 'Pháp nổi tiếng với tháp Eiffel và nghệ thuật ẩm thực tinh tế.',
    footballHistory: 'Pháp vô địch World Cup 1998 và 2018.',
    signatureFood: 'Bánh mì baguette và phô mai là biểu tượng ẩm thực Pháp.',
    figure: 'Zinedine Zidane là huyền thoại bóng đá Pháp.',
    questions: COUNTRY_QUESTION_BANK.france!,
  },
  {
    id: 'germany',
    name: 'Đức',
    flagColors: ['#000000', '#dd0000', '#ffce00'],
    culture: 'Đức nổi tiếng với lễ hội Oktoberfest và kiến trúc cổ kính.',
    footballHistory: 'Đức vô địch World Cup 4 lần và từng nhiều lần vào bán kết.',
    signatureFood: 'Xúc xích Bratwurst và bánh pretzel là món đặc trưng.',
    figure: 'Franz Beckenbauer là huyền thoại bóng đá Đức.',
    questions: COUNTRY_QUESTION_BANK.germany!,
  },
  {
    id: 'spain',
    name: 'Tây Ban Nha',
    flagColors: ['#aa151b', '#f1bf00', '#aa151b'],
    culture: 'Tây Ban Nha nổi tiếng với flamenco và kiến trúc Gaudi.',
    footballHistory: 'Tây Ban Nha vô địch World Cup 2010 và Euro 2008, 2012.',
    signatureFood: 'Paella là món cơm hải sản nổi tiếng.',
    figure: 'Andrés Iniesta ghi bàn quyết định ở chung kết World Cup 2010.',
    questions: COUNTRY_QUESTION_BANK.spain!,
  },
  {
    id: 'england',
    name: 'Anh',
    flagColors: ['#ffffff', '#ce1124', '#ffffff'],
    culture: 'Anh nổi tiếng với Cung điện Buckingham và truyền thống trà chiều.',
    footballHistory: 'Anh vô địch World Cup 1966 trên sân nhà và là nơi ra đời bóng đá hiện đại.',
    signatureFood: 'Fish and chips là món ăn đường phố nổi tiếng.',
    figure: 'Bobby Charlton là huyền thoại bóng đá Anh.',
    questions: COUNTRY_QUESTION_BANK.england!,
  },
  {
    id: 'japan',
    name: 'Nhật Bản',
    flagColors: ['#ffffff', '#bc002d', '#ffffff'],
    culture: 'Nhật Bản nổi tiếng với hoa anh đào và văn hóa trà đạo.',
    footballHistory: 'Nhật Bản phát triển bóng đá mạnh ở châu Á và thường vào vòng 16 đội World Cup.',
    signatureFood: 'Sushi và ramen là món ăn nổi tiếng toàn cầu.',
    figure: 'Hidetoshi Nakata là biểu tượng bóng đá Nhật Bản đầu tiên ở châu Âu.',
    questions: COUNTRY_QUESTION_BANK.japan!,
  },
  {
    id: 'morocco',
    name: 'Morocco',
    flagColors: ['#c1272d', '#006233', '#c1272d'],
    culture: 'Morocco nổi tiếng với chợ Medina và kiến trúc Hồi giáo đẹp mắt.',
    footballHistory: 'Morocco vào bán kết World Cup 2022, thành tích tốt nhất châu Phi.',
    signatureFood: 'Tagine là món hầm gia vị truyền thống.',
    figure: 'Achraf Hakimi là hậu vệ ngôi sao của Morocco.',
    questions: COUNTRY_QUESTION_BANK.morocco!,
  },
  {
    id: 'portugal',
    name: 'Bồ Đào Nha',
    flagColors: ['#006600', '#ff0000', '#ffff00'],
    culture: 'Bồ Đào Nha nổi tiếng với fado và cầu Luis I ở Porto.',
    footballHistory: 'Bồ Đào Nha vô địch Euro 2016 và Nations League 2019.',
    signatureFood: 'Pastel de nata là bánh trứng ngọt nổi tiếng.',
    figure: 'Cristiano Ronaldo là biểu tượng bóng đá Bồ Đào Nha.',
    questions: COUNTRY_QUESTION_BANK.portugal!,
  },
];
