import type { Difficulty, QuizQuestion } from './types';

export function makeQuestion(
  id: string,
  difficulty: Difficulty,
  prompt: string,
  options: [string, string, string],
  correctIndex: 0 | 1 | 2
): QuizQuestion {
  return { id, difficulty, prompt, options, correctIndex };
}

/** 18 câu / quốc gia (6 easy, 6 medium, 6 hard). */
export const COUNTRY_QUESTION_BANK: Record<string, QuizQuestion[]> = {
  usa: [
    makeQuestion('usa-e1', 'easy', 'Thủ đô của Hoa Kỳ là?', ['Washington D.C.', 'New York', 'Los Angeles'], 0),
    makeQuestion('usa-e2', 'easy', 'Màu chính trên cờ Mỹ gồm?', ['Đỏ, trắng, xanh', 'Vàng, đỏ, xanh', 'Đen, trắng, đỏ'], 0),
    makeQuestion('usa-e3', 'easy', 'Tượng Nữ thần Tự do nằm ở thành phố nào?', ['New York', 'Washington D.C.', 'Chicago'], 0),
    makeQuestion('usa-e4', 'easy', 'Hoa Kỳ nằm ở châu lục nào?', ['Bắc Mỹ', 'Châu Âu', 'Nam Mỹ'], 0),
    makeQuestion('usa-e5', 'easy', 'Môn thể thao phổ biến gọi là “soccer” ở Mỹ là?', ['Bóng đá', 'Bóng rổ', 'Bóng chày'], 0),
    makeQuestion('usa-e6', 'easy', 'Ngôn ngữ chính thức phổ biến ở Mỹ là?', ['Tiếng Anh', 'Tiếng Pháp', 'Tiếng Tây Ban Nha'], 0),
    makeQuestion('usa-m1', 'medium', 'World Cup 2026 có bao nhiêu nước đồng chủ nhà?', ['1', '2', '3'], 2),
    makeQuestion('usa-m2', 'medium', 'Món ăn nhanh nổi tiếng của Mỹ?', ['Phở', 'Burger', 'Sushi'], 1),
    makeQuestion('usa-m3', 'medium', 'Giải bóng đá nhà nghề lớn của Mỹ là?', ['MLS', 'NBA', 'NFL'], 0),
    makeQuestion('usa-m4', 'medium', 'Công viên quốc gia Yellowstone nằm ở Mỹ thuộc vùng nào?', ['Núi lửa và suối nước nóng', 'Sa mạc', 'Rừng nhiệt đới'], 0),
    makeQuestion('usa-m5', 'medium', 'Đội tuyển Mỹ có biệt danh nào?', ['USMNT / Stars and Stripes', 'Samba Boys', 'Les Bleus'], 0),
    makeQuestion('usa-m6', 'medium', 'Thành phố Los Angeles nằm ở bang nào?', ['California', 'Texas', 'Florida'], 0),
    makeQuestion('usa-h1', 'hard', 'Hoa Kỳ từng vào vòng nào tại World Cup 2002?', ['Vòng bảng', 'Tứ kết', 'Chung kết'], 1),
    makeQuestion('usa-h2', 'hard', 'Landon Donovan từng là cầu thủ nổi tiếng của đội tuyển nào?', ['Hoa Kỳ', 'Mexico', 'Anh'], 0),
    makeQuestion('usa-h3', 'hard', 'World Cup 1994 được tổ chức chủ yếu ở quốc gia nào?', ['Hoa Kỳ', 'Pháp', 'Ý'], 0),
    makeQuestion('usa-h4', 'hard', 'Sân MetLife (World Cup 2026) gần thành phố nào?', ['New York', 'Miami', 'Seattle'], 0),
    makeQuestion('usa-h5', 'hard', 'Mỹ có bao nhiêu ngôi sao trên cờ (đại diện bang)?', ['50', '48', '52'], 0),
    makeQuestion('usa-h6', 'hard', 'Đội tuyển nữ Mỹ vô địch World Cup nữ bao nhiêu lần?', ['4', '2', '6'], 0),
  ],
  mexico: [
    makeQuestion('mx-e1', 'easy', 'Màu xanh lá trên cờ Mexico tượng trưng điều gì?', ['Hy vọng', 'Biển', 'Núi'], 0),
    makeQuestion('mx-e2', 'easy', 'Thủ đô Mexico là?', ['Mexico City', 'Guadalajara', 'Cancún'], 0),
    makeQuestion('mx-e3', 'easy', 'Mexico nằm ở châu lục nào?', ['Bắc Mỹ', 'Châu Âu', 'Châu Phi'], 0),
    makeQuestion('mx-e4', 'easy', 'Ngôn ngữ chính thức của Mexico là?', ['Tiếng Tây Ban Nha', 'Tiếng Anh', 'Tiếng Bồ Đào Nha'], 0),
    makeQuestion('mx-e5', 'easy', 'Lễ hội Día de los Muertos gắn với quốc gia nào?', ['Mexico', 'Brazil', 'Nhật Bản'], 0),
    makeQuestion('mx-e6', 'easy', 'Biểu tượng chim trên quốc huy Mexico là?', ['Đại bàng cá đầu trắng', 'Chim én', 'Cò'], 0),
    makeQuestion('mx-m1', 'medium', 'Mexico đồng chủ nhà World Cup 2026 cùng nước nào?', ['Brazil và Argentina', 'Mỹ và Canada', 'Pháp và Đức'], 1),
    makeQuestion('mx-m2', 'medium', 'Món ăn Mexico nổi tiếng?', ['Taco', 'Pizza', 'Pad thai'], 0),
    makeQuestion('mx-m3', 'medium', 'Sân vận động Azteca ở đâu?', ['Mexico City', 'Monterrey', 'Puebla'], 0),
    makeQuestion('mx-m4', 'medium', 'Mexico từng đăng cai World Cup mấy lần?', ['1', '2', '3'], 1),
    makeQuestion('mx-m5', 'medium', 'Guacamole thường làm từ quả gì?', ['Bơ', 'Dưa hấu', 'Táo'], 0),
    makeQuestion('mx-m6', 'medium', 'Đội tuyển Mexico có biệt danh?', ['El Tri', 'La Albiceleste', 'A Seleção'], 0),
    makeQuestion('mx-h1', 'hard', 'Hugo Sánchez là huyền thoại bóng đá nước nào?', ['Mexico', 'Tây Ban Nha', 'Argentina'], 0),
    makeQuestion('mx-h2', 'hard', 'Mexico vô địch Gold Cup CONCACAF nhiều lần nhất — khu vực này?', ['Bắc Trung Mỹ và Caribbean', 'Châu Âu', 'Châu Á'], 0),
    makeQuestion('mx-h3', 'hard', 'World Cup 1970 ở Mexico, đội vô địch là?', ['Brazil', 'Đức', 'Ý'], 0),
    makeQuestion('mx-h4', 'hard', 'Chichen Itza là di sản văn hóa của nền văn minh nào ở Mexico?', ['Maya', 'La Mã', 'Ai Cập'], 0),
    makeQuestion('mx-h5', 'hard', 'Mexico vào vòng 16 đội World Cup 2018 sau trận thắng đội nào?', ['Đức', 'Brazil', 'Pháp'], 0),
    makeQuestion('mx-h6', 'hard', 'Giải Liga MX là giải bóng đá nội địa của nước nào?', ['Mexico', 'Colombia', 'Chile'], 0),
  ],
  canada: [
    makeQuestion('ca-e1', 'easy', 'Biểu tượng lá trên cờ Canada là?', ['Lá phong', 'Lá tre', 'Lá cọ'], 0),
    makeQuestion('ca-e2', 'easy', 'Thủ đô Canada là?', ['Ottawa', 'Toronto', 'Vancouver'], 0),
    makeQuestion('ca-e3', 'easy', 'Canada có hai ngôn ngữ chính thức là?', ['Anh và Pháp', 'Anh và Tây Ban Nha', 'Pháp và Đức'], 0),
    makeQuestion('ca-e4', 'easy', 'Tháp CN nổi tiếng ở thành phố nào của Canada?', ['Toronto', 'Ottawa', 'Montreal'], 0),
    makeQuestion('ca-e5', 'easy', 'Canada giáp với đại dương nào ở phía đông?', ['Đại Tây Dương', 'Thái Bình Dương', 'Ấn Độ Dương'], 0),
    makeQuestion('ca-e6', 'easy', 'Mùa đông Canada nổi tiếng với môn thể thao nào?', ['Khúc côn cầu trên băng', 'Cricket', 'Bóng bầu dục'], 0),
    makeQuestion('ca-m1', 'medium', 'Món poutine gồm khoai tây chiên và gì?', ['Phô mai và nước sốt', 'Cá hồi', 'Bơ'], 0),
    makeQuestion('ca-m2', 'medium', 'Canada đồng chủ nhà World Cup 2026 với?', ['Anh và Pháp', 'Mỹ và Mexico', 'Nhật và Hàn'], 1),
    makeQuestion('ca-m3', 'medium', 'Alphonso Davies chơi ở vị trí nào?', ['Hậu vệ cánh', 'Thủ môn', 'Trọng tài'], 0),
    makeQuestion('ca-m4', 'medium', 'Canada lần đầu dự World Cup năm nào?', ['1966', '1986', '2010'], 1),
    makeQuestion('ca-m5', 'medium', 'Siro maple lấy từ cây gì?', ['Cây phong', 'Cây thông', 'Cây dừa'], 0),
    makeQuestion('ca-m6', 'medium', 'Thành phố Vancouver nằm ở tỉnh bang nào?', ['British Columbia', 'Quebec', 'Ontario'], 0),
    makeQuestion('ca-h1', 'hard', 'Canada dự World Cup 2022 sau bao nhiêu năm vắng mặt?', ['36 năm', '12 năm', '4 năm'], 0),
    makeQuestion('ca-h2', 'hard', 'Đội tuyển Canada có biệt danh?', ['Les Rouges / Canucks', 'Oranje', 'La Roja'], 0),
    makeQuestion('ca-h3', 'hard', 'Giải MLS có đội bóng Canada nào?', ['Toronto FC, Vancouver, CF Montréal', 'Chỉ có một đội', 'Không có'], 0),
    makeQuestion('ca-h4', 'hard', 'Vườn quốc gia Banff nằm ở tỉnh bang nào?', ['Alberta', 'Nova Scotia', 'Manitoba'], 0),
    makeQuestion('ca-h5', 'hard', 'Christine Sinclair là huyền thoại bóng đá nữ nước nào?', ['Canada', 'Mỹ', 'Anh'], 0),
    makeQuestion('ca-h6', 'hard', 'Canada thắng Jamaica để vào World Cup 2022 ở vòng loại khu vực nào?', ['CONCACAF', 'UEFA', 'AFC'], 0),
  ],
  brazil: [
    makeQuestion('br-e1', 'easy', 'Brazil vô địch World Cup bao nhiêu lần?', ['3', '5', '7'], 1),
    makeQuestion('br-e2', 'easy', 'Màu vàng trên cờ Brazil tượng trưng?', ['Vàng kim', 'Mặt trời', 'Cát biển'], 0),
    makeQuestion('br-e3', 'easy', 'Thủ đô Brazil là?', ['Brasília', 'Rio de Janeiro', 'São Paulo'], 0),
    makeQuestion('br-e4', 'easy', 'Brazil nói tiếng gì?', ['Tiếng Bồ Đào Nha', 'Tiếng Tây Ban Nha', 'Tiếng Anh'], 0),
    makeQuestion('br-e5', 'easy', 'Carnival Rio nổi tiếng ở quốc gia nào?', ['Brazil', 'Mexico', 'Ý'], 0),
    makeQuestion('br-e6', 'easy', 'Rừng Amazon chủ yếu nằm ở quốc gia nào?', ['Brazil', 'Argentina', 'Chile'], 0),
    makeQuestion('br-m1', 'medium', 'Pelé từng chơi cho đội tuyển nào?', ['Brazil', 'Argentina', 'Bồ Đào Nha'], 0),
    makeQuestion('br-m2', 'medium', 'Feijoada là món đặc trưng của nước nào?', ['Brazil', 'Pháp', 'Nhật Bản'], 0),
    makeQuestion('br-m3', 'medium', 'Sân Maracanã nằm ở thành phố nào?', ['Rio de Janeiro', 'Salvador', 'Recife'], 0),
    makeQuestion('br-m4', 'medium', 'Brazil vô địch World Cup lần đầu năm nào?', ['1958', '1970', '1994'], 0),
    makeQuestion('br-m5', 'medium', 'Đội tuyển Brazil có biệt danh?', ['A Seleção', 'Les Bleus', 'Three Lions'], 0),
    makeQuestion('br-m6', 'medium', 'Neymar là cầu thủ nổi tiếng của nước nào?', ['Brazil', 'Pháp', 'Bồ Đào Nha'], 0),
    makeQuestion('br-h1', 'hard', 'Brazil thua Đức 7-1 ở bán kết World Cup năm nào?', ['2014', '2010', '2018'], 0),
    makeQuestion('br-h2', 'hard', 'Ronaldinho vô địch World Cup cùng Brazil năm nào?', ['2002', '1998', '2006'], 0),
    makeQuestion('br-h3', 'hard', 'Giải Brasileirão là giải vô địch quốc gia của?', ['Brazil', 'Argentina', 'Bồ Đào Nha'], 0),
    makeQuestion('br-h4', 'hard', 'Brazil vô địch World Cup 1970 với cầu thủ nào nổi tiếng?', ['Pelé', 'Maradona', 'Cruyff'], 0),
    makeQuestion('br-h5', 'hard', 'Thành phố São Paulo thuộc quốc gia nào?', ['Brazil', 'Bồ Đào Nha', 'Tây Ban Nha'], 0),
    makeQuestion('br-h6', 'hard', 'Brazil đăng cai World Cup gần nhất năm nào?', ['2014', '2006', '2022'], 0),
  ],
  argentina: [
    makeQuestion('ar-e1', 'easy', 'Argentina vô địch World Cup 2022 tại quốc gia nào?', ['Qatar', 'Nga', 'Brazil'], 0),
    makeQuestion('ar-e2', 'easy', 'Biểu tượng trên cờ Argentina là?', ['Mặt trời', 'Ngôi sao đỏ', 'Chữ thập'], 0),
    makeQuestion('ar-e3', 'easy', 'Thủ đô Argentina là?', ['Buenos Aires', 'Córdoba', 'Mendoza'], 0),
    makeQuestion('ar-e4', 'easy', 'Tango là điệu nhảy nổi tiếng của nước nào?', ['Argentina', 'Brazil', 'Mexico'], 0),
    makeQuestion('ar-e5', 'easy', 'Argentina nằm ở châu lục nào?', ['Nam Mỹ', 'Châu Âu', 'Châu Phi'], 0),
    makeQuestion('ar-e6', 'easy', 'Messi là cầu thủ nổi tiếng của nước nào?', ['Argentina', 'Brazil', 'Tây Ban Nha'], 0),
    makeQuestion('ar-m1', 'medium', 'Messi chơi vị trí nào?', ['Tiền đạo/Tiền vệ tấn công', 'Thủ môn', 'Trọng tài'], 0),
    makeQuestion('ar-m2', 'medium', 'Asado là món nướng truyền thống của nước nào?', ['Argentina', 'Nhật Bản', 'Anh'], 0),
    makeQuestion('ar-m3', 'medium', 'Argentina vô địch World Cup lần đầu năm nào?', ['1978', '1986', '1990'], 0),
    makeQuestion('ar-m4', 'medium', 'Maradona ghi bàn “Bàn tay của Chúa” ở World Cup nào?', ['1986', '1990', '1994'], 0),
    makeQuestion('ar-m5', 'medium', 'Đội tuyển Argentina có biệt danh?', ['La Albiceleste', 'Oranje', 'Die Mannschaft'], 0),
    makeQuestion('ar-m6', 'medium', 'Sân La Bombonera nổi tiếng ở thành phố nào?', ['Buenos Aires', 'Lima', 'Santiago'], 0),
    makeQuestion('ar-h1', 'hard', 'Argentina vô địch World Cup 2022 hạ đội nào ở chung kết?', ['Pháp', 'Croatia', 'Brazil'], 0),
    makeQuestion('ar-h2', 'hard', 'Maradona vô địch World Cup năm nào với Argentina?', ['1986', '1978', '2022'], 0),
    makeQuestion('ar-h3', 'hard', 'Argentina thua Saudi Arabia ở vòng bảng World Cup nào?', ['2022', '2018', '2014'], 0),
    makeQuestion('ar-h4', 'hard', 'Giải Primera División Argentina có hai đội lớn nào?', ['Boca Juniors và River Plate', 'Real và Barca', 'Inter và Milan'], 0),
    makeQuestion('ar-h5', 'hard', 'Argentina vô địch Copa América 2021 sau loạt penalty với?', ['Brazil', 'Chile', 'Uruguay'], 0),
    makeQuestion('ar-h6', 'hard', 'Thác Iguazu nằm giữa Argentina và nước nào?', ['Brazil', 'Chile', 'Peru'], 0),
  ],
  france: [
    makeQuestion('fr-e1', 'easy', 'Thủ đô Pháp là?', ['Paris', 'Lyon', 'Marseille'], 0),
    makeQuestion('fr-e2', 'easy', 'Cờ Pháp có mấy dải màu dọc?', ['2', '3', '4'], 1),
    makeQuestion('fr-e3', 'easy', 'Tháp Eiffel nằm ở thành phố nào?', ['Paris', 'Nice', 'Bordeaux'], 0),
    makeQuestion('fr-e4', 'easy', 'Pháp nằm ở châu lục nào?', ['Châu Âu', 'Châu Phi', 'Châu Á'], 0),
    makeQuestion('fr-e5', 'easy', 'Bánh mì baguette nổi tiếng của nước nào?', ['Pháp', 'Ý', 'Đức'], 0),
    makeQuestion('fr-e6', 'easy', 'Màu xanh trên cờ Pháp gọi là?', ['Xanh dương', 'Xanh lá', 'Xanh ngọc'], 0),
    makeQuestion('fr-m1', 'medium', 'Pháp vô địch World Cup 2018 tại nước nào?', ['Nga', 'Qatar', 'Brazil'], 0),
    makeQuestion('fr-m2', 'medium', 'Zidane từng chơi cho đội tuyển nào?', ['Pháp', 'Ý', 'Tây Ban Nha'], 0),
    makeQuestion('fr-m3', 'medium', 'Pháp vô địch World Cup 1998 trên sân nhà, đánh bại ai ở chung kết?', ['Brazil', 'Đức', 'Argentina'], 0),
    makeQuestion('fr-m4', 'medium', 'Mbappé ghi bao nhiêu bàn ở chung kết World Cup 2022?', ['2', '3', '4'], 1),
    makeQuestion('fr-m5', 'medium', 'Đội tuyển Pháp có biệt danh?', ['Les Bleus', 'Azzurri', 'La Roja'], 0),
    makeQuestion('fr-m6', 'medium', 'Sân Stade de France ở đâu?', ['Saint-Denis gần Paris', 'Lyon', 'Marseille'], 0),
    makeQuestion('fr-h1', 'hard', 'Pháp vô địch World Cup 2018 hạ Croatia với tỷ số chung kết?', ['4-2', '2-1', '3-3'], 0),
    makeQuestion('fr-h2', 'hard', 'Henry là cầu thủ ghi bàn nhiều nhất lịch sử đội tuyển nước nào (trước Mbappé)?', ['Pháp', 'Anh', 'Bồ Đào Nha'], 0),
    makeQuestion('fr-h3', 'hard', 'Pháp vô địch Euro 1984 với cầu thủ huyền thoại nào?', ['Platini', 'Zidane', 'Griezmann'], 0),
    makeQuestion('fr-h4', 'hard', 'Giải Ligue 1 là giải bóng đá nội địa của nước nào?', ['Pháp', 'Bỉ', 'Hà Lan'], 0),
    makeQuestion('fr-h5', 'hard', 'Pháp thua Argentina ở chung kết World Cup 2022 sau hiệp?', ['Hiệp chính + hiệp phụ + penalty', 'Chỉ hiệp chính', 'Chỉ hiệp phụ'], 0),
    makeQuestion('fr-h6', 'hard', 'Kylian Mbappé sinh ra ở thành phố nào của Pháp?', ['Bondy gần Paris', 'Marseille', 'Lille'], 0),
  ],
  germany: [
    makeQuestion('de-e1', 'easy', 'Đức vô địch World Cup bao nhiêu lần?', ['2', '4', '6'], 1),
    makeQuestion('de-e2', 'easy', 'Màu vàng trên cờ Đức là?', ['Vàng kim', 'Cam', 'Hồng'], 0),
    makeQuestion('de-e3', 'easy', 'Thủ đô Đức là?', ['Berlin', 'Munich', 'Hamburg'], 0),
    makeQuestion('de-e4', 'easy', 'Lễ hội Oktoberfest nổi tiếng ở nước nào?', ['Đức', 'Áo', 'Thụy Sĩ'], 0),
    makeQuestion('de-e5', 'easy', 'Đức nằm ở châu lục nào?', ['Châu Âu', 'Châu Á', 'Bắc Mỹ'], 0),
    makeQuestion('de-e6', 'easy', 'Xúc xích Bratwurst là món của nước nào?', ['Đức', 'Pháp', 'Ba Lan'], 0),
    makeQuestion('de-m1', 'medium', 'Đức vô địch World Cup 2014 tại Brazil, hạ ai ở chung kết?', ['Argentina', 'Brazil', 'Pháp'], 0),
    makeQuestion('de-m2', 'medium', 'Beckenbauer được gọi là gì?', ['Kaiser', 'Maestro', 'El Pibe'], 0),
    makeQuestion('de-m3', 'medium', 'Đức đăng cai World Cup gần nhất năm nào?', ['2006', '2010', '2014'], 0),
    makeQuestion('de-m4', 'medium', 'Giải Bundesliga là của nước nào?', ['Đức', 'Áo', 'Hà Lan'], 0),
    makeQuestion('de-m5', 'medium', 'Đội tuyển Đức có biệt danh?', ['Die Mannschaft / Nationalmannschaft', 'Oranje', 'Tricolor'], 0),
    makeQuestion('de-m6', 'medium', 'Müller là họ cầu thủ nổi tiếng của đội tuyển nào?', ['Đức', 'Brazil', 'Mexico'], 0),
    makeQuestion('de-h1', 'hard', 'Đức thua Hàn Quốc ở vòng bảng World Cup năm nào?', ['2018', '2014', '2022'], 0),
    makeQuestion('de-h2', 'hard', 'Gerd Müller ghi nhiều bàn ở World Cup 1970 cho nước nào?', ['Đức', 'Brazil', 'Anh'], 0),
    makeQuestion('de-h3', 'hard', 'Đức thống nhất và đội tuyển hợp nhất sau năm nào?', ['1990', '1970', '2000'], 0),
    makeQuestion('de-h4', 'hard', 'Bayern Munich thuộc giải đấu nào?', ['Bundesliga', 'Premier League', 'Serie A'], 0),
    makeQuestion('de-h5', 'hard', 'Đức vô địch World Cup 1990 hạ Argentina với bàn thắng của?', ['Brehme (penalty)', 'Klose', 'Götze'], 0),
    makeQuestion('de-h6', 'hard', 'Sân Allianz Arena ở thành phố nào?', ['Munich', 'Berlin', 'Dortmund'], 0),
  ],
  spain: [
    makeQuestion('es-e1', 'easy', 'Tây Ban Nha vô địch World Cup năm nào?', ['2006', '2010', '2014'], 1),
    makeQuestion('es-e2', 'easy', 'Thủ đô Tây Ban Nha là?', ['Madrid', 'Barcelona', 'Seville'], 0),
    makeQuestion('es-e3', 'easy', 'Flamenco là nghệ thuật của nước nào?', ['Tây Ban Nha', 'Brazil', 'Mexico'], 0),
    makeQuestion('es-e4', 'easy', 'Tây Ban Nha nằm ở châu lục nào?', ['Châu Âu', 'Nam Mỹ', 'Châu Phi'], 0),
    makeQuestion('es-e5', 'easy', 'Công trình Sagrada Familia của Gaudí ở thành phố nào?', ['Barcelona', 'Madrid', 'Valencia'], 0),
    makeQuestion('es-e6', 'easy', 'Ngôn ngữ chính thức của Tây Ban Nha là?', ['Tiếng Tây Ban Nha', 'Tiếng Bồ Đào Nha', 'Tiếng Catalan duy nhất'], 0),
    makeQuestion('es-m1', 'medium', 'Món paella thường có gì?', ['Cơm và hải sản', 'Bánh mì', 'Mì Ý'], 0),
    makeQuestion('es-m2', 'medium', 'Iniesta ghi bàn ở chung kết World Cup 2010 hạ đội nào?', ['Hà Lan', 'Đức', 'Brazil'], 0),
    makeQuestion('es-m3', 'medium', 'Real Madrid và Barcelona thuộc giải đấu nào?', ['La Liga', 'Premier League', 'Serie A'], 0),
    makeQuestion('es-m4', 'medium', 'Tây Ban Nha vô địch Euro liên tiếp mấy lần?', ['1', '2', '3'], 1),
    makeQuestion('es-m5', 'medium', 'Đội tuyển Tây Ban Nha có biệt danh?', ['La Roja', 'Azzurri', 'Les Bleus'], 0),
    makeQuestion('es-m6', 'medium', 'Torres là tiền đạo nổi tiếng của nước nào?', ['Tây Ban Nha', 'Argentina', 'Ý'], 0),
    makeQuestion('es-h1', 'hard', 'Tây Ban Nha vô địch World Cup 2010 tại Nam Phi, thua ai ở vòng bảng?', ['Thụy Sĩ', 'Brazil', 'Đức'], 0),
    makeQuestion('es-h2', 'hard', 'Xavi và Iniesta là bộ đôi tiền vệ của đội tuyển nào?', ['Tây Ban Nha', 'Brazil', 'Pháp'], 0),
    makeQuestion('es-h3', 'hard', 'Tây Ban Nha vô địch Euro 2008 hạ Đức với tỷ số?', ['1-0', '2-1', '3-2'], 0),
    makeQuestion('es-h4', 'hard', 'Casillas là thủ môn huyền thoại của nước nào?', ['Tây Ban Nha', 'Mexico', 'Bồ Đào Nha'], 0),
    makeQuestion('es-h5', 'hard', 'Tây Ban Nha thua Nhật Bản ở World Cup 2022 với tỷ số?', ['1-2', '0-1', '2-2'], 0),
    makeQuestion('es-h6', 'hard', 'Sân Camp Nou là sân nhà của đội nào?', ['Barcelona', 'Real Madrid', 'Atlético Madrid'], 0),
  ],
  england: [
    makeQuestion('en-e1', 'easy', 'Anh vô địch World Cup năm nào?', ['1966', '1970', '1990'], 0),
    makeQuestion('en-e2', 'easy', 'Thủ đô Anh là?', ['London', 'Manchester', 'Liverpool'], 0),
    makeQuestion('en-e3', 'easy', 'Cung điện Buckingham ở thành phố nào?', ['London', 'Edinburgh', 'Cardiff'], 0),
    makeQuestion('en-e4', 'easy', 'Fish and chips là món của nước nào?', ['Anh', 'Pháp', 'Mỹ'], 0),
    makeQuestion('en-e5', 'easy', 'Anh nằm ở châu lục nào?', ['Châu Âu', 'Bắc Mỹ', 'Châu Đại Dương'], 0),
    makeQuestion('en-e6', 'easy', 'Big Ben là tháp đồng hồ ở thành phố nào?', ['London', 'Birmingham', 'Leeds'], 0),
    makeQuestion('en-m1', 'medium', 'Giải bóng đá nhà nghề Anh là?', ['Premier League', 'La Liga', 'Bundesliga'], 0),
    makeQuestion('en-m2', 'medium', 'Món fish and chips gồm?', ['Cá chiên và khoai tây', 'Bánh mì và phô mai', 'Cơm và thịt'], 0),
    makeQuestion('en-m3', 'medium', 'Wembley là gì?', ['Sân vận động', 'Sông', 'Núi'], 0),
    makeQuestion('en-m4', 'medium', 'Anh được gọi là quê hương của môn thể thao nào?', ['Bóng đá hiện đại', 'Bóng rổ', 'Cricket'], 0),
    makeQuestion('en-m5', 'medium', 'Đội tuyển Anh có biệt danh?', ['Three Lions', 'Oranje', 'Samurai Blue'], 0),
    makeQuestion('en-m6', 'medium', 'Kane là tiền đạo nổi tiếng của nước nào?', ['Anh', 'Mỹ', 'Úc'], 0),
    makeQuestion('en-h1', 'hard', 'Anh vô địch World Cup 1966 hạ đội nào?', ['Đức', 'Brazil', 'Argentina'], 0),
    makeQuestion('en-h2', 'hard', 'Bobby Charlton là huyền thoại của đội tuyển nào?', ['Anh', 'Scotland', 'Ireland'], 0),
    makeQuestion('en-h3', 'hard', 'Anh vào chung kết Euro 2020 (2021) thua đội nào?', ['Ý', 'Tây Ban Nha', 'Đan Mạch'], 0),
    makeQuestion('en-h4', 'hard', 'Liverpool và Manchester United thuộc giải nào?', ['Premier League', 'Championship', 'Serie A'], 0),
    makeQuestion('en-h5', 'hard', 'Anh thua Iceland ở Euro 2016 vòng nào?', ['Vòng 16', 'Tứ kết', 'Bán kết'], 0),
    makeQuestion('en-h6', 'hard', 'Bellingham là cầu thủ trẻ sinh ra ở thành phố nào của Anh?', ['Stourbridge / Birmingham', 'London', 'Manchester'], 0),
  ],
  japan: [
    makeQuestion('jp-e1', 'easy', 'Biểu tượng trên cờ Nhật Bản là?', ['Mặt trời đỏ', 'Ngôi sao vàng', 'Chữ thập'], 0),
    makeQuestion('jp-e2', 'easy', 'Thủ đô Nhật Bản là?', ['Tokyo', 'Osaka', 'Kyoto'], 0),
    makeQuestion('jp-e3', 'easy', 'Hoa anh đào nổi tiếng của nước nào?', ['Nhật Bản', 'Hàn Quốc', 'Trung Quốc'], 0),
    makeQuestion('jp-e4', 'easy', 'Nhật Bản nằm ở châu lục nào?', ['Châu Á', 'Châu Âu', 'Châu Đại Dương'], 0),
    makeQuestion('jp-e5', 'easy', 'Sushi là món nổi tiếng của nước nào?', ['Nhật Bản', 'Thái Lan', 'Việt Nam'], 0),
    makeQuestion('jp-e6', 'easy', 'Núi Phú Sĩ (Fuji) ở quốc gia nào?', ['Nhật Bản', 'Hàn Quốc', 'Nepal'], 0),
    makeQuestion('jp-m1', 'medium', 'Món sushi thường dùng gì?', ['Cơm và cá', 'Bánh mì', 'Mì Ý'], 0),
    makeQuestion('jp-m2', 'medium', 'Nhật Bản đồng chủ nhà World Cup 2002 cùng nước nào?', ['Hàn Quốc', 'Trung Quốc', 'Thái Lan'], 0),
    makeQuestion('jp-m3', 'medium', 'J-League là giải bóng đá của nước nào?', ['Nhật Bản', 'Hàn Quốc', 'Trung Quốc'], 0),
    makeQuestion('jp-m4', 'medium', 'Nhật Bản vào vòng 16 đội World Cup 2022 hạ đội nào?', ['Đức', 'Brazil', 'Pháp'], 0),
    makeQuestion('jp-m5', 'medium', 'Đội tuyển Nhật có biệt danh?', ['Samurai Blue', 'Dragon Team', 'Red Devils'], 0),
    makeQuestion('jp-m6', 'medium', 'Ramen là món mì của nước nào?', ['Nhật Bản', 'Trung Quốc', 'Hàn Quốc'], 0),
    makeQuestion('jp-h1', 'hard', 'Nhật Bản thua Croatia ở vòng 16 World Cup 2022 sau?', ['Loạt penalty', 'Hiệp phụ', 'Bàn thắng vàng'], 0),
    makeQuestion('jp-h2', 'hard', 'Hidetoshi Nakata từng chơi ở Serie A cho nước nào?', ['Nhật Bản', 'Hàn Quốc', 'Iran'], 0),
    makeQuestion('jp-h3', 'hard', 'Nhật Bản thắng Tây Ban Nha ở World Cup 2022 với tỷ số?', ['2-1', '1-0', '3-2'], 0),
    makeQuestion('jp-h4', 'hard', 'World Cup 2002 có trận chung kết ở sân nào?', ['Yokohama International', 'Tokyo Dome', 'Sapporo Dome'], 0),
    makeQuestion('jp-h5', 'hard', 'Keisuke Honda ghi bàn đẹp sút xa cho Nhật ở World Cup nào?', ['2018', '2010', '2006'], 0),
    makeQuestion('jp-h6', 'hard', 'Nhật Bản là nước châu Á đầu tiên vô địch cúp châu lục nào (nữ)?', ['World Cup nữ', 'Asian Cup nam 4 lần', 'Không có'], 1),
  ],
  morocco: [
    makeQuestion('ma-e1', 'easy', 'Morocco thuộc châu lục nào?', ['Châu Phi', 'Châu Á', 'Châu Âu'], 0),
    makeQuestion('ma-e2', 'easy', 'Thủ đô Morocco là?', ['Rabat', 'Casablanca', 'Marrakech'], 0),
    makeQuestion('ma-e3', 'easy', 'Cờ Morocco có hình gì ở giữa?', ['Ngôi sao xanh', 'Mặt trời', 'Chữ thập'], 0),
    makeQuestion('ma-e4', 'easy', 'Morocco giáp đại dương nào?', ['Đại Tây Dương', 'Thái Bình Dương', 'Bắc Băng Dương'], 0),
    makeQuestion('ma-e5', 'easy', 'Thành phố Marrakech nổi tiếng với quảng trường nào?', ['Jemaa el-Fnaa', 'Trafalgar', 'Red Square'], 0),
    makeQuestion('ma-e6', 'easy', 'Tiếng Ả Rập và tiếng Amazigh là ngôn ngữ của nước nào?', ['Morocco', 'Ai Cập', 'Kenya'], 0),
    makeQuestion('ma-m1', 'medium', 'Morocco vào vòng nào tại World Cup 2022?', ['Vòng 16', 'Tứ kết', 'Bán kết'], 2),
    makeQuestion('ma-m2', 'medium', 'Món tagine là?', ['Món hầm', 'Bánh ngọt', 'Đồ uống'], 0),
    makeQuestion('ma-m3', 'medium', 'Hakimi chơi vị trí nào?', ['Hậu vệ cánh', 'Thủ môn', 'Tiền đạo'], 0),
    makeQuestion('ma-m4', 'medium', 'Morocco thua ai ở bán kết World Cup 2022?', ['Pháp', 'Argentina', 'Croatia'], 0),
    makeQuestion('ma-m5', 'medium', 'Đội tuyển Morocco có biệt danh?', ['Atlas Lions', 'Black Stars', 'Super Eagles'], 0),
    makeQuestion('ma-m6', 'medium', 'Casablanca là thành phố lớn nhất của nước nào?', ['Morocco', 'Algeria', 'Tunisia'], 0),
    makeQuestion('ma-h1', 'hard', 'Morocco thắng Bồ Đào Nha ở tứ kết World Cup 2022 với tỷ số?', ['1-0', '2-1', '3-2'], 0),
    makeQuestion('ma-h2', 'hard', 'En-Nesyri ghi bàn đánh đầu nổi tiếng cho Morocco ở World Cup nào?', ['2022', '2018', '2014'], 0),
    makeQuestion('ma-h3', 'hard', 'Morocco là đội châu Phi đầu tiên vào bán kết World Cup năm nào?', ['2022', '2010', '1998'], 0),
    makeQuestion('ma-h4', 'hard', 'Sahel và Sahara liên quan đến vùng nào của Morocco?', ['Địa lý phía nam và đông', 'Chỉ phía bắc', 'Chỉ ven biển'], 0),
    makeQuestion('ma-h5', 'hard', 'Giải Botola Pro là giải nội địa của nước nào?', ['Morocco', 'Senegal', 'Nigeria'], 0),
    makeQuestion('ma-h6', 'hard', 'Morocco thắng Bỉ ở vòng bảng World Cup 2022 với tỷ số?', ['2-0', '1-1', '3-1'], 0),
  ],
  portugal: [
    makeQuestion('pt-e1', 'easy', 'Cristiano Ronaldo đến từ nước nào?', ['Bồ Đào Nha', 'Brazil', 'Tây Ban Nha'], 0),
    makeQuestion('pt-e2', 'easy', 'Thủ đô Bồ Đào Nha là?', ['Lisbon', 'Porto', 'Faro'], 0),
    makeQuestion('pt-e3', 'easy', 'Bồ Đào Nha nằm ở châu lục nào?', ['Châu Âu', 'Nam Mỹ', 'Châu Phi'], 0),
    makeQuestion('pt-e4', 'easy', 'Pastel de nata là bánh của nước nào?', ['Bồ Đào Nha', 'Pháp', 'Ý'], 0),
    makeQuestion('pt-e5', 'easy', 'Cầu Luis I nổi tiếng ở thành phố nào?', ['Porto', 'Lisbon', 'Faro'], 0),
    makeQuestion('pt-e6', 'easy', 'Ngôn ngữ chính thức của Bồ Đào Nha là?', ['Tiếng Bồ Đào Nha', 'Tiếng Tây Ban Nha', 'Tiếng Anh'], 0),
    makeQuestion('pt-m1', 'medium', 'Bồ Đào Nha vô địch Euro năm nào?', ['2012', '2016', '2020'], 1),
    makeQuestion('pt-m2', 'medium', 'Pastel de nata là loại gì?', ['Bánh trứng ngọt', 'Món mặn', 'Đồ uống'], 0),
    makeQuestion('pt-m3', 'medium', 'Ronaldo ghi nhiều bàn nhất cho đội tuyển nước nào?', ['Bồ Đào Nha', 'Brazil', 'Anh'], 0),
    makeQuestion('pt-m4', 'medium', 'Bồ Đào Nha vô địch Euro 2016 hạ đội nào?', ['Pháp', 'Đức', 'Tây Ban Nha'], 0),
    makeQuestion('pt-m5', 'medium', 'Giải Primeira Liga là của nước nào?', ['Bồ Đào Nha', 'Brazil', 'Angola'], 0),
    makeQuestion('pt-m6', 'medium', 'Đội tuyển Bồ Đào Nha có biệt danh?', ['A Seleção das Quinas', 'La Roja', 'Oranje'], 0),
    makeQuestion('pt-h1', 'hard', 'Eder ghi bàn quyết định ở chung kết Euro 2016 cho nước nào?', ['Bồ Đào Nha', 'Pháp', 'Croatia'], 0),
    makeQuestion('pt-h2', 'hard', 'Bồ Đào Nha vô địch Nations League 2019 hạ đội nào?', ['Hà Lan', 'Anh', 'Tây Ban Nha'], 0),
    makeQuestion('pt-h3', 'hard', 'Figo là cầu thủ huyền thoại của nước nào?', ['Bồ Đào Nha', 'Brazil', 'Argentina'], 0),
    makeQuestion('pt-h4', 'hard', 'Bồ Đào Nha thua Morocco ở vòng bảng World Cup 2022 với tỷ số?', ['0-1', '1-2', '0-2'], 0),
    makeQuestion('pt-h5', 'hard', 'Ronaldo ghi hat-trick thắng Tây Ban Nha ở World Cup nào?', ['2018', '2014', '2022'], 0),
    makeQuestion('pt-h6', 'hard', 'Benfica và Porto thuộc giải đấu nào?', ['Primeira Liga', 'La Liga', 'Eredivisie'], 0),
  ],
};
