import type { ClassifyItem } from './questions';
/** Phân loại Cửu Long bổ sung — 162 mục */
export const ITEMS_SUPPLEMENT: ClassifyItem[] = [
  { id: '31', label: 'Cá chép', emoji: '🐟', bin: 'dong-vat' },
  { id: '32', label: 'Sen hồng', emoji: '🪷', bin: 'thuc-vat' },
  { id: '33', label: 'Nước dâng', emoji: '🌊', bin: 'hien-tuong' },
  { id: '34', label: 'Tôm càng xanh', emoji: '🦐', bin: 'dong-vat' },
  { id: '35', label: 'Bèo sen', emoji: '🍃', bin: 'thuc-vat' },
  { id: '36', label: 'Lũ lụt', emoji: '🌊', bin: 'hien-tuong' },
  { id: '37', label: 'Vịt trời', emoji: '🦆', bin: 'dong-vat' },
  { id: '38', label: 'Cây nhãn', emoji: '🌳', bin: 'thuc-vat' },
  { id: '39', label: 'Hạn hán', emoji: '☀️', bin: 'hien-tuong' },
  { id: '40', label: 'Cá mè', emoji: '🐟', bin: 'dong-vat' },
  { id: '41', label: 'Rau nhút', emoji: '🥬', bin: 'thuc-vat' },
  { id: '42', label: 'Sương muối', emoji: '🌫️', bin: 'hien-tuong' },
  { id: '43', label: 'Ếch tía', emoji: '🐸', bin: 'dong-vat' },
  { id: '44', label: 'Cây bình bát', emoji: '🌿', bin: 'thuc-vat' },
  { id: '45', label: 'Triều cường', emoji: '🌊', bin: 'hien-tuong' },
  { id: '46', label: 'Chuột chù', emoji: '🐭', bin: 'dong-vat' },
  { id: '47', label: 'Cây điền điển', emoji: '🌳', bin: 'thuc-vat' },
  { id: '48', label: 'Mưa phùn', emoji: '🌧️', bin: 'hien-tuong' },
  { id: '49', label: 'Cá rô', emoji: '🐠', bin: 'dong-vat' },
  { id: '50', label: 'Bông điền', emoji: '🌸', bin: 'thuc-vat' },
  { id: '51', label: 'Gió lốc', emoji: '🌪️', bin: 'hien-tuong' },
  { id: '52', label: 'Rắn nước', emoji: '🐍', bin: 'dong-vat' },
  { id: '53', label: 'Cây chà là', emoji: '🌴', bin: 'thuc-vat' },
  { id: '54', label: 'Sạt lở bờ', emoji: '⛰️', bin: 'hien-tuong' },
  { id: '55', label: 'Cua đồng', emoji: '🦀', bin: 'dong-vat' },
  { id: '56', label: 'Lúa nước', emoji: '🌾', bin: 'thuc-vat' },
  { id: '57', label: 'Nắng nóng', emoji: '🔥', bin: 'hien-tuong' },
  { id: '58', label: 'Cò bợ', emoji: '🦩', bin: 'dong-vat' },
  { id: '59', label: 'Cây bần', emoji: '🌳', bin: 'thuc-vat' },
  { id: '60', label: 'Mưa dông', emoji: '⛈️', bin: 'hien-tuong' },
  { id: '61', label: 'Cá thát lát', emoji: '🐟', bin: 'dong-vat' },
  { id: '62', label: 'Rau muống', emoji: '🥗', bin: 'thuc-vat' },
  { id: '63', label: 'Sấm chớp', emoji: '⚡', bin: 'hien-tuong' },
  { id: '64', label: 'Ốc nhồi', emoji: '🐌', bin: 'dong-vat' },
  { id: '65', label: 'Cây tràm', emoji: '🌲', bin: 'thuc-vat' },
  { id: '66', label: 'Bão nhiệt đới', emoji: '🌀', bin: 'hien-tuong' },
  { id: '67', label: 'Chim cút', emoji: '🐦', bin: 'dong-vat' },
  { id: '68', label: 'Hoa súng', emoji: '🪷', bin: 'thuc-vat' },
  { id: '69', label: 'Nước mặn xâm nhập', emoji: '🧂', bin: 'hien-tuong' },
  { id: '70', label: 'Cá chốt', emoji: '🐟', bin: 'dong-vat' },
  { id: '71', label: 'Cây vú sữa', emoji: '🌳', bin: 'thuc-vat' },
  { id: '72', label: 'Khô hạn', emoji: '🏜️', bin: 'hien-tuong' },
  { id: '73', label: 'Tôm đất', emoji: '🦐', bin: 'dong-vat' },
  { id: '74', label: 'Cây mận', emoji: '🌳', bin: 'thuc-vat' },
  { id: '75', label: 'Sương giá', emoji: '❄️', bin: 'hien-tuong' },
  { id: '76', label: 'Nhện cây', emoji: '🕷️', bin: 'dong-vat' },
  { id: '77', label: 'Cây khế', emoji: '🌳', bin: 'thuc-vat' },
  { id: '78', label: 'Lốc xoáy', emoji: '🌪️', bin: 'hien-tuong' },
  { id: '79', label: 'Dế đồng', emoji: '🦗', bin: 'dong-vat' },
  { id: '80', label: 'Cây nhãn lồng', emoji: '🌳', bin: 'thuc-vat' },
  { id: '81', label: 'Mưa acid', emoji: '🧪', bin: 'hien-tuong' },
  { id: '82', label: 'Cá diếc', emoji: '🐟', bin: 'dong-vat' },
  { id: '83', label: 'Cây dừa', emoji: '🥥', bin: 'thuc-vat' },
  { id: '84', label: 'Bụi mù', emoji: '🌫️', bin: 'hien-tuong' },
  { id: '85', label: 'Thằn lằn', emoji: '🦎', bin: 'dong-vat' },
  { id: '86', label: 'Cây chôm chôm', emoji: '🌳', bin: 'thuc-vat' },
  { id: '87', label: 'Nước thủy triều', emoji: '🌊', bin: 'hien-tuong' },
  { id: '88', label: 'Chuồn chuồn', emoji: '🪰', bin: 'dong-vat' },
  { id: '89', label: 'Cây mít', emoji: '🌳', bin: 'thuc-vat' },
  { id: '90', label: 'Gió monsoon', emoji: '💨', bin: 'hien-tuong' },
  { id: '91', label: 'Cá trê', emoji: '🐟', bin: 'dong-vat' },
  { id: '92', label: 'Cây sầu riêng', emoji: '🌳', bin: 'thuc-vat' },
  { id: '93', label: 'Sạt lở đất', emoji: '🏔️', bin: 'hien-tuong' },
  { id: '94', label: 'Bọ cạp', emoji: '🦂', bin: 'dong-vat' },
  { id: '95', label: 'Cây thanh long', emoji: '🌵', bin: 'thuc-vat' },
  { id: '96', label: 'Mưa lớn', emoji: '🌧️', bin: 'hien-tuong' },
  { id: '97', label: 'Cá hồi', emoji: '🐟', bin: 'dong-vat' },
  { id: '98', label: 'Cây bưởi', emoji: '🍊', bin: 'thuc-vat' },
  { id: '99', label: 'Áp thấp', emoji: '🌀', bin: 'hien-tuong' },
  { id: '100', label: 'Kiến vàng', emoji: '🐜', bin: 'dong-vat' },
  { id: '101', label: 'Cây cam', emoji: '🍊', bin: 'thuc-vat' },
  { id: '102', label: 'Nắng gắt', emoji: '☀️', bin: 'hien-tuong' },
  { id: '103', label: 'Giun đất', emoji: '🪱', bin: 'dong-vat' },
  { id: '104', label: 'Cây xoài', emoji: '🥭', bin: 'thuc-vat' },
  { id: '105', label: 'Sương mù dày', emoji: '🌫️', bin: 'hien-tuong' },
  { id: '106', label: 'Cá ngừ', emoji: '🐟', bin: 'dong-vat' },
  { id: '107', label: 'Cây ổi', emoji: '🍐', bin: 'thuc-vat' },
  { id: '108', label: 'Lũ quét', emoji: '🌊', bin: 'hien-tuong' },
  { id: '109', label: 'Bướm đêm', emoji: '🦋', bin: 'dong-vat' },
  { id: '110', label: 'Cây nhãn', emoji: '🌳', bin: 'thuc-vat' },
  { id: '111', label: 'Gió giật', emoji: '💨', bin: 'hien-tuong' },
  { id: '112', label: 'Nòng nọc', emoji: '🐸', bin: 'dong-vat' },
  { id: '113', label: 'Cây măng cụt', emoji: '🍇', bin: 'thuc-vat' },
  { id: '114', label: 'Mưa rào', emoji: '🌧️', bin: 'hien-tuong' },
  { id: '115', label: 'Cá nục', emoji: '🐟', bin: 'dong-vat' },
  { id: '116', label: 'Cây vải', emoji: '🍒', bin: 'thuc-vat' },
  { id: '117', label: 'Khí hậu ẩm', emoji: '💧', bin: 'hien-tuong' },
  { id: '118', label: 'Châu chấu', emoji: '🦗', bin: 'dong-vat' },
  { id: '119', label: 'Cây na', emoji: '🌳', bin: 'thuc-vat' },
  { id: '120', label: 'Nhiệt độ tăng', emoji: '🌡️', bin: 'hien-tuong' },
  { id: '121', label: 'Cá hồng', emoji: '🐟', bin: 'dong-vat' },
  { id: '122', label: 'Cây khế chua', emoji: '🌿', bin: 'thuc-vat' },
  { id: '123', label: 'Bão cuốn', emoji: '🌀', bin: 'hien-tuong' },
  { id: '124', label: 'Nhện nước', emoji: '🕷️', bin: 'dong-vat' },
  { id: '125', label: 'Cây đu đủ', emoji: '🌴', bin: 'thuc-vat' },
  { id: '126', label: 'Sóng thần', emoji: '🌊', bin: 'hien-tuong' },
  { id: '127', label: 'Cá mòi', emoji: '🐟', bin: 'dong-vat' },
  { id: '128', label: 'Cây me', emoji: '🌳', bin: 'thuc-vat' },
  { id: '129', label: 'Hơi nước bốc', emoji: '💨', bin: 'hien-tuong' },
  { id: '130', label: 'Đom đóm', emoji: '✨', bin: 'dong-vat' },
  { id: '131', label: 'Cây sắn', emoji: '🌿', bin: 'thuc-vat' },
  { id: '132', label: 'Mưa ngâu', emoji: '🌧️', bin: 'hien-tuong' },
  { id: '133', label: 'Cá trích', emoji: '🐟', bin: 'dong-vat' },
  { id: '134', label: 'Cây khoai lang', emoji: '🍠', bin: 'thuc-vat' },
  { id: '135', label: 'Gió mùa đông bắc', emoji: '❄️', bin: 'hien-tuong' },
  { id: '136', label: 'Chim sẻ', emoji: '🐦', bin: 'dong-vat' },
  { id: '137', label: 'Cây đậu phộng', emoji: '🥜', bin: 'thuc-vat' },
  { id: '138', label: 'Nước ngập úng', emoji: '🌊', bin: 'hien-tuong' },
  { id: '139', label: 'Cá ngựa', emoji: '🐴', bin: 'dong-vat' },
  { id: '140', label: 'Cây lạc', emoji: '🥜', bin: 'thuc-vat' },
  { id: '141', label: 'Khô cằn', emoji: '🏜️', bin: 'hien-tuong' },
  { id: '142', label: 'Ong mật', emoji: '🐝', bin: 'dong-vat' },
  { id: '143', label: 'Cây đậu xanh', emoji: '🫘', bin: 'thuc-vat' },
  { id: '144', label: 'Mưa phù sa', emoji: '🌧️', bin: 'hien-tuong' },
  { id: '145', label: 'Cá chim', emoji: '🐟', bin: 'dong-vat' },
  { id: '146', label: 'Cây ngô', emoji: '🌽', bin: 'thuc-vat' },
  { id: '147', label: 'Áp suất thấp', emoji: '📉', bin: 'hien-tuong' },
  { id: '148', label: 'Dơi', emoji: '🦇', bin: 'dong-vat' },
  { id: '149', label: 'Cây lúa mì', emoji: '🌾', bin: 'thuc-vat' },
  { id: '150', label: 'Cháy rừng', emoji: '🔥', bin: 'hien-tuong' },
  { id: '151', label: 'Cá mập', emoji: '🦈', bin: 'dong-vat' },
  { id: '152', label: 'Cây khoai tây', emoji: '🥔', bin: 'thuc-vat' },
  { id: '153', label: 'Bụi khói', emoji: '💨', bin: 'hien-tuong' },
  { id: '154', label: 'Sứa', emoji: '🪼', bin: 'dong-vat' },
  { id: '155', label: 'Cây rau má', emoji: '🌿', bin: 'thuc-vat' },
  { id: '156', label: 'Tuyết rơi', emoji: '❄️', bin: 'hien-tuong' },
  { id: '157', label: 'Sao biển', emoji: '⭐', bin: 'dong-vat' },
  { id: '158', label: 'Cây rau ngót', emoji: '🥬', bin: 'thuc-vat' },
  { id: '159', label: 'Băng tan', emoji: '🧊', bin: 'hien-tuong' },
  { id: '160', label: 'Cá voi', emoji: '🐋', bin: 'dong-vat' },
  { id: '161', label: 'Cây rau đay', emoji: '🥗', bin: 'thuc-vat' },
  { id: '162', label: 'Hạn mặn', emoji: '🧂', bin: 'hien-tuong' },
  { id: '163', label: 'Rùa biển', emoji: '🐢', bin: 'dong-vat' },
  { id: '164', label: 'Cây rau muống', emoji: '🥬', bin: 'thuc-vat' },
  { id: '165', label: 'Xói mòn', emoji: '🏔️', bin: 'hien-tuong' },
  { id: '166', label: 'Cá heo', emoji: '🐬', bin: 'dong-vat' },
  { id: '167', label: 'Cây rau cải', emoji: '🥬', bin: 'thuc-vat' },
  { id: '168', label: 'Ô nhiễm nước', emoji: '☣️', bin: 'hien-tuong' },
  { id: '169', label: 'Hải âu', emoji: '🕊️', bin: 'dong-vat' },
  { id: '170', label: 'Cây rau dền', emoji: '🥬', bin: 'thuc-vat' },
  { id: '171', label: 'Thủy triều', emoji: '🌊', bin: 'hien-tuong' },
  { id: '172', label: 'Cá mực', emoji: '🦑', bin: 'dong-vat' },
  { id: '173', label: 'Cây rau lang', emoji: '🥬', bin: 'thuc-vat' },
  { id: '174', label: 'El Nino', emoji: '🌡️', bin: 'hien-tuong' },
  { id: '175', label: 'Cua ghẹ', emoji: '🦀', bin: 'dong-vat' },
  { id: '176', label: 'Cây rau sam', emoji: '🌿', bin: 'thuc-vat' },
  { id: '177', label: 'La Nina', emoji: '🌧️', bin: 'hien-tuong' },
  { id: '178', label: 'Sam biển', emoji: '⭐', bin: 'dong-vat' },
  { id: '179', label: 'Cây rau muống đồng', emoji: '🥬', bin: 'thuc-vat' },
  { id: '180', label: 'Khí nhà kính', emoji: '🏭', bin: 'hien-tuong' },
  { id: '181', label: 'Sao biển đỏ', emoji: '⭐', bin: 'dong-vat' },
  { id: '182', label: 'Cây rau đắng', emoji: '🌿', bin: 'thuc-vat' },
  { id: '183', label: 'Mưa axit', emoji: '🧪', bin: 'hien-tuong' },
  { id: '184', label: 'Cá nóc', emoji: '🐡', bin: 'dong-vat' },
  { id: '185', label: 'Cây rau muống nước', emoji: '🥬', bin: 'thuc-vat' },
  { id: '186', label: 'Sạt lở ven sông', emoji: '⛰️', bin: 'hien-tuong' },
  { id: '187', label: 'Cá thu', emoji: '🐟', bin: 'dong-vat' },
  { id: '188', label: 'Cây rau sắng', emoji: '🌿', bin: 'thuc-vat' },
  { id: '189', label: 'Nước đục', emoji: '🟤', bin: 'hien-tuong' },
  { id: '190', label: 'Cá ngừ đại dương', emoji: '🐟', bin: 'dong-vat' },
  { id: '191', label: 'Cây rau muống trắng', emoji: '🥬', bin: 'thuc-vat' },
  { id: '192', label: 'Cạn kiệt nước', emoji: '💧', bin: 'hien-tuong' },
];
